### ISSUE TITLE
Can I somehow retrigger the script loading while using page_scripts?

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#101]
Some content on my page can change without page reload, loads dynamically. This content can contain different type of scripts, and I would like to load / execute them based on their category and the user selection.

So example the loaded content would contain a script with `data-cookiecategory="analytics"` and after the content loaded, I'd like to retrigger the function which handles these scripts on page load. Is it possible?

**Comment by orestbida** [comment]
You could use the [`.accept()`](https://github.com/orestbida/cookieconsent#api--configuration-parameters) method like so:

```javascript
// retrieve array of already accepted categories (otherwise set to empty array if no categories are accepted)
var acceptCategories = cookieconsent.get('level') || [];

// add the new category to accept
acceptCategories.push('analytics');

// accept all categories specified above (those already accepted won't be triggered again)
cookieconsent.accept(acceptCategories);
```

**Comment by wzol** [comment]
This is almost good: in my case the category doesn't change, but there are new scripts added to the page as `type="text/plain" data-cookiecategory="analytics"` and I'd like to load / execute them based on the previously selected category.

**Comment by orestbida** [comment]
Yea, It's literally 3 lines of code since it's already implemented under the hood. I don't like the `.update()` naming though, it could be misinterpreted. Perhaps `.updateScripts()` is more fit, even though longer. I'm open to other (better) naming suggestions if you have any

**Comment by wzol** [comment]
I agree, .updateScripts() is better, for me it is fine.
