### ISSUE TITLE
Access values of the config

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#108]
Hi,
would be possible to add a way how to read values of the _config after the plugin was initialized? Or would you accept pull request implementing this?

For example - for analytics purposes, we would like to track the language in which user gave consent. However if the language autodetection is enabled, the language is resolved [internally in the plugin](https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L146-L153), and there doesn't seems to be a way how to get the actual resolved value of the `current_lang`.

I was thinking about something like:
```js
const config = cookieconsent.get('config');
console.log(config.current_lang);

// or to not confuse with `get` which is used for reading  the cookie data
const config = cookieconsent.getConfig();
```

We would also possibly have an use case for reading other values of the config, not only `current_lang`.

There would obviously needs to be only a "get" method for the config, as it could be set only on initialization.

**Comment by orestbida** [comment]
I think we should go with `.getConfig()`. A PR is very welcome!
