### ISSUE TITLE
cc_cookie not created if the domain name includes a port

### ISSUE THREAD

**Issue by parisiam** [orestbida/cookieconsent#11]
Your plugin is awesome and the documentation is very helpful.

I've experienced a problem when using the plugin on my localhost which has a port (i.e. mydomain.com:8890): the cc_cookie is not created.

As a solution, I've replaced all occurences of 'location.host' and 'window.location.host' by 'location.hostname' and 'window.location.hostname'

**Comment by orestbida** [comment]
I see, I've never experienced such an issue even on custom ports (3000). Cookie should (in theory) be set regardless of the port, in fact they should also be accessible (from within the same server) even on different ports.

 Questions:
- is your local server running on https? 
- which browser have you tested it on? (assuming google chrome)

Anyway, I will test this change and if nothing breaks it will be implemented in the next version.
