### ISSUE TITLE
Add support of default translation

### ISSUE THREAD

**Issue by jelen07** [orestbida/cookieconsent#112]
### Feature request
Add ability to load default translations the same way as loading custom styles. The implementation (resp. usage) of this widget could be done almost with zero configuration.

#### To consider
1. If this feature should be turned on by default or optionable.
2. Which consent types will be used as default (ie. the [Google's](https://developers.google.com/tag-platform/tag-manager/templates/consent-apis) - see _"content types"_)
3. Tone of default translation (**formal**, casual, ...)
4. Use GitHub PR for translation or some other service (ie. Crowdin)

### Proposed solution
There should be a public JSON with all available translations. Explicitly configured languages will be merged and overridden the defaults. Configuration of default consent types and their settings (`enabled`, `readonly`) should be configurable out of the `languages` key.

#### Links
- https://developers.google.com/tag-platform/tag-manager/templates/consent-apis

---
I can help with translations to czech, slovak, polish & deutsch.

**Comment by jelen07** [comment]
ATM we solve this via "wrapper" [`68publishers/cookie-consent`](https://github.com/68publishers/cookie-consent) that integrates `orestbida/cookieconsent`. All translations can be overriden via GTM tag settings.

<img width="863" alt="Snímek obrazovky 2021-12-21 v 8 57 10" src="https://user-images.githubusercontent.com/2346295/146892648-7ab556be-f85c-4437-bc07-d091e12b4aaa.png">

**Comment by orestbida** [comment]
For now I'm marking this as low-priority so that it doesn't get closed by the bot. I still don't know whether I want to have default configurations or not.

**Comment by orestbida** [comment]
Had quite a bit of time to think about this; I'd like to keep the current concept, no default translations/configurations! :/
