### ISSUE TITLE
Autodetect language based on HTML lang

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#114]
Current language autodetection (`auto_language`) [is based](https://github.com/orestbida/cookieconsent/blob/3837e6f5e110f326d9d43b07a3f7c8986b6e028b/src/cookieconsent.js#L966-L971) on `navigator.language`, which basically is language of the browser UI ([see MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language)).

However, this may not match the language in which users want to see the actual website (including the cookie banner). For example in a case when you explicitly choose a specific language version of the site, you just want the cookie banner translation to match the chosen page language. If user enters an English webpage, the page and cookie banner should both be in English. If the user clicks language switch to toggle the webpage to for example "Czech" version, as a user, I'd expect the cookie banner to be in Czech as well.

Current way to achieve this behavior it to manually disable `auto_language` and provide `current_lang`. However this includes an extra logic, necessity to dynamically modify the plugin configuration based on current language etc., while this could be simply automated.

The proposed solution is to simplify this by adding a new strategy of language autodetection - using value of the standard lang attribute `<html lang=...>`. This value could be accessed via `document.documentElement.lang`. [See MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/lang).

For example - possible values of `auto_language` could be:
- `auto_language: 'browser'` - current behavior of `true`, detect language from the browser
- `auto_language: 'html'` (or `'document`) - read the language from html lang
- `auto_language: 'false'` - disable autodetection
- `auto_language: 'true'` - kept for backward compatibility, same as `browser`

If you'd agree, I can prepare a pull request for this.

**Comment by orestbida** [comment]
Oh yea!

**Comment by OndraM** [comment]
Here is it: #115
