### ISSUE TITLE
Missing documentation of middle position behavior

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#116]
Hi,
~setting modal position to `middle center` has no effect and it behaves just like `bottom center`.~

EDIT: From #95 it seems position could only by middle when `force_consent` is enabled. However this is not documented in the readme nor in the demo.

Consider [`app.js`](https://github.com/orestbida/cookieconsent/blob/master/demo/app.js#L32) from the demo directory.

```js
    // ...
    gui_options: {
        consent_modal: {
            layout: 'box',                      // box,cloud,bar
            position: 'middle center',           // bottom,middle,top + left,right,center
            transition: 'slide'                 // zoom,slide
        },
        // ...
    }
```

**Current result:**
![image](https://user-images.githubusercontent.com/793041/143017895-18216140-9701-45ab-8b6d-c46b894dd314.png)

**Expected result:**
The box is vertically aligned.

Setting the position to `top center` works as expected.

**Comment by jelen07** [comment]
Duplicate #95

**Comment by OndraM** [comment]
Oh, true, I missed that, thanks!

So this should at least be documented, because now its imho nowhere in the readme. So I'm keeping this issue but will just rename it.

**Comment by orestbida** [comment]
This is a feature which has been requested a few more times (privately) and at this point I think it's better to just allow it and let the user choose if it fits well with their website layout or not.

I totally agree on the lacking documentation. In fact there are a few other options which are not mentioned at all.
