### ISSUE TITLE
The possibility to remove the console logs would be nice

### ISSUE THREAD

**Issue by parisiam** [orestbida/cookieconsent#12]
It would be great to have the possibility to remove the console logs (for production sites, for example).
As a suggestion, it could be possible to create a DEBUG variable which could be set to true to show the console logs and false not to show them.

**Comment by orestbida** [comment]
Hi, the console logs are available only on the [src version](https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js) (for developement purposes). If you need a more optimized version (recommended for production) then there's the [dist version](https://github.com/orestbida/cookieconsent/blob/master/dist/cookieconsent.js) which is not simply minified, but also stripped of the logs and processed through google's [closure compiler](https://github.com/google/closure-compiler). 

Before version 2, there was infact a property (boolean) called `cc_enable_verbose` used to enable/disable logs both on the dist and src version, though it was later on removed for the sake of having even more simplified and diverse versions (to better distinguish between src and dist).

**Comment by orestbida** [comment]
Closed due to inactivity. Feel free to re-open this issue if needed!
