### ISSUE TITLE
Custom configuration broken in 2.7.0-rc2

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#122]
Hi, unfortunately the fix in #120 did not work as expected.

What happes in the Closure compiler now, is the keys in the `_config` defaults are preserved (thanks to #120), however, name of the actual value which is used is still minified. Meaning the `_config` now contains

```
{ 
  cookie_expiration: 182,  // value from the default config value
  v: 365 // acutally used value
  // ...
}
```
... so in the end `getConfig()` returns value from the default configuration, not the actual used one.

[The way of fixing this](https://stackoverflow.com/a/7834912/464890) obviously requires accessing the config as an array arguments, for example:

```diff
if(typeof conf_params['cookie_expiration'] === "number")
-                _config.cookie_expiration = conf_params['cookie_expiration'];
+                _config['cookie_expiration'] = conf_params['cookie_expiration'];
```

and doing so on all places. This should force the Closure compiler to avoid renaming of the fields. However, I'm not sure whether this solution is preferred, there still may be edgecases and unexpected bugs.  There are two other options:

- Only use `SIMPLE_OPTIMIZATIONS` level in Closure compiler.
- Do not use Closure compiler at all, and use some other minifier.

What do you think, @orestbida?

**Comment by orestbida** [comment]
Yea, at this point it's better switching to something else, perhaps uglifyjs? I'd rather have a bit bigger filesize than a broken plugin.

**Comment by OndraM** [comment]
Agreed, also just for the record:

|||
|--|--|
| Original Size | 15.68KB gzipped (76.1KB uncompressed) |
| SIMPLE - Compiled Size | 6.59KB gzipped (18.2KB uncompressed) |
| ADVANCED  -Compiled Size| 6.46KB gzipped (17.24KB uncompressed) |

So the difference between SIMPLE and ADVANCED is quite minor, especially considering the gziped size.

**Comment by orestbida** [comment]
It's up, third time's a charm! Man, @tillsanders' gonna hate me for all these releases ...

**Comment by tillsanders** [comment]
@orestbida As a matter of fact, I love how much effort you put into this project ❤️
