### ISSUE TITLE
How to remove secondary_btn

### ISSUE THREAD

**Issue by ivent** [orestbida/cookieconsent#124]
Hello congratulations for the script, I'm using it for the lgdp law in brazil, here it is not mandatory to have the reject button just accept so I would like to know how I can remove the secondary_btn leaving only one accept button

**Comment by orestbida** [comment]
Hi @ivent,

currently the only way to hide it is via custom css. This is something which will be possible with the upcoming 2.7 version

**Comment by mrleblanc101** [comment]
I fail to see how to is possible
