### ISSUE TITLE
Two page views on Google Analytics on a single click

### ISSUE THREAD

**Issue by mraassin** [orestbida/cookieconsent#129]
Hello! 

Based on my quick tests, Google Universal Analytics' real-time reports seem to show two pageviews on a single page click after accepting cookies (both the page views per minute and per second). Shouldn't it be just one? 

However, it shows correctly just one active user. The tracking code is of form UA-XXXXXXXXX-Y, and I have added type="text/plain" data-cookiecategory="analytics" on my tracking scripts.

**Comment by orestbida** [comment]
HI @mraassin,

can you please provide your configuration?

**Comment by mraassin** [comment]
The version is v2.7.0-rc3, and my configuration is as in the example below. Both the cookieconsent.js and cookieconsent.css are in my web applications' external files (all.js and all.css, containing combined and minified Javascript and CSS styles). So, defining the CSS location in the theme_css attribute is not necessary, neither including the cookieconsent.js in the beginning.

<body>
    

    
    <script>
        window.addEventListener('load', function(){
            
            // obtain plugin
            var cc = initCookieConsent();

            // run plugin with your configuration
            cc.run({
                current_lang: 'en',
                autoclear_cookies: true,                   // default: false

                page_scripts: true,                        // default: false

                // delay: 0,                               // default: 0
                // auto_language: '',                      // default: null; could also be 'browser' or 'document'
                // autorun: true,                          // default: true
                // force_consent: false,                   // default: false
                // hide_from_bots: false,                  // default: false
                // remove_cookie_tables: false             // default: false
                // cookie_name: 'cc_cookie',               // default: 'cc_cookie'
                // cookie_expiration: 182,                 // default: 182 (days)
                // cookie_domain: location.hostname,       // default: current domain
                // cookie_path: '/',                       // default: root
                // cookie_same_site: 'Lax',                // default: 'Lax'
                // use_rfc_cookie: false,                  // default: false
                // revision: 0,                            // default: 0

                onAccept: function (cookie) {
                    // ...
                },

                onChange: function (cookie, changed_preferences) {
                    // ...
                },

                languages: {
                    'en': {
                        consent_modal: {
                            title: 'We use cookies!',
                            description: 'Hi, this website uses essential cookies to ensure its proper operation and tracking cookies to understand how you interact with it. The latter will be set only after consent. <button type="button" data-cc="c-settings" class="cc-link">Let me choose</button>',
                            primary_btn: {
                                text: 'Accept all',
                                role: 'accept_all'              // 'accept_selected' or 'accept_all'
                            },
                            secondary_btn: {
                                text: 'Reject all',
                                role: 'accept_necessary'        // 'settings' or 'accept_necessary'
                            }
                        },
                        settings_modal: {
                            title: 'Cookie preferences',
                            save_settings_btn: 'Save settings',
                            accept_all_btn: 'Accept all',
                            reject_all_btn: 'Reject all',
                            close_btn_label: 'Close',
                            cookie_table_headers: [
                                {col1: 'Name'},
                                {col2: 'Domain'},
                                {col3: 'Expiration'},
                                {col4: 'Description'}
                            ],
                            blocks: [
                                {
                                    title: 'Cookie usage 📢',
                                    description: 'I use cookies to ensure the basic functionalities of the website and to enhance your online experience. You can choose for each category to opt-in/out whenever you want. For more details relative to cookies and other sensitive data, please read the full <a href="#" class="cc-link">privacy policy</a>.'
                                }, {
                                    title: 'Strictly necessary cookies',
                                    description: 'These cookies are essential for the proper functioning of my website. Without these cookies, the website would not work properly',
                                    toggle: {
                                        value: 'necessary',
                                        enabled: true,
                                        readonly: true          // cookie categories with readonly=true are all treated as "necessary cookies"
                                    }
                                }, {
                                    title: 'Performance and Analytics cookies',
                                    description: 'These cookies allow the website to remember the choices you have made in the past',
                                    toggle: {
                                        value: 'analytics',     // your cookie category
                                        enabled: false,
                                        readonly: false
                                    },
                                    cookie_table: [             // list of all expected cookies
                                        {
                                            col1: '^_ga',       // match all cookies starting with "_ga"
                                            col2: 'google.com',
                                            col3: '2 years',
                                            col4: 'description ...',
                                            is_regex: true
                                        },
                                        {
                                            col1: '_gid',
                                            col2: 'google.com',
                                            col3: '1 day',
                                            col4: 'description ...',
                                        }
                                    ]
                                }, {
                                    title: 'Advertisement and Targeting cookies',
                                    description: 'These cookies collect information about how you use the website, which pages you visited and which links you clicked on. All of the data is anonymized and cannot be used to identify you',
                                    toggle: {
                                        value: 'targeting',
                                        enabled: false,
                                        readonly: false
                                    }
                                }, {
                                    title: 'More information',
                                    description: 'For any queries in relation to our policy on cookies and your choices, please <a class="cc-link" href="#yourcontactpage">contact us</a>.',
                                }
                            ]
                        }
                    }
                }
            });
        });
    </script>
<body>

And here is the Google Analytics tracking script:

```
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script type="text/plain" data-cookiecategory="analytics" async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
        <script type="text/plain" data-cookiecategory="analytics">
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-XXXXXXXXXX');
          gtag('config', 'UA-XXXXXXXXX-Y');

        </script>

```

**Comment by orestbida** [comment]
There's nothing wrong with the configuration. The issue is — _probably_ — caused by the following 2 lines:

```javascript
// ...
gtag('config', 'G-XXXXXXXXXX');
gtag('config', 'UA-XXXXXXXXX-Y');
// ...
```
as you are trying to initialize the `gtag` function 2 times. 

I'd recommend you to use only one of the methods, and to not mix them up:
-  [`gtag` configured with  the newer `GA4` (google analytics 4)](https://developers.google.com/analytics/devguides/collection/gtagjs)
- [google `UA` (universal analytics)](https://developers.google.com/analytics/devguides/collection/analyticsjs)

If you don't need/want gtag, here is the "[Google Universal Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs#alternative_async_tag)" only approach
```html
<!-- Google Analytics -->
<script type="text/plain" data-cookiecategory="analytics">
  window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
  ga('create', 'UA-XXXXX-Y', 'auto');
  ga('send', 'pageview');
</script>
<script type="text/plain" data-cookiecategory="analytics" async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->
```

**Comment by mraassin** [comment]
Hello @orestbida,

Thanks for your kind reply. It is highly appreciated.

According to the Google Developers guide (https://developers.google.com/tag-platform/gtagjs/install), you can add multiple products to an existing global site tag, so I guess that is not the root cause of the problem. Also, I wanted to send the data to both products (Google UA and GA-4), so I have to include multiple products in the initialization script.


```
<!-- Global site tag (gtag.js) - Floodlight -->
<script async src="https://www.googletagmanager.com/gtag/js?id=DC-ZZZZZZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'G-XXXXXX');
  gtag('config', 'AW-YYYYYY');
  gtag('config', 'DC-ZZZZZZ');
</script>
```

However, your solution works fine, so it fixed the issue. But still, there was something weird going on, so I investigated this issue a bit more. I found an interesting feature regarding how you include your script on your page. I have no clue why it works like this, but it is what it is.

If you do it like this, you get two page views per click:

`<script type="text/plain" data-cookiecategory="analytics" async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
`

But if you do it like this, you will get only one page view per click:

`<script type="text/plain" data-cookiecategory="analytics" async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXXX-Y"></script>`

So, depending on whether you have **?id=G-XXXXXXXXXX** or **?id=UA-XXXXXXXXX-Y** on your script import, you'll get a different outcome.

From my end, I guess this issue could be closed now as this workaround seems to work fine.

**Comment by orestbida** [comment]
Learned something new today! Glad you managed to fix it!
