### ISSUE TITLE
Blocking vimeo cookie (vuid) added by iframe embed

### ISSUE THREAD

**Issue by vikasneugi** [orestbida/cookieconsent#134]
Thanks for such a wonderful plugin.
The onIy cookie i couldn't restrict is the vimeo (vuid), which gets added by vimeo iframe embeds.
Is there any way we can do this?

**Comment by orestbida** [comment]
Hi @vikasneugi,

If you're loading the iframe directly then no, I can't help you. You can however use something like [iframemanager](https://github.com/orestbida/iframemanager) to entirely block iframes and load them only after consent. Check out the [demo](https://orestbida.com/demo-projects/iframemanager/demo1/).

**Comment by vikasneugi** [comment]
@orestbida Thanks for your quick response.
I will go through the [iframemanager](https://github.com/orestbida/iframemanager) plugin

**Comment by orestbida** [comment]
@vikasneugi ,

if you need help configuring iframemanager, feel free to create an issue there!
