### ISSUE TITLE
getUserPreferences not working properly without block title

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#136]
Hi, we just tried using `getUserPreferences()` added in 2.7.0, but it was returning an empty data, even after accepting all cookies:

```
Object { accept_type: "all", accepted_categories: [], rejected_categories: [] }
```

After digging into the source, it seems:

- `accepted_categories` get its value from `to_accept` variable https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L1778
- `to_accept` variable gets its value from `toggle_categories` https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L1750
- values of `toggle_categories` [are added](https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L589) only when given cookie category has its title https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L530

As we don't use settings modal, we use configuration like this:

```js
settings_modal: {
      blocks: [
        {
          // no title value here
          toggle: {
            value: 'necessary',
            enabled: true,
            readonly: true,
          },
        },
        {
          // no title value here as well
          toggle: {
            value: 'ad',
            enabled: false,
            readonly: false,
          },
        },
        // ...
    ]
}
```

... meaning our cookie categories don't have defined any title. As a result, `getUserPreferences()` does not work as expected.

While we can add some placeholder as the title, this is quite unexpected and I'd say wrong behavior - if such feature is based on so-far optional cookie level **title**, and depends on settings modal. From implementation perspective, this should be independent.

**Comment by orestbida** [comment]
I see, I'll release a minor version by tomorrow evening, ~perhaps sooner!
