### ISSUE TITLE
Inconsistent naming - category vs. level

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#144]
Hi, there seems to be confusing and inconsistent naming across the library and its documentation regarding consent `category` vs. `level`.

- The cookie itself contains `level` field
- There is `cookieconsent.get('level')` method
- `<script data-cookiecategory="">` uses on the other hand term `category` 
- The example configuration has examples like `my_category1`
- In the readme there are also mostly references to "cookie categories"
- The new method `getUserPreferences()` returns `accepted_categories` and `rejected_categories` - ie. not levels.

So what should be used? Shouldn't this be also unified?

**Comment by orestbida** [comment]
Yes, should be `categories` instead of `level`!
