### ISSUE TITLE
Cookie_table undefined values

### ISSUE THREAD

**Issue by cerv0077** [orestbida/cookieconsent#151]
Hi,

I have two issues. First is with cookie table. I get undefined cookie. You can see bellow and I dont know why. I think the second problem could be related to that. Am i wrong?

<img width="668" alt="Snímek obrazovky 2021-12-15 v 15 03 42" src="https://user-images.githubusercontent.com/14922022/146201448-324613ba-f667-4ab1-bd63-515941a8f167.png">

The second problem is that when is fired the auto_clear script, it deletes some undefined cookies and eventually deletes them all.

<img width="1020" alt="Snímek obrazovky 2021-12-15 v 15 05 11" src="https://user-images.githubusercontent.com/14922022/146201145-deb7b053-d80c-4784-b350-ec2372dcb7bc.png">

My config:
`{
        autorun: true,
        auto_language: 'document',
        //theme_css: '<path-to-cookieconsent.css>',
        autoclear_cookies: true,
        page_scripts: true,
        cookie_domain: window.location.hostname,
        cookie_path : window.location.pathname,
        revision: -1,

        gui_options: {
            consent_modal: {
                layout: 'box',               // box/cloud/bar
                position: 'bottom right',     // bottom/middle/top + left/right/center
                transition: 'zoom',            // zoom/slide
                swap_buttons: false            // enable to invert buttons
            },
            settings_modal: {
                layout: 'box',                 // box/bar
                // position: 'left',           // left/right
                transition: 'zoom'            // zoom/slide
            }
        },

        onFirstAction: function(user_preferences, cookie){
            // callback triggered only once
        },

        onAccept: function (cookie) {
            // ... cookieconsent accepted
        },

        onChange: function (cookie, changed_preferences) {
            // ... cookieconsent preferences were changed
        },

        languages: {
            cs: {
                consent_modal: {
                    title: 'We are using cookie!',
                    description: 'lorem lorem<button type="button" data-cc="c-settings" class="cc-link">Edit my settings</button>',
                    primary_btn: {
                        text: 'Accept All',
                        role: 'accept_all'              // 'accept_selected' or 'accept_all'
                    },
                    secondary_btn: {
                        text: 'Reject All',
                        role: 'accept_necessary'                // 'settings' or 'accept_necessary'
                    }
                },
                settings_modal: {
                    title: 'Cookie settings',
                    save_settings_btn: 'Save Settings',
                    accept_all_btn: 'Accept all',
                    reject_all_btn: 'Reject all',       // optional, [v.2.5.0 +]
                    cookie_table_headers: [
                        {col1: 'Name'},
                        {col2: 'Domain'},
                        {col3: 'Expiration'},
                        {col4: 'Description'},
                        {col5: 'Type'}
                    ],
                    blocks: [
                        {
                            title: 'Cookie usage',
                            description: 'I use cookies to ensure the basic functionalities of the website and to enhance your online experience. You can choose for each category to opt-in/out whenever you want.'
                        }, {
                            title: 'Strictly necessary cookies',
                            description: 'These cookies are essential for the proper functioning of my website. Without these cookies, the website would not work properly.',
                            toggle: {
                                value: 'necessary',
                                enabled: true,
                                readonly: true
                            }
                        }, {
                            title: 'Analytics cookies',
                            description: 'These cookies collect information about how you use the website, which pages you visited and which links you clicked on. All of the data is anonymized and cannot be used to identify you.',
                            toggle: {
                                value: 'analytics',
                                enabled: false,
                                readonly: false,
                            },
                            cookie_table: [
                                {
                                    col1: '^_ga',
                                    col2: 'localhost',
                                    col3: '2 years',
                                    col4: 'description ...',
                                    col5: 'Permanent cookie',
                                    is_regex: true
                                },
                                {
                                    col1: '_gid',
                                    col2: 'localhost',
                                    col3: '1 day',
                                    col4: 'description ...',
                                    col5: 'Permanent cookie'
                                }
                            ]
                        },
                        {
                            title: 'More information',
                            description: 'For any queries in relation to my policy on cookies and your choices, please <a class="cc-link" href="#yourwebsite">contact me</a>.',
                        }
                    ]
                }
            }
        }
    });`

and in head i have this:

```
<script>
    // Define dataLayer and the gtag function.
    window.dataLayer = window.dataLayer || [];
    function gtag() {
	    dataLayer.push(arguments);
    }
    
    // Default ad_storage to 'denied'.
    gtag('consent', 'default', {
	    'ad_storage': 'denied',
	    'analytics_storage': 'denied'
    });
</script>
<script>
    (function (w, d, s, l, i) {
	    w[l] = w[l] || [];
	    w[l].push({
		    'gtm.start':
				    new Date().getTime(), event: 'gtm.js'
	    });
	    var f = d.getElementsByTagName(s)[0],
			    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
	    j.async = true;
	    j.src =
			    'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
	    f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-XXXX');
</script>
<script type="text/plain" data-cookiecategory="analytics">gtag('consent', 'update', {'analytics_storage': 'granted'});</script>
<script type="text/plain" data-cookiecategory="ads">gtag('consent', 'update', {'ad_storage': 'granted'});</script>

```

**Comment by orestbida** [comment]
Hi @cerv0077,

I copy-pasted your configuration and but I found no issue. Perhaps there is something else causing this wrong behaviour?
