### ISSUE TITLE
Problem with scripts containing document.write()

### ISSUE THREAD

**Issue by N4thyra** [orestbida/cookieconsent#154]
### Problem
if one of your scripts contains `document.write()` e.g. old versions of GA, once the plugin has executed the "sleeping" script, the whole page will disappear and you will see a blank page.  

### Explanation
document.write() is used to write to the document stream.

Calling document.write() on a closed document stream automatically calls document.open(), which will clear the document. 

More info on [StackOverflow](https://stackoverflow.com/questions/10873942/document-write-clears-page)

### Solutions in other libraries

- CookieBot overwrites document.write with their own function called [writeOverride](https://consent.cookiebot.com/uc.js) in its scope
- GTM utilises a library called [postscribe](https://github.com/krux/postscribe)

### Possible solution

// Adding import at the very beginning of CookieConsent

`import postscribe from './postscribe.min'`

// Creating two helper functions inside CookieConsent function
```
  /**
   * Save native document.write function for later use
   */
  var _nativeWrite = document.write;

  /**
   * Enhanced document.write function
   * @param {String} html
   */
  var _enhancedWrite = function (html) {
      var element = document.createElement("div");
      element.style.display = "none";
      element.style.visibility = "hidden";
      document.body.appendChild(element);
      postscribe(element, html, {
          done: function() {
              document.write = _nativeWrite;
          }
      });
  }
```

// Adding `document.write = _enhancedWrite; ` before `curr_script.parentNode.replaceChild(fresh_script, curr_script);`
```
// Replace current "sleeping" script with the new "revived" one
document.write = _enhancedWrite;
curr_script.parentNode.replaceChild(fresh_script, curr_script);
```

**Comment by orestbida** [comment]
Hi @N4thyra, 

I appreciate the detailed explanation + solution!

I understand that it's something which is a must-have for your configuration to work — but — this is also quite a niche feature and for many would be a significant chunk of "dead-weight" (or at least for me).

If there was a simpler/shorter way (relatively little code) to achieve this, then I'd consider adding this feature as a "plugin" once v3 releases.

**Comment by N4thyra** [comment]
Hey @orestbida,

Thanks for the reply! I agree that this might be an overkill for many.

Not only is it discouraged to use document.write but e.g. old GA using it should've already been replaced as it's deprecated.

I'm working on a platform that will detect and auto-assign categories to each script, and it's likely that I will need to keep this feature.

**Comment by orestbida** [comment]
I'd like to leave this issue open. I'll see what I can do only after the v3 release.
