### ISSUE TITLE
Place accept_necessary button in consent_modal.description

### ISSUE THREAD

**Issue by Mangatt** [orestbida/cookieconsent#156]
Is it possible to place `accept_necessary` button in `consent_modal.description`? Since `settings` can be secondary button, user should be able to reject all in first step.

**Comment by orestbida** [comment]
Hi @Mangatt,

this is not possible without custom code and I do not plan on adding a specific option to change buttons' parent container.

I could — however — add some special _"hooks"_:

`data-cc="accept-all"`, `data-cc="accept-necessary"` and `data-cc="accept-selection"` which would allow to easily connect any link/button to the api calls:

```html
<button type="button" data-cc="accept-necesary"> Accept necessary only </button>
```
You would then be able to use this button anywhere, even inside the description modal.

**Comment by Mangatt** [comment]
@orestbida That was my thought as well, that would be most flexible and ideal solution.

Thank you
