### ISSUE TITLE
Add trigger via URL

### ISSUE THREAD

**Issue by jelen07** [orestbida/cookieconsent#158]
### Feature request
Add the ability to show settings modal via URL like `https://www.example.com/#cookie-settings`. Whenever is the anchor tag present on the page. Consider implementation, when the anchor tag is added via GTM etc.

**Comment by orestbida** [comment]
Just like #111, I think this falls in the cool/very optional feature group. Not saying no, but will have to wait until v3 comes out with a "plugin" system.
