### ISSUE TITLE
Color management - idea

### ISSUE THREAD

**Issue by DanielMiara** [orestbida/cookieconsent#16]
Hi,

Thank you for the script. You did great gob! 👍 
Will be awesome add some color management to the section below, such as

auto_language : true,
buttons : #CCCC,
swich_on : #CCCC,
swich_off: #00000,
...
cookie_expiration : 365..

Thanks Again

**Comment by orestbida** [comment]
@DanielMiara yea, as of now the only way to personalize the plugin is by overriding the style via those crazy css classes. 

The **first option is to go the javascript way** (like you suggested), but then users would surely ask to add other features like the ability to define color schemes for both light and dark modes, and mabye additional other properties like button_hover_bg_color, focus_border ... 

**The other route would be to make the existing css more** **"ready-to-edit"** (maybe by specyfing css variables at the beginning of the .css stylesheet for an easier/immediate management. Something like:

```css
/* Light color-scheme */
--buttons-bg: red;
--buttons-bg-hover: brown;
/*other props ... */

/* Dark color-scheme */
--buttons-bg-dark: white;
--buttons-bg-hover-dark: grey;
/* other props ... */

/** Rest of css style **/
```

The css solution would be easier to maintain/update (from my point of view at least) but in constrast. For the old browsers which dont support css variables (IE ...), you would have to either include a polyfill or leave it like that (the default dark-blue style would be applied). 

All that being said, surely one of the 2 methods will be implemented in the future!

**Comment by DanielMiara** [comment]
Any options to manage the colors will be helpful but now I think the second one will work better :)

BTW: Maybe you can find a better option than force--consent now to force a full screen.
I mean **force--consent** works good but it's difficult sometimes to get and modify **HTML** tag.
If we can use just **<div class="force--consent"** somewhere will be more helpful 

Thanks

**Comment by orestbida** [comment]
Shouldn't be an issue. 

In the upcoming 2.3 release I'll change it so whoever the element with class="force--consent" is (as long as it is a parent container) the css will still apply.

**Comment by DanielMiara** [comment]
Superb, thanks
