### ISSUE TITLE
is there any way to set up NONCE attribute for CSP ?

### ISSUE THREAD

**Issue by luchianenco** [orestbida/cookieconsent#162]
```
 if (cookieconsent.allowedCategory('analytics')) {
     cookieconsent.loadScript('https://www.googletagmanager.com/gtag/js?id=XXX', function() {
                            window.dataLayer = window.dataLayer || [];
                            function gtag(){dataLayer.push(arguments);}
                            gtag('js', new Date());
                            gtag('config', 'XXXX');
                        });
    }
}
```
I have the above script but loadScript function does not allows to set up nonce attribute when you have CPS strict-dynamic. Is there any way to set it up ? thanks

**Comment by orestbida** [comment]
Hi @luchianenco,

you can attach any attribute via the `.loadScript()` method:

```javascript
cookieconsent.loadScript('path-to-script.js', function(){
    // Script loaded, do something
}, [
    {name: 'nonce', value: 'nonce-value'}
]);
```

Alternatively you can load scripts using the [recommended way](https://github.com/orestbida/cookieconsent#how-to-blockmanage-scripts):
```html
<script type="text/plain" data-cookiecategory="analytics" src="path-to-script.js" nonce="nonce-value"></script>
```

**Comment by luchianenco** [comment]
```
<script nonce="random-csp-nonce">
                (function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:000000,hjsv:6};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;r.nonce="random-csp-nonce";
                r.setAttribute('data-cookiecategory', 'analytics')
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
                })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
            </script>
```
if I will add attribute data-cookiecategory dynamically - will it work or I should do as it the first approach?

**Comment by orestbida** [comment]
The plugin doesn't have any active listeners so It would not be aware of the new script. If you were to add the `data-cookiecategory` later (after the plugin's), you'd also need to manually call the `.updateScripts()` method to let the plugin know that there are some new script blocks to manage.

I would highly recommend that you use the recommended way by setting `type="text/plain"` (this is what disables the current script block) and `data-cookiecategory="some-category"`
