### ISSUE TITLE
Auto 3rd party cookie blocking?

### ISSUE THREAD

**Issue by HerissonMan-TMP** [orestbida/cookieconsent#17]
Hello,

Would it be possible to add a support for blocking third party cookies for <script> and <iframe> tags ?

**Comment by orestbida** [comment]
@HerissonMan-TMP hi, unfortunately i do not plan on adding this feature (surely not in the near future). You could check out [klaro](https://github.com/kiprotect/klaro) as it gives you more control on your scripts.

**Comment by HerissonMan-TMP** [comment]
Hello,

After all my researchs, I don't even know how I didn't find the repository you mentioned before 😄

Thanks a lot
