### ISSUE TITLE
Feature removal

### ISSUE THREAD

**Issue by orestbida** [orestbida/cookieconsent#182]
I plan on removing the following options/features:

`theme_css` (option)
- initially added as an attempt to optimize css loading (deferred)
- issue: it works but it's not perfect. Sometimes css will load/apply just a few milliseconds after the plugin has initialized, causing a similar effect to FOUC — although very small.
<br>

`page_scripts_order` (undocumented option)
- allows to load page scripts in an unordered way (performance optimizations)
- issue: useless, unless we're talking about hundreds+ scripts in one page ...
<br>

`.set('revision')` (api)
- added as an attempt to make revision management easier (check #75)
- issue: not very intuitive; It'd be easier to simply change the revision number by directly manipulating the cookie

**Comment by MartinMystikJonas** [comment]
I would like to keep theme_css option . What about some minimal ( 50ms?) delay between adding of CSS link and display of consent applied when this option is used?

**Comment by MartinMystikJonas** [comment]
Maybe just change 0 to 50 here?

https://github.com/orestbida/cookieconsent/blob/1f20f3716d390ce03af30dced1b847b294499b56/src/cookieconsent.js#L1493

**Comment by OndraM** [comment]
I'm all in for removing `theme_css`. It is redundant and does not in my opinion provide any benefit over using `<link rel="stylesheet">`. It just adds confusion and makes loading styles not transparent, it is also quite unusual for a component like this to load its external CSS file themselves.

Also when you install the package using npm and pack the styles in your stylesheet, you must unexpectedly disable theme_css, which causes another confusion.

**Comment by orestbida** [comment]
Yes, I've seen too many wrong implementations of the plugin where users are loading the style twice, using both a `link` tag and `theme_css` option. 

The same deferred style loading — that `theme_css` offers — can be achieved using something like [this](https://stackoverflow.com/questions/32759272/how-to-load-css-asynchronously):
```html
<link rel="stylesheet" href="<path-to-css>" media="print" onload="this.media='all'">
```

**Comment by MartinMystikJonas** [comment]
theme_css loads CSS even if consent is not shown same as this lazy load example? I thought it loads CSS only when consent is shown. It it is load always but just lazy then I agree thet this feature is not needed.

Maybe add onShow handler to allow to implement similar only when shown logic?

**Comment by orestbida** [comment]
@MartinMystikJonas,

yes, adding an `onShow` handler is perfectly fine for me!
