### ISSUE TITLE
Reject All Link like c-settings  

### ISSUE THREAD

**Issue by pitr82** [orestbida/cookieconsent#186]
Hi, 
I would like add **link to reject all** into description section. 
Can you add function like **data-cc="c-reject-all"**. For generate this link. 

Thankx

**Comment by orestbida** [comment]
Hi @pitr82,

this was implemented in #170 and will be included in the v2.8 release. You can use any link/button with the following attribute `data-cc="accept-necessary"`

The new data-cc values have yet to be documented

**Comment by pitr82** [comment]
Hi @orestbida ,
thanks for great news.
