### ISSUE TITLE
Optional configurable close icon (button) on consent dialogs

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#187]
Just saw this, and I think it is a great idea especially for multilingual websites. It is impossible to add all languages, so choosing the right button can be difficult if the displayed text is in a different language than the visitor's native language. If used with force consent it could result in a simple bounce from the site.

I can imagine it could be configured to accept-all or reject-all based on the setting.
Also as an extra it could appear only if the browser accepted language is not supported by the dialog (so if there is no definition for that language).

**Comment by orestbida** [comment]
Yes, a close button can be added!

With that being said, it is still advisable to translate the button's `aria-label` in your configured languages — for accessibility reasons (used by screen readers).

**Comment by orestbida** [comment]
In v3 you can now manually configure a close button-icon, which will be treated as "accept necessary only" only.
