### ISSUE TITLE
Integrate iframe manager in cookie

### ISSUE THREAD

**Issue by tecnoweb** [orestbida/cookieconsent#188]
Hello,
I can't understand how to integrate in the same action  the iframemanager to block video 
thanks
Davide

**Comment by orestbida** [comment]
Hi @tecnoweb,

the most basic/easy way to configure them together is as follows:

1. Load iframemanager and cookieconsent
2. Configure and run iframemanager
3. Configure and run cookieconsent

For the sake of this example, I'm assuming that all iframes fall under the `analytics` category. Load all needed scripts:
```html
<script src="iframemanager.js" defer></script>
<script src="cookieconsent.js" defer></script>
<script src="cookieconsent-init.js" defer></script>
```

Configure and run plugins Inside `cookieconsent-init.js`:
```javascript
const iframemanager = iframemanager();
const cookieconsent = initCookieConsent();

iframemanager.run({
    // your configuration ...
});

cookieconsent.run({
    // your configuration ...

    onAccept: function(){
        if(cookieconsent.allowedCategory('analytics'))
            iframemanager.acceptService('all');
    },
    
    onChange: function(){
        if(!cookieconsent.allowedCategory('analytics'))
            iframemanager.rejectService('all');
    },

    // ...
});
```

**Comment by LanmanGroup** [comment]
Hi @orestbida, 
I did the same thing but with iframemanager **v1.1** beceause with the **v1.0** when you change your cookie preference from accepted to denied, the iframes in the web page are reloaded: they are destroyed but when you scroll they are recreated.
I also added an option to iframemanager to remove the button `loadBtn` and  `loadAllBtn`, so you can only control your preference by cookieconsent (if you want i send you my code..)

**Comment by tecnoweb** [comment]
can you share @LanmanGroup

**Comment by LanmanGroup** [comment]
Here https://github.com/LanmanGroup/iframemanager/blob/v1.1/src/iframemanager.js you can find my new option
