### ISSUE TITLE
How to change plugin position

### ISSUE THREAD

**Issue by franm3e** [orestbida/cookieconsent#19]
I think it could be interesting for the developer to be able to change the modal position (top, top-right-left, bottom-right-left, etc..). Maybe it is already posible to do it, but i could not find it.

Thank you.

Regards.

**Comment by orestbida** [comment]
@franm3e this is the main "sore point" of the cookieconsent as of now. In fact there is currently NO option to choose a **layout** or/and **anchor position** . This will be the focus with next future update.

I will surely add some basic layout options for the small consent modal (exactly what you mentioned), and at least 2 layout options for the settings/preferences modal (thinking about "centered_box" - that is, the current one - and "vertical_bar" (narrow or wide) which can be positioned either on the left or right side of the page)

These options would be available as a new property available on the javascript side:
```javascript
cookieconsent.run({
  ...
   gui_options: {
      consent_modal: {
         layout : "box",
         position : "top left"  
      },
      settings_modal : {
         layout : "vertical_bar",
         position : "left" 
      }
   },
...
}
```

With that being said, unfortunately the update will have to wait a few weeks as I'm a bit busy currently. But if you still want to change the **position** of the consent modal yourself, you can do so easily with a few lines of css:

Example top-left

```css
#cc_div #cm {
    top: 1.25em;
    left: 1.25em;
   
     /* unset the other 2 positions */
    bottom: unset;  
    right: unset;
}
```

The same logic would apply for the other 3 positions. As for the settings modal, well ... thats a bit more complicated!
