### ISSUE TITLE
Event handlers are not re-attached to data-cc elements after changing language

### ISSUE THREAD

**Issue by alex-ketch** [orestbida/cookieconsent#193]
Hi, and thanks for this library 💖

In testing the new `updateLanguage` methods added in v2.8.0 I noticed that strings using custom `data-cc` attributes don't have their click handlers attached.

The specific use case I had was for the `consent_modal.description` text where I have a button with `data-cc="c-settings"` ([same as the demo app](https://github.com/orestbida/cookieconsent/blob/1f20f3716d390ce03af30dced1b847b294499b56/demo/app.js#L79)).
This button stops functioning and does not open the settings modal after calling the `updateLanguage` method.

Is it safe to call [`_addDataButtonListeners`](https://github.com/orestbida/cookieconsent/blob/1f20f3716d390ce03af30dced1b847b294499b56/src/cookieconsent.js#L247) after the language change, or do we need to keep track of already hydrated elements to prevent duplicate event listeners?

I can provide a PR, but will probably not be in time for the v2.8 release tag.

Thanks again!

**Comment by orestbida** [comment]
Hi @alex-ketch,

thanks for letting me know! Will fix this asap.
