### ISSUE TITLE
Adding buttons to accept on a component if the cookie category is not (yet) accepted

### ISSUE THREAD

**Issue by melker** [orestbida/cookieconsent#195]
(This is more a question of best practice on how to do something, and twitter is just an example.)

Lets say I want to add a twitter flow on a page and let the visitor accept/not accept content and cookies from twitter.

I add
```
<a class="twitter-timeline" data-tweet-limit=5 href="someTwitterUrlHere"></a>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8" data-cookiecategory="twitter" type="text/plain"></script>
```
It gets displayed if the user has accepted (or when enabling) the category "twitter". Fine.

**Problem**
If the user has not accepted the category I want to show some text (preferably reuse some text from the cc settings?) and buttons (accept this, accept all from twitter) on the location of where the twitter flow would have been.

What is the best/some good way to achieve this?

**My current attempt**
NOTE: This uses jquery and is a piece of code that is run after cc has been loaded and "this" is a container around the html-code above.
```
		var self = this;
		this.$el = $(element);

		if (!cc.allowedCategory('twitter')) {
			var newDiv = $('<div>' +
				'<p>A twitter feed will be displayed here if you allow that. Twitter will set cookies.</p>' +
				'<button class="allowall">Always allow twitter feeds</button></div>');
			newDiv.find('.allowall').on('click', function (e) {
				e.stopPropagation();
				e.preventDefault();
				cc.accept('twitter'); // This will trigger the js to be activated
				newDiv.remove(); // Hide button and disclaimer
			});

			this.$el.append(newDiv);
              }
```

PS I am currently implementing a solution for us based on this library. That you for making it!

**Comment by melker** [comment]
A second question, based on my comment to reuse texts.
cc.getConfig('current_lang');
lets me read a config value. 
But if I have the category and want to read the name and description of a category in the currently active language? (something also defined in config). Is that possible, and if so, how?

(sorry for adding multiple things in in the same issue, just tell me and I can make another one)

**Comment by orestbida** [comment]
Hi @melker,

I think this task should be entrusted to [iframemanager](https://github.com/orestbida/iframemanager), since you're trying to load an iframe. Unfortunately, the plugin is still in its very-first release and doesn't support yet “custom iframes” generated by such as:
 ```html
<a class="twitter-timeline" data-tweet-limit=5 href="someTwitterUrlHere"></a>
```
This aspect will improve in [v1.1](https://github.com/orestbida/iframemanager/tree/v1.1) (work-in-progress).

`.getConfig()` returns only configuration options which are stored in the internal `_config` variable, and you won't be able to retrieve the `languages` object or any of the callbacks. This can be easily changed though!

**Comment by orestbida** [comment]
As of v2.8, `.getConfig()` will now search on the input config. too:
https://github.com/orestbida/cookieconsent/blob/7bb43cf12bfcb3598fd9451744c55af2c6b6db58/src/cookieconsent.js#L1793-L1795

**Comment by melker** [comment]
Thanks for replies @orestbida

About the iframe - ok, I might add some issue on iframemanager, (but currently we are not using that as we want some other initial behavior, I might add a feature request for that too.)

Reading config, works good!

**Comment by melker** [comment]
Just a side note:
Perfect: I also realized that I may add a few extra strings elements in the config to use in the blocks on the pages (for my approval buttons there)
