### ISSUE TITLE
Allow html inside buttons 

### ISSUE THREAD

**Issue by thomasschadron** [orestbida/cookieconsent#206]
Hello, how do you provide a line break in the button text of the consent_modal? I tried /n but no luck.

![add_linebreak](https://user-images.githubusercontent.com/95974052/149989879-832ede4c-9f07-41f4-bb38-f601aeb7b88e.png)

**Comment by orestbida** [comment]
Hi @thomasschadron,

currently buttons don't allow html markup (simply because I didn't think it would be useful). I'll add this to the v3 milestone.

**Comment by thomasschadron** [comment]
👍 
thank you for being so committed to this project.
