### ISSUE TITLE
Add support for bulk consent

### ISSUE THREAD

**Issue by orestbida** [orestbida/cookieconsent#213]
See [bulk consent for multiple domains](https://www.cookieinfo.net/en/knowledge-base/bulk-consent-for-multiple-websites-or-subdomainsconsent-for-multiple-websites-or-subdomains/#:~:text=If%20you%20operate%20multiple%20websites,this%20as%20a%20Bulk%20Consent.).

**Comment by n3t** [comment]
Not sure if this could work without some server-side application. It Would mean to set cookie for multiple domains. CookieBot in this case is IMHO using cookie set to their domain, so all sites using their script could load it. 

I solved this using code like this
```
        _config.cookie_domains.forEach(function(value) {
          let image = document.createElement('img');
          image.src = value + '&val=' + _getCookieValue(_config.cookie_name);
          image.style = "display:none";
          document.getElementsByTagName("body")[0].appendChild(image);
        });
```
So it calls PHP script from any other domain listed in _config.cookie_domains, which set the cookie for that domain (just copy value of current cc cookie). Note, that it works just if cookie has samesite=None attribute. But this requires server side PHP script.

**Comment by orestbida** [comment]
This can be implemented entirely on the client-side, using `localstorage`, since the data here — unlike cookies — will persist across multiple websites.

For example, if the following conditions are met:

1. cookie is not set in the current domain
2. bulk consent is activated (array of domains)
3. there's an item saved in `localstorage` (valid cc_cookie content)

=> don't ask for consent.

based on [Cookiebot](https://support.cookiebot.com/hc/en-us/articles/360003792573-Share-consent-across-multiple-domains#h_01FHYYNCTCWZRRFJYTD6AKBC5E):

```
In order for the Bulk Consent to function properly, these following three conditions must be met:

The user allows third party local storage in their browser settings
The user has not activated “Do Not Track (DNT)” in their browser settings
The user accepts all cookies, or as a minimum, cookies in the 'Preferences' category when the user submits their consent preferences
```

**Comment by n3t** [comment]
Ok, you are right, I missed local storage :) In my case however I need the coookie value also on server, so local storage is not the way.

**Comment by orestbida** [comment]
This feature requires too much code (for my taste) + raises many small issues; It won't be implemented
