### ISSUE TITLE
CSS color for hovered button

### ISSUE THREAD

**Issue by n3t** [orestbida/cookieconsent#214]
Hi, 

default CSS contains definition for all elements in Cookie Consent div
```
.cc_div *, .cc_div :after, .cc_div :before {...}
```
however it doesn't cover some states, like hover, so if template of website contains code like this
```
button:hover {
    color: #fff;
}
```
block headers has white color on mouse hover.

This change helped:
```
.cc_div *, .cc_div *:hover, .cc_div :after, .cc_div :before {...}
```

**Comment by orestbida** [comment]
Nice catch!
