### ISSUE TITLE
Add ability to show the consent modal

### ISSUE THREAD

**Issue by jelen07** [orestbida/cookieconsent#215]
### Feature request
Add ability to show the `consent modal`.

#### Why
We're working on the https://github.com/68publishers/cookie-consent/issues/36 feature and atm there is no way how to show the `consent modal` just `settings modal` which could be confusing for some users.

**Comment by orestbida** [comment]
Does adding a second parameter  `create_modal` to the `.show(<delay:number>, <create_modal:boolean>)` method fix this?

If the second parameter is set to `true` => generate modal if it doesn't exist

**Comment by jelen07** [comment]
Yeah, seems fine to me 😉
