### ISSUE TITLE
swap_buttons option also for settings dialog

### ISSUE THREAD

**Issue by n3t** [orestbida/cookieconsent#218]
Hi, would be nice to have swap_buttons option also for settings dialog. 
Mainly on mobile layout this looks strange, as on consent dialog Accept all is at the bottom, and after clicking Settings, it goes to top.
![swap-buttons-mobile](https://user-images.githubusercontent.com/979699/150644416-6cca44c4-af2c-4cbf-867d-d4cb3e59d282.gif)

Thanks for consideration.

**Comment by orestbida** [comment]
Implemented in #288
