### ISSUE TITLE
Block Google maps api

### ISSUE THREAD

**Issue by gfmodica** [orestbida/cookieconsent#223]
HI,
i try to block script for call google maps api, but dont'work. Chrome console report that "Uncaught ReferenceError: google is not defined" when try to render map
-----------
I have tried two methods:
1)
 <script type="text/plain" data-cookiecategory="funzionalita">
                cc.loadScript('https://maps.googleapis.com/maps/api/js?key=MyKey', function(){
            // Script loaded, do something
        });
    </script>
2)
 <script type="text/plain" data-cookiecategory="funzionalita" src='https://maps.googleapis.com/maps/api/js?key=MyKey'></script>

Thanks!

**Comment by orestbida** [comment]
Hi @gfmodica,

after loading the maps api:
```html
<script type="text/plain" data-cookiecategory="funzionalita" src='https://maps.googleapis.com/maps/api/js?key=MyKey'></script>
```

you also need to put the configuration/initialization of the iframes under the same category, otherwise the code will run before the maps api is loaded!

So, something like this should fix your issue:
```html
<script type="text/plain" data-cookiecategory="funzionalita">
  // Initialize and add the map
  // The location of Uluru
  const uluru = { lat: -25.344, lng: 131.036 };
  // The map, centered at Uluru
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 4,
    center: uluru,
  });
</script>
```

The above example code was taken from the [official doc.](https://developers.google.com/maps/documentation/javascript/adding-a-google-map#maps_add_map-javascript)

**Comment by orestbida** [comment]
Yes, adding  `type="text/plain" data-cookiecategory="funzionalita"` to the external script should fix it!

**Comment by gfmodica** [comment]
Dont Work...
my complete script is:

------------
 <script type="text/plain" data-cookiecategory="funzionalita" src="https://maps.googleapis.com/maps/api/js?key=MYKEY&callback=initMap&libraries=&v=weekly" defer></script>
    <script type="text/plain" data-cookiecategory="funzionalita">
        // Initialize and add the map
        function initMap() {
            // The location of Uluru
            // The map, centered at Uluru
            const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 8,
                center: { lat: 111111111, lng: 2222222 },
                streetViewControl: false,
                styles: [
                    {
                        "featureType": "administrative.neighborhood",
                        "elementType": "labels.text",
                        "stylers": [
                            {
                                "color": "#6a1ddd"
                            },
                            {
                                "weight": 0.5
                            }
                        ]
                    },
                    {
                        "featureType": "poi.attraction",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.business",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.government",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.medical",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.place_of_worship",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.school",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    }
                ]

            });
          

           etc..........
.................
..........        

    </script>

**Comment by orestbida** [comment]
I think there is a misconfiguration on your part;

- are you able to view the map without cookieconsent?
- are there any errors/warnings in the browse's console? 
- have you set a specific height/width to the element which will contain the map?

I created a [demo](https://codesandbox.io/s/cookieconsent-demo-config-j135o?file=/index.html) with google maps working just fine.

**Comment by gfmodica** [comment]
- yes without cookiesconsent work
- error is google is not defined
- now i try to adapt your demo
