### ISSUE TITLE
Callbacks when one of the modals is shown/closed or option to hide first modal when settings are opened

### ISSUE THREAD

**Issue by alexanderadam** [orestbida/cookieconsent#226]
First of all: thank you so much for cookieconsent! 🙌 

Now, I would love to hide the main modal while the settings modal is open.
Is this achievable right now?
If not: would it be possible to add this as an option (i.e. `hideMainModalWhenSettingsShown: true`) or to add some callbacks (i.e. `onSettingsShown`, `onSettingsHidden`, `onMainShown` and `onMainHidden`) to achieve this?

**Comment by orestbida** [comment]
Hi @alexanderadam,

as of now the only way to achieve this would be with some custom code, perhaps using a `MutationObserver` to check if the `html` element's className contains `show--consent` and `show--settings`. #70 might help you out.

**Comment by orestbida** [comment]
A very simple solution would be to just use css:

```css
.show--consent.show--settings #cc_div #cm {
    opacity: 0!important;
    visibility: hidden!important;
}
