### ISSUE TITLE
Strange behaviour in Firefox

### ISSUE THREAD

**Issue by blondak** [orestbida/cookieconsent#227]
I setup this great script to one web and i get into troubles, I have cookie PHPSESSID which is set as HttpOnly. But in firefox sometimes this value is overwrited (only in firefox), when i call 
```
var cc = initCookieConsent();
```
it sometimes leads to change value of cookie (dumping out PHPSESSID on server side value vs, but in developer bar is random value)

Does anyone have the same problem?

**Comment by orestbida** [comment]
@blondak,

you can't access an `httpOnly` cookie via javascript so I don't see how the plugin can be the culprit. 

I tried setting up a local web server with xampp (php 8.1) and session cookie set as `httpOnly` but I can't reproduce this issue (using latest version of firefox).

**Comment by blondak** [comment]
I know, that's the reason, why I'm asking here, if someone facing same (or similar) problem. I have no idea how it happens. I will try make minimal "defective" environment.

**Comment by blondak** [comment]
I looks, that issue happens only with HTTP/2 push,...
