### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by Anxium** [orestbida/cookieconsent#232]
Hi guys,

I came across your library a few days ago, and it is awesome, big thanks!

I'm using it in React with TypeScript, and my colleague and I have created our own typescript type (especially for what we are using inside it), because we wasn't able to find an existing one. So i'm wondering, will you accept that we add the types in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or maybe convert the existing code to typescript ?

Thanks in advance for your response,
Have a good day

**Comment by orestbida** [comment]
Hi @Anxium,

I don't mind switching to typescript in the future. For the moment, this will need to wait at least until v3 is released.

**Comment by Anxium** [comment]
I'm closing the issue as there is a typescript support now.
Thanks for this 🔥
