### ISSUE TITLE
Problem with very old website

### ISSUE THREAD

**Issue by gfmodica** [orestbida/cookieconsent#238]
I have a problem with a very old website write in classic asp:
when accept the cookie I realized it is written wrong :
`{"level":"[\"necessary\", \"analytics\", \"marketing\", \"funzionalita\"]","revision":0,"data":{"DateUpdate":"19-2-2022 0:9:41"},"rfc_cookie":false}`

note backslash before " and so it is not read correctly and not working
How i can solve?

**Comment by orestbida** [comment]
The plugin doesn't add backslashes. If you haven't modified the plugin, or manipulated the cookie value directly, then this might be due to ASP framework.

What kind of issue does this cause?

**Comment by gfmodica** [comment]
Issue is that value of cookie is read wrong and  so cookies are not activate after consent.
For you where  i can try to replace \ with empty value?

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by orestbida** [comment]
Are there any errors/warnings in the browsers console? Did you try enabling the `use_rfc_cookie` option?

**Comment by gfmodica** [comment]
no error in console.
I also try rfc but without success.
i would try to replace any \" with an empty string but in js i can't find where to do it.

**Comment by orestbida** [comment]
you can try and put this code before line 2142:
https://github.com/orestbida/cookieconsent/blob/82f34db917ed3a145a1fd50d316b5d0925a2fddd/src/cookieconsent.js#L2142

like so:
```
try{
if(found.indexOf('\') !== -1){


}

**Comment by gfmodica** [comment]
i change line 2142:
` if(found && name === _config.cookie_name){
                    try {
                        if (found.indexOf('\\') !== -1){
                            found = JSON.parse(found)
                         }
                        
                    }`
not work. Note that i had to add another backslah.
the value of cookies write is always {"level":"[\"necessary\", \"analytics\", \"marketing\", \"funzionalita\"]" instead of {"level":"["necessary", "analytics", "marketing", "funzionalita"]"

**Comment by orestbida** [comment]
you can try and modify line 2142:
https://github.com/orestbida/cookieconsent/blob/82f34db917ed3a145a1fd50d316b5d0925a2fddd/src/cookieconsent.js#L2142

like so:
```javascript
// if json string contains backslash characters => remove them
if(found.indexOf('\\') !== -1){
    found = found.replace(/\\/g, "");
}

found = JSON.parse(found) 
```

**Comment by gfmodica** [comment]
not work.
i add image of console.
[https://ibb.co/5RkVv2n](url)

**Comment by orestbida** [comment]
Can you add some `console.log` and `console.error` calls ? Just to know what is going on. Like so:

```javascript
try{
    console.log("before parsing: ", typeof found, found);
    found = JSON.parse(found);
    console.log("after parsing: ", typeof found, found);
}catch(e){
  console.error("parsing error1: ", e);
  try {
      found = JSON.parse(decodeURIComponent(found))
  } catch (e) {
      console.error("parsing error2: ", e);
      // if I got here => cookie value is not a valid json string
      found = {};
  }
}

**Comment by gfmodica** [comment]
nothing...
I realized it doesn't even write logs!

**Comment by orestbida** [comment]
There should be something on the browser's console, otherwise the script might not be running at all
