### ISSUE TITLE
Extract auto clear logic from cookie_table 

### ISSUE THREAD

**Issue by superbiche** [orestbida/cookieconsent#250]
Hey there,

First thanks SO MUCH, I spent hours looking for a working open source package and while some stuff could be enhanced, it works out-of-the-box, it's clean, looks great, and is quite easy to use. So really, kudos.

For the v3, would you consider decoupling `cookie_table` and `autoclear_cookies` ? The fact we need to have the name of the cookie as first column + `use_regex` among column names is not very intuitive, and it forces us to hide the column using CSS in many projects.  

I was thinking of something like this (multiple proposals included) :  
```js
{
                    title: 'Analytics Cookies',
                    description: 'Cookies you do not need if you are not hungry',
                    toggle: {
                        value: 'analytics',
                        enabled: false,
                        readonly: false,
                    },
                    autoclear: {
                      enabled: true, // Allows to enable/disable autoclear per-category?
                      targets: [
                        { name: 'woot', is_regex: false }, // Define if regex for each pattern.
                        { name: '^ga_', is_regex: true },
                        { name: 'cookie_we_dont_remove', is_regex: false, clear: false },  // Ability to disable autoclear for a single pattern.
                      ]
                    },
                    cookie_table: [
                        {
                            service: 'Google Analytics',
                            expiration: '2 years',
                            description: 'desc',
                            // is_regex: false, // this could be deprecated or even removed
                        },
                    ],
                }, 
```

What do you think? 
I'd be happy to drop a PR for the sake of the hours you just saved me with this plugin.

**Comment by orestbida** [comment]
@superbiche, v3 will have plenty of changes from the configuration point of view. I think #252 might suit your proposed change. 

I'm a bit skeptical on some features suggested here, like the "Ability to disable autoclear for a single pattern" or "Allow to enable/disable autoclear per-category". Could you describe some scenarios in which these option could come in handy?

**Comment by superbiche** [comment]
Closing in favor of #252
