### ISSUE TITLE
Set "cc_cookie" expiration to session if a cookie category is rejected

### ISSUE THREAD

**Issue by rabandy** [orestbida/cookieconsent#253]
Hello,

is it possible to set "cc_cookie" expiration to session if a cookie category is rejected?
So that the cookie banner appears again in a new session if a category was rejected in the last session.

I mean something like that:

```
if(!cc.allowedCategory('analytics')){
// Set/Change "cc_cookie" expiration to session
} 
```

Thank you.

**Comment by orestbida** [comment]
@rabandy, transferred the issue to the cookieconsent repo. 

I believe you will be able to achieve this once #251 is done!

**Comment by orestbida** [comment]
@rabandy, in v3 you'll be able to achieve this like so:

```javascript
cookie: {
    expiresAfterDays: function(){
        //if analytics category is not accepted => set as session cookie
        if(!cc.acceptedCategory('analytics')) return 0; 

        return 182; //otherwise 182 days
    }
}
```

Will be properly documented when v3 releases.
