### ISSUE TITLE
Export CookieConsent object, only bind to window if it's actually available

### ISSUE THREAD

**Issue by superbiche** [orestbida/cookieconsent#255]
Using `window` without making sure it's available will break in some JS frameworks (Nuxt/Next/etc) unless loaded as a client-only script. 
Making sure `window` exists would be quite easy and avoir breaking in those frameworks.

Also we could do something like:  
```js
import 'CookieConsent' from 'vanilla-cookieconsent'

window.addEventListener('load', () => {
  const consent = CookieConsent.init()
  
  consent.run({ /* options */ })
}
```

**Comment by darkowic** [comment]
I just encountered the same issue with Gatsby
