### ISSUE TITLE
Adopt Firefox's thin scrollbar and add overscroll-behavior

### ISSUE THREAD

**Issue by frankykubo** [orestbida/cookieconsent#256]
When you open the settings modal in Safari browser, elements #s-hdr (header element with title and close button) and #s-bl (scrollable element) are not aligned on right side, probably because of Safari's scrollbar behaviour. I tried to find a solution, but I haven't been able to, so at least I am reporting it here.

**Comment by orestbida** [comment]
Can you post a screenshot?

**Comment by frankykubo** [comment]
Yes, here it is.
![safari](https://user-images.githubusercontent.com/50501921/156720271-dee59a14-baeb-415e-83d6-c7ee9bc32df9.png)

As you can see, there is a gap highlighted with red rectangle. I don't know, probably this is how it should be (?). Anyway, on chrome, it is not there.

**Comment by orestbida** [comment]
Unfortunately, this is a normal behavior. Only chromium based browsers (Google Chrome, Opera, Microsoft Edge …) support this css rule (which allows the scrollbar to be on-top of the content:
```css
overflow-y: overlay;
```

You can also check a more detailed browser list here: [https://caniuse.com/css-overflow-overlay](https://caniuse.com/css-overflow-overlay)

**Comment by frankykubo** [comment]
Okay, thank you. Though, I have a recommendation about Firefox scrollbar (windows) and overscroll-behaviour (chrome, firefox, edge).

Adding this css:

```
#s-bl {
        scrollbar-width: thin;
        scrollbar-color: var(--cc-webkit-scrollbar-bg);
}
```
makes Firefox's ugly default navbar prettier.

and adding:
```
#s-bl {
        overscroll-behavior: none;
}
```
prevents from unwanted scroll of body element.

**Comment by orestbida** [comment]
Sure! Could you create a new issue with the above suggestions?
