### ISSUE TITLE
Auto detect dark mode

### ISSUE THREAD

**Issue by darkowic** [orestbida/cookieconsent#260]
Idea: Automatically detect dark mode based on user's system preferences.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by orestbida** [comment]
@darkowic sorry, I don't think this feature is worth it. 

In the future there could also be 2 new stylesheets (light/dark theme) and this option would not make any sense at all for those only using one theme.
