### ISSUE TITLE
Remove rfcCompliant option

### ISSUE THREAD

**Issue by OndraM** [orestbida/cookieconsent#264]
Hi, 
is there a reason why to keep rfcCompliant option in v3? I would suggest using the RFC mode by default and drop the "rfcCompliant: false" feature.

It would be BC for those using non-RFC mode with version 2, but this is why it is breaking change... The feature was kept for backward compatibility only (there is no other usecase afaik), so I guess it could be removed with new major version.

**Comment by orestbida** [comment]
The only "downside" I can see is that you'd need to decode/encode the value each time you want to directly access/modify the cookie.

Other than that, it should be totally fine removing it!
