### ISSUE TITLE
v3 release date

### ISSUE THREAD

**Issue by justinkruit** [orestbida/cookieconsent#269]
To start off, this is an amazing plugin with a really nice style!

I was wondering, since I saw the beta of v3, is there any planning on a full release of the version? At my work we want to integrate this into our system we use everywhere, and the breaking changes in v3 might be a reason for us to wait for the release depending on how soon that will be.

**Comment by orestbida** [comment]
Hi @justinkruit,

Unfortunately, I don't have any specific release date for the v3.0.0 build. If I really had to choose a timeframe, I'd say that in ~a month, it should pretty close to the final build.

Until then, I could release intermediate beta builds (be warned, there could be breaking changes from one beta to another). You'd need to follow the instructions in the v3-beta branch's [README.md](https://github.com/orestbida/cookieconsent/tree/v3.0-beta) file, which should receive updates in the next days.

**Comment by justinkruit** [comment]
Just wondering... It has been over a year now, do you have any plans to make a final release for v3.0.0, or gonna keep with the RCs? 😜
