### ISSUE TITLE
cookie accepted on domain valid also on subdomains

### ISSUE THREAD

**Issue by webhostingsrbijaRS** [orestbida/cookieconsent#274]
Hello, is it possible to add cookie that is accepted on domain.tld to be also accepted also on clientarea.domain.tld
it is the same site but the second one is for clieantarea. 

From configuration i tried:

cookie_domain: '.domain.tld'
and
cookie_domain: 'domain.tld'

but cookie is always set to www.domain.tld

**Comment by orestbida** [comment]
Hi @webhostingsrbijaRS,

If what you're saying is correct, then this is definitely a bug. Do you have an online demo/website where I can further inspect the issue?

**Comment by webhostingsrbijaRS** [comment]
[website](https://www.webhostingsrbija.rs)

**Comment by orestbida** [comment]
Based on your configuration, the cookie looks to be set on the right domain, and should therefore be accessible from any subdomain.

```javascript
cookie_name: 'izborkolacica',
cookie_domain: '.webhostingsrbija.rs',
cookie_path: '/'
```

![uuu](https://user-images.githubusercontent.com/34487268/159568559-deb090da-80a1-42b7-a4c9-7bdf00d009a4.PNG)

**Comment by webhostingsrbijaRS** [comment]
i am using developer tool in chrome and result is different
![developertoolschrome](https://user-images.githubusercontent.com/15720022/159571091-0de3d967-ad86-4308-91fc-3fb7336149dc.PNG)
also i have other cookies (affiliate) without "www"

**Comment by orestbida** [comment]
Yes, looks fine to me. 

Could this be an issue related with the cache not being cleared properly (if you have any)? Have you tried using a VPN on a new private window — or a completely different browser — and see if the issue persists?

![ddsds](https://user-images.githubusercontent.com/34487268/159574282-63d1e5e5-a680-4ef5-aa84-c1ba077e70fb.PNG)

**Comment by webhostingsrbijaRS** [comment]
My apology, even in incognito show me the problem i reported, on TOR it is like you said. So this is definitely on my end. Thank you, for your reply and this awesome repo.
