### ISSUE TITLE
Register (multiple) callback handler on the instance

### ISSUE THREAD

**Issue by eyecatchup** [orestbida/cookieconsent#276]
Currently, you can set up a single event handler (for each of the 3 events) within the configuration upon initialization. The first tradeoff of this is, you have to mix up business logic and configuration. Also, you can not setup multiple event handlers; i.e. a dedicated handler from within a class / component. Or you can't change event handlers dynamically, based on application state. Some code to illustrate:

---

### Option 1 with the current implementation

```js
window.cc = initCookieConsent()
cc.run({
    // config ...
    onAccept: function() { 
        ComponentA.doStuff()
        ComponentB.doStuff()
    }
})
```

This approach will mix business logic and configuration; not ideal. Also, it's a one-shot solution; you need to setup all (possibly) required listeners before initialization.

### Option 2 with the current implementation

_Note, this is basically [how I handle event hooks for the Vue plugin](https://github.com/eyecatchup/vue-cookieconsent/blob/main/src/index.ts#L18) I created for your library._

```js
// init-cc.js
window.cc = initCookieConsent()
cc.run({
    // config ...
    onAccept: function() { 
        window.dispatchEvent(new Event('consentOnAccept'))
    }
})

// componentA.js
window.addEventListener('consentOnAccept', () => { 
    /* component specific business logic */
    if (cc.getUserPreferences().accepted_categories.includes('analytical')) {
        // whatever
    }
}, false)

// componentB.js
window.addEventListener('consentOnAccept', () => { /* component specific business logic */ }, false)
```

This approach will _not_ mix business logic and configuration; better. Also, you can setup the listeners _after_ initialization. _But_ it's relying on events; still not ideal.

---

### Suggested addition

What I'd like to suggest is an approach as follows:

```js
// init-cc.js
window.cc = initCookieConsent()
cc.run({ /* config */ })
```

_Sidenote: I don't suggest to remove the ability to define an onAccept handler within your configuration. It just shouldn't be the sole option, IMHO. So, let's move on._

```js
// componentA.js
const namedFnContainingComponentSpecificBusinessLogic = () => {
    /* component specific business logic */
    if (cc.getUserPreferences().accepted_categories.includes('analytical')) {
        // whatever
    }
}

cc.addListener('onAccept', namedFnContainingComponentSpecificBusinessLogic)

// maybe later..
cc.removeListener('onAccept', namedFnContainingComponentSpecificBusinessLogic)
```

Internally, instead of executing a single defined callback function, both the initial configured handler and all later registered event handlers will be hold in an array and all get executed on accept/change.

---

Thoughts, @orestbida? If you agree, this would be a beneficial addition, I'd like to offer my help to implement the suggested change and provide a PR for it.

**Comment by orestbida** [comment]
Hi @eyecatchup,

I really like the idea!

If this is implemented though, I would likely remove the current callback functions. I don't see a good enough reason to keep them.

Also, I wish the `.addListener()` and `.removeListener()` names were a bit more concise. E.g. `.addListener('onAccept', doSomething)` could be changed to `.on('accept', doSomething)`.

**Comment by orestbida** [comment]
- From the [v3.0-beta](https://github.com/orestbida/cookieconsent/tree/v3.0-beta) branch.
- I couldn't come up with a better name either; so `off` it is.
- I would prefer that you actually removed the callbacks completely.
- The current callback names (in v3 beta) are `onFirstConsent`, `onConsent` and `onChange` — from which you should remove the 'on' prefix — and therefore should become: `firstConsent`, `consent` and `change`

Although not necessary (since there are dedicated methods to retrieve the same data), you should keep the same arguments.

**Comment by eyecatchup** [comment]
Great, will implement it on monday.

**Comment by eyecatchup** [comment]
Had some time and already started on this. The `on` part was fairly easy and already works as expected. 

```js
const cc = CookieConsent.init()
cc.run({ /* config */ })

const doStuff = (savedCookieContent) => {
    console.log('doStuff', savedCookieContent)
}

const doStuff2 = (savedCookieContent) => {
    console.log('doStuff2', savedCookieContent)
}

cc.on('consent', doStuff)
cc.on('consent', doStuff2)
```

See the [two related commits](https://github.com/eyecatchup/cookieconsent/commits/feature/event-handler).

---

However, I don't have an idea at the moment of how to implement the `off` part. Since there's [no way to uniquely identify a function ***instance***](https://stackoverflow.com/questions/1630863/uniquely-identify-a-function-in-javascript), I wonder how this could be solved. I might look at how native Event listeners are implemented. Any idea from your side?

**Comment by orestbida** [comment]
Mhm, I tried setting up a quick array of named functions, and `.filter` seems to identify the named function just fine.

```javascript
const myCallbackToRemove = () {
    console.log('doSomething');
}
// before: callbacks.onAccept: [Function [myCallbackToRemove]]

callbacks.onAccept = callbacks.onAccept.filter(existingCallback => {
    return existingCallback !== myCallbackToRemove
});

// after: callbacks.onAccept: []
```

**Comment by eyecatchup** [comment]
Yep, that would work. I was worried about something like, but in fact it does remove the correct instance. Even though the functions signature of `this.bar` is identical in both Classes. 🤷🏻‍♂️

```js
class A {
    constructor() {
        this.foo = false;
        this.bar = () => { this.method() }
        cc.on('consent', this.bar)   
        cc.on('change', this.bar)   
    }
    method() {
        this.foo = true;
        console.log('method in class a')    
    }
}

class B {
    constructor() {
        this.foo = 'abc';
        this.bar = () => { this.method() }
        cc.on('consent', this.bar)
        cc.on('change', this.bar)
    }
    method() {
        this.foo = 'def';
        console.log('method in class b')
    }
    del() {
        console.log('remove change handler from class b')
        cc.off('change', this.bar)
    }
}

const _A = new A()
const _B = new B()

setTimeout(() => {
    _B.del()
}, 25000)

```

So, since I confirmed this is working as intended, the `off` implementation is ready as well. I'll clean up a bit and create the PR by the end of the weekend. Cheers

**Comment by orestbida** [comment]
Re-opening this issue. 

I just realized that this method has a fundamental flaw: you have to put the `on(event, callback)` methods between `CookieConsent.init()` and `.run()`, to make sure that all callbacks are executed.

While things work on the very first consent, they break on subsequent page loads. The `consent` event is fired synchonously immediatetly after `.run()`, and any defined callback registered on the `consent` event will be ignored, unless delcared before the `.run()` method.

**Comment by orestbida** [comment]
I think it would be better to go with your second suggested option, and perhaps keep the previously removed callbacks. It would require very small changes and yet offer way more flexibility, at the cost of dealing with an uglier syntax.

**Comment by orestbida** [comment]
Sorry, just went ahead and implemented your second approach since it was something quite simple to do. Couldn't bear with the limits of the current method.

The new custom events have the same names as the callback functions: `onFirstConsent`, `onConsent` and `onChange`:

```javascript
window.addEventListener('onFirstConsent', function(){
    // do something ...
});
```
