### ISSUE TITLE
Dynamically update config

### ISSUE THREAD

**Issue by ebracci** [orestbida/cookieconsent#277]
Hi everyone,

I was reading the documentation and I finded out that it is possible to dynamically update the configuration.
For example:
```
// Change content: e.g. modify modal title
cookieconsent.getConfig('languages').en.consent_modal.title = 'New title';
```
I have a question on how this statement works. 

Which fields of the configuration are upgradeable? Only the languages or also the other fields?

I tried to do something like that:

`
cookieConsent.getConfig('auto_language') = 'browser';
`

but this statement trigger **Invalid left-hand side in assignment** error.

Are there other ways to do that?

Furthermore, Is there a method to retrieve the entire current configuration?

Thank you in advance

**Comment by ebracci** [comment]
Hi @orestbida,

First, thank you for your fast and clear reply.

Just a question that could seem "stupid": why I need to have two different configurations? In the run method some fields of the default config (_config) are overwritten with user_config values. 

So a kind of merge is already done, isn't it?

Now. I'll try to explain my goal and what I'm trying to do.

I am building a wrapper application (a kind of lib) for this library that offers to the user the possibility to use this library just importing a script tag in the head/body of the index.
Something like this:
`
<script src="mycookieconsentlib.js></script>
`
In my application I have exposed methods like hide, hideSettings, show, updateLanguage and so on but NOT the run method (I don't want that the user has the possibility to call it but it must be called when my library is imported in the project).

That's why I have different projects that I want that they shared the same library, configuration and logic.

In practice, each project has only to import the library as a simple script tag and the default cookie-config.json that I have generated in my project will be used. 

However, in each project there might be a need to modify only few parameters of the configuration such as (as in the example) the `auto_language`, the `gui_options` or the` onAccept`,`onChange`/`onFirstAction` function.

It could be interesting have some methods to update the single value (or more at once) of the configuration at runtime.

At the same time, a function that returns the entire current configuration (maybe with a parameter to choose which configuration the user need?) it wil be usefull.

I have already implemented a method that, given an object, it updates the config values but, as I previously said in the first question, it works only if the field of the configuration is an object. Otherwise, I obviously receive an **Invalid left-hand side in assignment** error.

I hope to have been clear and I remain available for further clarification.

Thank you in advance

**Comment by orestbida** [comment]
You will always need 2 configurations and although you can merge them entirely, it's just not needed.

As for the ability to update the config., I don't think it's worth implementing. There would be too many small things to handle when updating certain fields (post-execution).

E.g. knowing that the plugin has already called the `.run()` method;
what should happen if I were to change the name of the cookie ? Should I treat it as an "ask again for consent" case, or just rename the cookie in the background? What if I change the content of the `onAccept` callback, should I re-run it? There are surely many other weird cases like these.

Those using my version (with a config/execute-event needed) would find the new "updateConfig" method useless, or at least I see it as such.

The simplest solution would be to — somehow — let your version of the plugin know beforehand if it needs to wait for the user's config. or not. One way to achieve that is by using a custom attribute on the script tag itself. If it is present => don't run the plugin automatically: 

```html
<!--Case1: Executed automatically -->
<script src="mycookieconsentlib.js"></script>

<!-- Case2: Wait for the user's config -->
<script src="mycookieconsentlib.js" data-config></script>
<script>
mycookieconsentlib.run({
    // user's custom options
});
</script>
```

**Comment by Loosie94** [comment]
Hi @orestbida , I read this because I was facing the same issue. 

I understand the usage of the config file with the .run() function, but I'm missing a .destroy() function for example. 
If this was available, we can just update the config file, destroy the current consent and fire the .run() function with the new config. Or is there an easier way now?

Thanks!

**Comment by orestbida** [comment]
@Loosie94, unfortunately v2 will not receive new features. There is however a [`.reset()`](https://cookieconsent.orestbida.com/reference/api-reference.html#reset) method available in v3.
