### ISSUE TITLE
`npm run build`

### ISSUE THREAD

**Issue by eyecatchup** [orestbida/cookieconsent#280]
Currently, it seems to be a manual step to build the dist files?! Any plans to include the bundling into the project source? So everyone could run a simple `npm run build` to create a dist version?

**Comment by eyecatchup** [comment]
Sorry, my mistake. Just checked out the master.

**Comment by orestbida** [comment]
haha, you are right then. Up until v2.x.x there was never a public tool to automatically generate the files
