### ISSUE TITLE
Cannot initiate the run method

### ISSUE THREAD

**Issue by dungle-scrubs** [orestbida/cookieconsent#284]
Hi,

I'm following the React guide at the bottom of the FAQ and it doesn't want to work for me. I get the error:

`Cannot read properties of undefined (reading 'cookie_expiration')`

which you can see in [this CodeSandBox](https://codesandbox.io/s/vanilla-cookieconsent-react-xskjed)

Any suggestions?

Thanks

**Comment by orestbida** [comment]
Hi @dungle-scrubs,

the `.run()` method expects a full-valid configuration, which is missing in your example. You also need to import the `css`:

```javascript
import 'vanilla-cookieconsent/dist/cookieconsent.css';
```

If things still don't work, you could try importing both the script and the stylesheet using a full path:
```javascript
import "../node_modules/vanilla-cookieconsent/dist/cookieconsent.js";
import "../node_modules/vanilla-cookieconsent/dist/cookieconsent.css";
```
