### ISSUE TITLE
How to autorun cookie on all pages except Privacy Policy page

### ISSUE THREAD

**Issue by gh4l3b** [orestbida/cookieconsent#287]
I have problem trying to prevent the cookies from initiating in Privacy Page. https://url/privacy
However I still want the script to be there (cookieconsent-init.js) so I can trigger the settings using `data-cc="c-settings"`

Thank you

**Comment by orestbida** [comment]
You need to distinguish the privacy page from the others. If it is the privacy page => disable the `autorun` option.

There are many ways to achieve this. You could create a `script` tag inside the `head` section of the privacy page, and then declare a global variable with a unique value. Example:

`privacy-page.html`
```html
<html>
  <head>
       <!--- head things ... -->
      <script>
          window.page = 'privacy-page';
      </script>
  </head>
<body>
     <!-- body things -->
    <script defer src="cookieconsent.js"></script>
    <script defer src="cookieconsent-init.js"></script>
</body>
</html>
```

`cookieconsent-init.js`

```javascript
const cc = initCookieConsent();

cc.run({
    autorun: window.page !== 'privacy-page',
    // other config. options
});
```

This approach will prevent the consent modal from being shown. Everything else would work as usual.

**Comment by gh4l3b** [comment]
Thank you so much, this solved the issue.
