### ISSUE TITLE
Automate cookies list

### ISSUE THREAD

**Issue by joaogomez** [orestbida/cookieconsent#296]
Hello, it would be nice to have an option to automatically fetch the cookies categorized in the document.

**Comment by orestbida** [comment]
Hi @joaogomez,

could you elaborate more? 

From what I understand, this would require a database or a `.json` file with the cookies already categorized. It would be a hybrid solution, as you will still need to manually declare cookies specific to your website.

**Comment by joaogomez** [comment]
Hello @orestbida,

Why not read all the scripts in the document that matches the configured categories and list it automatically? for dynamic ones maybe use MutationObserver?

**Comment by orestbida** [comment]
Sorry, I don't understand what you mean. Could you describe/show an example of how this should work?
