### ISSUE TITLE
autoclear_cookies not working?

### ISSUE THREAD

**Issue by remberg** [orestbida/cookieconsent#30]
Hello, I have activated autoclear_cookies but all cookies are still displayed.

Kind regards,
Stefan

**Comment by orestbida** [comment]
Hi @remberg,

did you list the cookies inside the `cookie_table` (if so, make sure the first property contains the name of the cookie) ?

here's what it would look like: https://github.com/orestbida/cookieconsent/blob/a86368fec4b742ff329b1e6b21dd36525016a7fb/demo/app.js#L95-L102

If both answers are yes, then I'd need some additional info. to assist you, like:
- any errors/warnings in console
- the version you're using
- your config. object (or an example config with the same issue)

**Comment by remberg** [comment]
Ah ok, now it works. Thanks a lot!

**Comment by AdamReznicek** [comment]
@orestbida Is it posible use cookies name like '_ga/_ga*, _gid', or need to be each alone?

**Comment by erzzo** [comment]
@orestbida Hi. I've seen more issues with the autoclear_cookies option and I have a simmilar issue. Some of the cookies are cleared, when I change the option, but the hotjar cookies are not. When I refresh the page then the hotjar cookies are gone. The cookies table for the analytics type looks like this:
`
{
  col1: '^_hj',
  col2: 'hotjar.com',
  col3: 'XXX',
  col4: 'YYYY,
  is_regex: true,
},
`
after disabling the analytics option, some of them are cleared (google) but hotjar remains:
![image](https://user-images.githubusercontent.com/886192/197546423-cfbad101-af1f-441e-b314-2c8c9a29150d.png)

Do you see some issie with it? Thanks a lot

**Comment by orestbida** [comment]
@erzzo, you cannot delete cookies that are not on your domain. Those are third party cookies, and you shouldn't worry about them.
