### ISSUE TITLE
Support for a third button

### ISSUE THREAD

**Issue by mc7244** [orestbida/cookieconsent#304]
Some Italian company associations (i.e. AICEL) say that a third button to refuse all cookies is necessary to be GDPR-complaint.

While I'm quite sure this is not true, to get their certification it's mandatory to have it, so it would be nice to have the option to add a third button, after primary and secondary, via config options.
It could then in this case be mapped map it to "accept_necessary", leaving accept_all and setting for the other.

**Comment by orestbida** [comment]
Hi @mc7244,

this has already been addressed in v3 beta: #288
