### ISSUE TITLE
Allow analytics by default

### ISSUE THREAD

**Issue by mohamedHamadaboy** [orestbida/cookieconsent#305]
Hello .
Actually all works fine for me but i want to know if it possible to show google analytics cookie by default if the user didn't reject analytics cookies.
how i can achieve that ?

**Comment by dombyte** [comment]
What do you mean by show the cookie? Show in your browser? 
If so the cookie only gets shown when the cookie is set by analytics. The cookie consent plugin doesn't actually set the analytics cookie only blocks it if you're not accepting the analytic cookies. The plugin only sets the cc_cookie be default to save the user settings.
