### ISSUE TITLE
Default to user_config.current_lang when auto_language is 'document' and document.documentElement.lang is not set

### ISSUE THREAD

**Issue by rayronvictor** [orestbida/cookieconsent#309]
### Expected behavior
When using `auto_language: 'document'` and `document.documentElement.lang` is not set (`<html>` without lang) default to `user_config.current_lang` before defaulting to `_config.current_lang`.

Example:
```html
<html> <!-- without lang -->
```
```javascript
const cc = initCookieConsent();

 cc.run({
  current_lang: 'pt-BR',
  auto_language: 'document',
  languages: {
    'pt-BR': {/*...*/},
    'en': {/*...*/},
  },
})
```

### Current behavior
When using `auto_language: 'document'` and `document.documentElement.lang` is not set `current_lang` has no effect.

**Comment by orestbida** [comment]
Hi @rayronvictor,

thanks for taking your time to create the issue + pr. Unfortunately, I don't plan on releasing new v2.x.x versions.

A better, broader approach is to check if the value returned from `document.documentElement.lang` (which in this case is an empty string `''`) is defined as a property key of the `language`'s object. If it is not, use default language. This was implemented in v3.0-beta.
