### ISSUE TITLE
Reload button with modal .showSettings

### ISSUE THREAD

**Issue by dngraphisme** [orestbida/cookieconsent#315]
Hello @orestbida,

Thank you for your plugin which is really great.

I just have a small problem with barbaJS. This library does not reload pages and therefore does ajax for navigation.

We therefore need to reset certain scripts before entering a new page.

The issue I am having is the following:

With the button to restart the modal > data-cc="c-settings"

Unfortunately this one does not work after a page change.

I therefore tried to trigger this action directly on click like this:

```
$("footer.cookie-modal").click(function () {
             cookieNotice.showSettings(0);
         });
```

It works fine except that when changing the page, if I click again I get this JS error:

`Uncaught TypeError: can't access property "setAttribute", E is undefined`

Can you tell me how to fix it?

Thanks in advance, regards Nicolas

**Comment by orestbida** [comment]
I believe the issue is the following:

1. Page load (both cookieconsent and barbajs are executed)
2. Page change (cookieconsent's generated html markup was deleted)
3. `.showSettings()` throws an error as the html markup does not exist anymore

You'd need to re-initialize the plugin before the calling the `.showSettings()` method, or right after barbajs has finished loading the new page.

Example:
```javascript
const cc = window.initCookieConsent();

$("footer.cookie-modal").click(function () {
    if(!document.getElementById('cc--main')){
        cc.run({
            // your config
        });
    }

    cc.showSettings(0);
});
```

**Comment by dngraphisme** [comment]
Hello @orestbida 

Wow thank you very much! 

I'll test this asap and get back to you if it worked :)

thanks again

**Comment by dngraphisme** [comment]
Hello @orestbida 

I come back to you to tell you that unfortunately none of the techniques work.

Here is my code to explain it properly :

1. The footer is reloaded by barbaJS on each page because it is in `data-barba="container"`
2. I call the cookies function at the init of the first launch of the site >  `init: function () {}`
3. I relaunch the function only for the modal in the footer at the `hooks.beforeEnter` of barbaJS >  `reload: function () {}`
4. Here is my code for you to understand
```
export const cookie = {
    init: function () {
        const cookieNotice = window.initCookieConsent();
        cookieNotice.run({
            // my config
        });
    },
    reload: function () {
        const cookieNotice = window.initCookieConsent();
        $("footer .cookie-modal").click(function () {
            cookieNotice.run({
                // my config
            });
            cookieNotice.showSettings(0);
        });
    }
}
```
5. The footer at each page change always has this: `<a class="btn underline cookie-modal" data-cc="c-settings">Cookie management</a>`

The click still works, but I have this JS error that does not clean in the console :D

However, I did not understand your last hypothesis ^^

Thanks for your help :)

**Comment by orestbida** [comment]
@dngraphisme one solution is to make sure that the markup generated by the plugin is outside of the barbajs' wrapper (so that it does not get deleted/reloaded).

The plugin should be initialized only once.

```html
<button type="button" id="show-preferencesModal">Show Cookie Preferences</button>
```
```javascript
function addBtnClickListener(newBody) {
    const btn = (newBody || document).querySelector('#show-preferencesModal');

    btn.addEventListener('click', () => {
        cc.showPreferences();
    });
}

barba.hooks.afterEnter((data)=>{
    addBtnClickListener(data.next && data.next.container);
});
```

Demo:

https://user-images.githubusercontent.com/34487268/173868335-bda96829-5a34-40b0-acb5-a76ca7fda138.mp4

Note: In this example I'm using the v3.0-beta version of the plugin, but the same applies to v2.8. Instead of `.showPreferences` you'll have to use `.showSettings()`

**Comment by dngraphisme** [comment]
Hello @orestbida,

Thank you very much for taking the time to give me an example.

I still can't fix the error, I did the exact same thing as you and it still doesn't work :

**cookie.js >**

```
export const cookie = {
    init: function () {
        const cookieNotice = window.initCookieConsent();
        cookieNotice.run({
            // my config
        });
    }
}
```

---

**init.js >**

```
barba: function () {

const cookieNotice = initCookieConsent();

        function addBtnClickListener(newBody) {
            const btn = (newBody || document).querySelector('#show-preferencesModal');
            btn.addEventListener('click', () => {
                console.log(btn)
                cookieNotice.showSettings();
            });
        }

barba.hooks.afterEnter((data) => {
            console.log("afterEnter")
            addBtnClickListener(data.next && data.next.container);
        });

}
```

---

**example for template .php >**

```
<div class="wrapper" data-barba="container" data-barba-namespace="">

<?php get_footer(); ?>

</div>
```

---

The footer is in the barba container, and that's where there's the link to make the popup work.

---

cookieConsent is launched only once and it is well outside the container barba, and I still get the error...

`Uncaught TypeError: can't access property "setAttribute", E is undefined`

I really don't understand ^^'

**Comment by orestbida** [comment]
> cookieConsent is launched only once and it is well outside the container barba, and I still get the error...

Can you inspect the HTML code in your browser, and make sure that cookieconsent's HTML markup is still there after page change?

Unless you create a minimal example with the issue on platforms like [CodeSandbox](https://codesandbox.io/) or [PHPSandbox](https://phpsandbox.io/), It's hard for me to say what/who the culprit is.

**Comment by dngraphisme** [comment]
Hello @orestbida,

Thanks again for answering me. I can't make you sandbox with this stack because I'm under WP6 running locally.

So difficult to have this on a sandbox.

----

I made a video for you so you can understand.

And yes, cookieconsent's HTML markup is always present on page change with barbaJS

Thanks again for your help !

https://user-images.githubusercontent.com/5530905/174428905-1e404d56-726f-4dcc-a95e-822b060cd90b.mp4

**Comment by orestbida** [comment]
I think the culprit could be the fact that you're calling `initCookieConsent` twice. 

- inside `cookie.js`
- inside `init.js`

you should call `initCookieConsent` only once. A second call will reset the internal pointers to the DOM elements and give you that error (many other things might be broken too).

For example, you could change this to:
```javascript
export const cookie = {
    init: function () {
        const cookieNotice = initCookieConsent();
        cookieNotice.run({
            // my config
        });
        // Important, always use the same "instance" of cookieconsent 
        return cookieNotice;
    }
}
```

Then, inside `init.js`, you could store the return value of `cookie.init()` and make it accessible to any function inside that file:


```javascript

let cookieNotice;

export const init = {
    firstLoad: function () {
    
        cookieNotice = cookie.init();
        init.barba();
    },
    barba: function() {

        // remove this line!
        const cookieNotice = initCookieConsent();
    }
}
```

**Comment by dngraphisme** [comment]
Hello @orestbida ,

**You are a boss...** 

I understood my mistake ! 

Really thank you very much for your help.

Regards Nicolas :)

**Comment by orestbida** [comment]
Sure, no problem!
