### ISSUE TITLE
'Accept all' not working if showing the cookie consent again after accepting once

### ISSUE THREAD

**Issue by italomandara** [orestbida/cookieconsent#328]
Since i needed to make the user to re-accept if they remove the cookie, I discovered this issue.

**Steps to reproduce:**

- accept cookies
- remove/change cookie to ''
- re-open the dialog using the show() method
- click the 'accept' button

_in this case the cookie doesn't get saved_

- accept cookies
- remove/change cookie to ''
- re-open the dialog using the show() method
- open the preferences
- click 'accept necessary'

_in this case it works and always will, including when you click 'accept' from the main dialog_

**Comment by italomandara** [comment]
ok any way to reset the categories with some method?

**Comment by orestbida** [comment]
Unfortunately, it's not possible without writing custom code.

The idea is to save the cookie's value every time one of these callbacks is executed:
- `onAccept`
- `onChange`

Then you can add a new `eventListener` to each button:

```javascript
const btns = [
    ...document.querySelectorAll('#s-bns .c-bn'),
    ...document.querySelectorAll('#c-bns .c-bn')
];

btns.forEach(btn => btn.addEventListener('click', () => {
    if(!cc.validCookie(cc.getConfig('cookie_name'))){
        // set saved cookie value
    }
}));
```

You'd need to define a "setCookie" function. You can retrieve any of the cookie's settings using the `getConfig()` method.
