### ISSUE TITLE
Change to NPM configuration today maybe causing issues

### ISSUE THREAD

**Issue by karptonite** [orestbida/cookieconsent#333]
Hey, so starting today, vanilla Cookie Consent started misbehaving in a few ways that I suspect are related to the changes in the way it is being distributed via NPM.

We are using version 2.7.0, and on every deploy, we pull the code down from npm via yarn, and deploy the code from the `dist` directory. After a deploy earlier today, we got reports of issues from users, which you can read in the following discussions:
https://boardgamegeek.com/thread/2891715/pages-not-displaying-older-apple-oss
https://boardgamegeek.com/thread/2891626/your-privacy

Since we hadn't changed anything related to Cookie Consent, it was pretty confusing, until I tried loading up the site in firefox 78, and saw that now the minified js was using the logical OR assignment (`||=`), even in the version 2.7.0 code. This was not supported by Firefox until version 79. 

The problems reported in the second thread did not seem to be directly related to users using incompatible older browsers--the site was working, but they were having trouble saving the consent preferences. I don't know exactly what caused this issue, but it can't be a coincidence that this bug came up at the same time as the other one.

For now, we are solving this problem by compressing the js from `src` ourselves, and deploying it. But there is definitely some issue with the way this package is being distributed.

I hope this is a helpful report. Let me know if you have any other questions about it.

**Comment by orestbida** [comment]
Thanks for letting me know!

Looks like there was an issue with the minification tools' config. parameters. I'll make sure the minified output is in es5 format and that it runs in IE9-IE11. 

Will release a minor revision soon.

**Comment by karptonite** [comment]
OK, just to give you a quick correction on my initial report, I was inadvertently using the "latest" version of Vanilla Cookie Consent.
When version 2.8.1 went out yesterday, two things happened. As reported in 
https://boardgamegeek.com/thread/2891715/pages-not-displaying-older-apple-oss, the code stopped working entirely on old browsers, probably due to minimization. I fixed that by deploying src instead.

However, there was a separate issue, https://boardgamegeek.com/thread/2891626/your-privacy, that was NOT fixed by deploying src. I think that this may be a legit bug in 2.8.1, separate from the minimization, that occurs for users in modern browsers, but I cannot reproduce it myself.

For now, I'm rolling back to 2.7.2 on production to try to avoid this other bug. Sorry I don't have more details about it, but perhaps by reading that thread, you may get some idea of what the issue might be.

**Comment by orestbida** [comment]
v2.8.2 fixes the minified files. 

I was not able to reproduce the issue described in the second thread. If v2.7.x works fine for you, you might as well stay with it. v2 will no longer receive feature updates, only bug fixes — as I'd like to focus on v3.
