### ISSUE TITLE
Icon to riedit cookies

### ISSUE THREAD

**Issue by voltaichail75** [orestbida/cookieconsent#339]
Hello, I would like to understand what I can do to make sure that a user can change the cookie choices ... for example an icon that refers to the banner or the like ... this possibility is already implemented and if so how can I activate it? thank you
P.S. be patient I am not a professional but I am learning ...

**Comment by stehled** [comment]
This isn't about learning but about reading. Look into FAQ. `<button type="button" aria-label="View cookie settings" data-cc="c-settings">Cookie Settings</button>`

**Comment by voltaichail75** [comment]
Thank you stehled i've done and all is ok!!! next time i'll see FAQ better :)

**Comment by orestbida** [comment]
@voltaichail75, if you'd like to manually implement a nice “floating button”, you can check out #326. 

Closing this issue.
