### ISSUE TITLE
Invoking "onChange" after user's action with the new revision

### ISSUE THREAD

**Issue by tg666** [orestbida/cookieconsent#340]
Hi!
We have previously integrated your plugin into GTM - https://github.com/68publishers/cookie-consent
As it is necessary for consent to be stored somewhere, we are developing an application that is integrated with our wrapper.

https://github.com/68publishers/consent-management-platform

The application has (or will have) several features like

- user management
- statistics (the number of consents per period, positive consents ratio, etc.)
- multiple projects (websites) support
- cookies & cookie providers management (common or per project)
- storage of user consents
- the easy way how to print cookie providers table into your webpage
- and more ...

And the CookieConsent Wrapper communicates with the CMP application in both ways:

- READ - the cookie plugin reads cookies from the CMP application and creates cookie tables from it.
- WRITE - the cookie plugin sends a user's preferences into the CMP.

And now to the issue.
When a user is on the website and makes for example his first action - clicks on the "Accept all" button - callback "onFirstAction" is invoked - everything is fine. The consent is stored.

But when we increase the `revision` and the user clicks again on the "Accept all" button then no callbacks are invoked. But in this case, I would expect the "onChange" callback to be invoked.
On the one hand, yes, there was no change in preferences. On the other hand, it is necessary to know that the user has given his consent to the new form of the terms - new revision.

How to solve this?

1) Call `onChange` callback on preferences change and also after an action if the revision changed, but the preferences remained the same. Is it BC break?
2) New configuration option, something like `invokeCallbacksAfterNewRevision: false|true` (no BC break)
3) New callback? (no BC break)

Thank you
Finally, for your interest, I am attaching a couple of screenshots from CMP 🙂 The application is currently localized in the Czech language, but it will also be in English before the release.
<img width="1792" alt="Snímek obrazovky 2022-07-11 v 22 27 42" src="https://user-images.githubusercontent.com/24430186/178352281-abf60c4e-5164-4590-a045-c5a7ea7ccc5a.png">
<img width="1792" alt="Snímek obrazovky 2022-07-11 v 22 28 33" src="https://user-images.githubusercontent.com/24430186/178352417-663c7e10-a827-4c78-be4b-6d50098c6994.png">
<img width="1792" alt="Snímek obrazovky 2022-07-11 v 23 26 59" src="https://user-images.githubusercontent.com/24430186/178361409-58816f84-a65d-46a5-8f2f-1d845ed762d6.png">

<img width="1792" alt="Snímek obrazovky 2022-07-11 v 23 27 44" src="https://user-images.githubusercontent.com/24430186/178361514-395d11c7-f598-4e63-af8b-0c39b23c087c.png">
<img width="734" alt="Snímek obrazovky 2022-07-11 v 23 28 26" src="https://user-images.githubusercontent.com/24430186/178361598-dd6f598d-d239-44d4-9746-3a6c9a120670.png">

**Comment by orestbida** [comment]
Mhm, I honestly would re-execute the `onFirstAction` callback since it was added specifically for logging purposes. Currently it is executed once, but I would like to change its behavior so that it runs when consent is not valid:

- on invalid cookie
- on revision change

I would like to avoid adding further features to v2 and focus on v3 instead.

**Comment by orestbida** [comment]
@tg666 

>But when we increase the revision and the user clicks again on the "Accept all" button then no callbacks are invoked. But in this case, I would expect the "onChange" callback to be invoked.

I might be missing something. I tried changing the revision number on of the demos and both the `onFirstAction` and `onAccept` callback are executed after the new consent (as expected).

This behavior is defined here:
https://github.com/orestbida/cookieconsent/blob/4a2f57662d607e422381f0cb016ac7573795d0f3/src/cookieconsent.js#L1179-L1191

The `onChange` callback is executed if the following conditions are all true:
- consent is valid
- the user changed the preferences

Why isn't the `onFirstAction` callback suitable for your use case?

**Comment by tg666** [comment]
Oh,
I'm sorry, I had version `2.8.0` in a project. And with this version, it doesn't work but from `2.8.1` yes.
Of course, the `onFirstAction` callback is now enough for my use case.

Thank you very much.
Btw. when do you estimate the `v3` will be stable and fully documented?

**Comment by orestbida** [comment]
Note that there is a breaking change in v2.8.1+ — explained here https://github.com/orestbida/cookieconsent/issues/349#issuecomment-1195535562 — which might cause issues. 

`v3` is pretty much done, at least from the coding side. The documentation however is not ready yet, as there are missing sections which need to be worked on before the release. `v3` should be ready in ~1 week (hopefully).
