### ISSUE TITLE
On selected close button wierd small box

### ISSUE THREAD

**Issue by T-D3V** [orestbida/cookieconsent#341]
![image](https://user-images.githubusercontent.com/40610605/178455962-7f6177cb-eb14-476e-b93e-8a8b444245bb.png)

When I tab onto the close button the wierd little box also get's selected, what is this and how can i fix it?

Thanks for the help, it's also on the demo site.

**Comment by orestbida** [comment]
This was not present months ago. Will be fixed in the next revision.
