### ISSUE TITLE
New callbacks/events for v3

### ISSUE THREAD

**Issue by lynt-smitka** [orestbida/cookieconsent#342]
Hi,

The new version would be great to have two additional callbacks/events when modal shows and hide:
* onShow
* onHide (not strictly necessary, it is almost the same as a mix of onChange and onFirstConsent)

With these events, you can interact more easily with other popups on the page. You can also use it for statistics on how many users leave without interaction.

**Comment by orestbida** [comment]
I also think they're useful.

**Comment by orestbida** [comment]
The following 2 callbacks/events were added to v3 (will be included in the next release).

* `onModalShow`
* `onModalHide`

Check out the [docs](https://cookieconsent.orestbida.com/advanced/callbacks-events.html#onmodalshow) for details.
