### ISSUE TITLE
Cookie pop up doesn't appear

### ISSUE THREAD

**Issue by RedstonePfalz** [orestbida/cookieconsent#343]
Hello,
the cookie popup does not appear on my page. Here is the code:
https://pastebin.com/xB1GK4JG
Does anyone know what I can do?

**Comment by RedstonePfalz** [comment]
`t`

**Comment by RedstonePfalz** [comment]
`<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8">
<title>Cookies</title>
</head>
<body>
<h1>CONTENT</h1>
<script src="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@master/dist/cookieconsent.js" defer></script>
<script>
    var cc = initCookieConsent();
var cookie = '🍪';
cc.run({
    current_lang : 'de',
    autoclear_cookies : true,
    cookie_name: 'consent',
    theme_css: 'https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@master/dist/cookieconsent.css',
    cookie_expiration : 365,
    page_scripts: true,
    autorun: true,
    gui_options: {
        consent_modal: {
            layout: 'cloud',
            position: 'bottom center',
            transition: 'slide',
            swap_buttons: false
        },
        settings_modal: {
            layout: 'box',
            // position: 'left',
            transition: 'slide'
        }
    },
    onFirstAction: function(){
        console.log('onFirstAction fired');
    },

    onAccept: function (cookie) {
        console.log('onAccept fired ...');
    },
    onChange: function (cookie, changed_preferences) {
        console.log('onChange fired ...');
    },
    languages: {
        de: {
            consent_modal: {
                title: cookie + ' Wir nutzen Cookies! ',
                description: 'Diese Webseite nutzt essentielle Cookies, um den ordnungsgemäßen Betrieb zu gewährleisten und Tracking-Cookies, um herauszufinden, welche Inhalte die Nutzer interessieren. <button type="button" data-cc="c-settings" class="cc-link">Auswählen, welche Cookies genutzt werden</button',
                primary_btn: {
                    text: 'Alle Akzeptieren',
                    role: 'accept_all'
                },
                secondary_btn: {
                    text: 'Einstellungen',
                    role: 'settings'
                }
            },
            settings_modal: {
                title: 'Cookie-Manager',
                save_settings_btn: 'Einstellungen speichern',
                accept_all_btn: 'Alle akzeptieren',
                reject_all_btn: 'Alle ablehnen',
                close_btn_label: 'Schließen',
                blocks: [
                    {
                        title: 'Wofür wir Cookies nutzen',
                        description: 'Wir nutzen Cookies um die Basisfunktionalität der Webseite zu gewährleisten und die Nutzererfahrung zu verbessern. Du kannst selbst entscheiden, welche Kategorien Du akzeptieren möchtest. Mehr Infos, wie wir Cookies verwenden, findest Du in der <a href="#" class="cc-link">Datenschutzerklärung</a>'
                    }, {
                        title: 'Unbedingt notwendige Cookies',
                        description: 'Diese Cookies sind essenziell für den Betrieb und die Funktion dieser Webseite. Ohne diese Cookies wird die Webseite nicht richtig funktionieren.',
                        toggle: {
                            value: 'necessary',
                            enabled: true,
                            readonly: true
                        }
                    }, {
                        title: 'Performance und Analysecookies',
                        description: 'Mit diesen Cookies können wir deine vorherigen Aktivitäten und Auswahlen wie z.B. dein bevorzugtes Theme auf der Seite speichern',
                        toggle: {
                            value: 'analytics',
                            enabled: true,
                            readonly: false
                        },
                    }, {
                    title: 'Werbe und Trackingcookies',
                    description: 'Diese Cookies sammeln Informationen darüber, wie Du diese Webseite nutzt, welche Seiten Du besuchst und auf welche Links Du klickst. Alle Daten sind anonymisiert und können nicht benutzt werden, um Dich zu identifizieren.',
                    toggle: {
                        value: 'targeting',
                        enabled: true,
                        readonly: false
                    }
                    }, {
                        title: 'Weitere Informationen',
                        description: 'Wenn Du weitere Fragen hast oder uns auf Fehler hinweisen möchtest, kannst Du unser <a class="cc-link" href="https://google.com">Kontaktforumlar</a> nutzen.',
                    }
                ], 
            }
        }
    }

});


</script>
<script type="text/plain" data-cookiecategory="analytics">
    console.log('"analytics" category accepted');
</script>
<script type="text/plain" data-cookiecategory="targeting">
    console.log('"ads" category accepted');
</script>
<button type="button" data-cc="c-settings">Show cookie settings</button>

</body></html>`

**Comment by dombyte** [comment]
> Hello,
> 
> the cookie popup does not appear on my page. Here is the code:
> 
> https://pastebin.com/xB1GK4JG
> 
> Does anyone know what I can do?

As I can see it you're missing the cookie_table in your Umbedingt notwendige cookies.
There you need to decline you're consent cookie (cookie name) otherwise the script has no idea that the cookie for the plug-in is a necessity. Look in the demo directory there is everything.

**Comment by dombyte** [comment]
Can you show me your implementation. Otherwise you can copy my version this works. 
Also it's important to use a web server. The script won't work without a web server.

**Comment by RedstonePfalz** [comment]
I use an Apache2 Webserver on a Debian VM.
I copy your version and modify it.
Thanks,

**Comment by dombyte** [comment]
Can you show me your code that you're currently using. The error code says something is not defined. So I guess something is missing.

**Comment by RedstonePfalz** [comment]
https://pastebin.com/MNLtNdgT

**Comment by dombyte** [comment]
I've seen you still use my domain in the cookie table, maybe it works when you switch to your domain. I think I've heard of problems related to this. Otherwise you can try to use a different version of the cookieconsent.js script. I for example use the CookieConsent v3.0.0-beta.1 script and load it locally because of this unclear German privacy laws. The last option could be to copy one of the demo folders and try it out standalone. After it works you can implement it in your page.

**Comment by RedstonePfalz** [comment]
The same error occurs again

**Comment by dombyte** [comment]
Found your error! You forgot to implement the Cookieconsent CSS and for some reason you can't implement the cookie consent-init not via a `<script>.....</script>`.
You need to implement it via `<script src="cookieconsent-init.js" defer></script>>` otherwise an error occurs because it can't define the variable. Try to make a file .js file for the cookieconsent-init.js
Then your original script also works fine. 
Tested on Mac via Safari. Let me know if it works now.

```
<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8">
<title>Cookies</title>
<script src="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@master/dist/cookieconsent.js" defer></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@v2.8.2/dist/cookieconsent.css" media="print" onload="this.media='all'">
  
</head>
<body>
<h1>CONTENT</h1>
<script src="cookieconsent-init.js" defer></script>>

<script type="text/plain" data-cookiecategory="analytics">
    console.log('"analytics" category accepted');
</script>
<script type="text/plain" data-cookiecategory="targeting">
    console.log('"ads" category accepted');
</script>
<button type="button" data-cc="c-settings">Show cookie settings</button>

</body></html>
```


**cookieconsent-init.js**

```
var cc = initCookieConsent();
var cookie = '🍪';
cc.run({
    current_lang : 'de',
    autoclear_cookies : true,
    cookie_name: 'consent',
    theme_css: 'https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@master/dist/cookieconsent.css',
    cookie_expiration : 365,
    page_scripts: true,
    autorun: true,
    gui_options: {
        consent_modal: {
            layout: 'cloud',
            position: 'bottom center',
            transition: 'slide',
            swap_buttons: false
        },
        settings_modal: {
            layout: 'box',
            // position: 'left',
            transition: 'slide'
        }
    },
    onFirstAction: function(){
        console.log('onFirstAction fired');
    },
 
    onAccept: function (cookie) {
        console.log('onAccept fired ...');
    },
    onChange: function (cookie, changed_preferences) {
        console.log('onChange fired ...');
    },
    languages: {
        de: {
            consent_modal: {
                title: cookie + ' Wir nutzen Cookies! ',
                description: 'Diese Webseite nutzt essentielle Cookies, um den ordnungsgemäßen Betrieb zu gewährleisten und Tracking-Cookies, um herauszufinden, welche Inhalte die Nutzer interessieren. <button type="button" data-cc="c-settings" class="cc-link">Auswählen, welche Cookies genutzt werden</button',
                primary_btn: {
                    text: 'Alle Akzeptieren',
                    role: 'accept_all'
                },
                secondary_btn: {
                    text: 'Einstellungen',
                    role: 'settings'
                }
            },
            settings_modal: {
                title: 'Cookie-Manager',
                save_settings_btn: 'Einstellungen speichern',
                accept_all_btn: 'Alle akzeptieren',
                reject_all_btn: 'Alle ablehnen',
                close_btn_label: 'Schließen',
                blocks: [
                    {
                        title: 'Wofür wir Cookies nutzen',
                        description: 'Wir nutzen Cookies um die Basisfunktionalität der Webseite zu gewährleisten und die Nutzererfahrung zu verbessern. Du kannst selbst entscheiden, welche Kategorien Du akzeptieren möchtest. Mehr Infos, wie wir Cookies verwenden, findest Du in der <a href="#" class="cc-link">Datenschutzerklärung</a>'
                    }, {
                        title: 'Unbedingt notwendige Cookies',
                        description: 'Diese Cookies sind essenziell für den Betrieb und die Funktion dieser Webseite. Ohne diese Cookies wird die Webseite nicht richtig funktionieren.',
                        toggle: {
                            value: 'necessary',
                            enabled: true,
                            readonly: true
                        }
                    }, {
                        title: 'Performance und Analysecookies',
                        description: 'Mit diesen Cookies können wir deine vorherigen Aktivitäten und Auswahlen wie z.B. dein bevorzugtes Theme auf der Seite speichern',
                        toggle: {
                            value: 'analytics',
                            enabled: true,
                            readonly: false
                        },
                    }, {
                    title: 'Werbe und Trackingcookies',
                    description: 'Diese Cookies sammeln Informationen darüber, wie Du diese Webseite nutzt, welche Seiten Du besuchst und auf welche Links Du klickst. Alle Daten sind anonymisiert und können nicht benutzt werden, um Dich zu identifizieren.',
                    toggle: {
                        value: 'targeting',
                        enabled: true,
                        readonly: false
                    }
                    }, {
                        title: 'Weitere Informationen',
                        description: 'Wenn Du weitere Fragen hast oder uns auf Fehler hinweisen möchtest, kannst Du unser <a class="cc-link" href="https://google.com">Kontaktforumlar</a> nutzen.',
                    }
                ], 
            }
        }
    }
 
});
 
 
```

**Comment by RedstonePfalz** [comment]
Thanks, it works!
