### ISSUE TITLE
Ability to add a third button on consent_modal

### ISSUE THREAD

**Issue by BigsmileAgency** [orestbida/cookieconsent#352]
Hello,

First, thanks for this awesome plugin!!!!!

After readed this GDPR white paper, for a full gdpr compliant (in Belgium anyway), we need to add a third button on the "consent_modal". Like Settings - Accept all - reject all!
Is there a way to add it or did you already plan this functionnality ?

[https://www.universem.com/blog/gdpr-belgium-white-paper-universem-lexing/](url)

Thanks

**Comment by orestbida** [comment]
Hi @BigsmileAgency,

this has already been implemented in v3, which should be released ~soon. Check out #288 for a preview.

**Comment by BigsmileAgency** [comment]
Hi @orestbida ,

So great!! 
Thanks for this and your reactivity ;)
