### ISSUE TITLE
Script is loaded even though the Service is deactivated

### ISSUE THREAD

**Issue by biceps-George** [orestbida/cookieconsent#353]
Hello,

great work with your plugin so far! I have been enjoying working with it a lot.
However I think I have noticed a bug regarding services and script loading in the Beta Branch.

I have a Category named external which has multiple Services.
Whenever I try to disable for example the Recaptcha Service the script is still being loaded as long as any other service in this category is active.

If the entire category is disabled it works as expected.

`<script src="https://www.google.com/recaptcha/api.js" type="text/plain" data-category="external" data-service="Google Recaptcha"></script>`

**Comment by orestbida** [comment]
Nice catch!

**Comment by orestbida** [comment]
Fixed in 8f231f62c07a76fb0a183cc0f918e6b148045263.
