### ISSUE TITLE
Cookie not deleted if not .domain.com

### ISSUE THREAD

**Issue by jacksoggetto** [orestbida/cookieconsent#356]
I have this code:

{
"col1":"pippo",
"col2":"cookie-consent.local",
"col3":"1 year",
"col4":"description"
}

I have a cookie named pippo, with value 1 and domain cookie-consent.local

When I disable the cookie category doesn't get deleted.

If I change the domain value to .cookie-consent.local then disable the cookie category, it gets deleted, without any problems.

I tried the following combinations, but nothing worked:

{
"col1":"pippo",
"col2":"cookie-consent.local",
"col3":"1 year",
"col4":"description",
"path":"/", // tried with and without path
"domain:"cookie-consent.local" // also tried .cookie-consent.local
}

**Comment by davidsprinz** [comment]
I am experiencing similar problems. The cookie in the analytics category (_fbp, the facebook-Pixel) gets deleted when the user disables/rejects this category, but the cookie in the trailer category (_trailer) doesn't -- and I don't understand why.

`{
	title: 'Werbung und Analytics',
	description: 'Werbe- und Analyse-Cookies',
	toggle: {
		value: 'analytics',
		enabled: false,
		readonly: false
	},
	cookie_table: [
		{
			col1: '_fbp',
			col2: 'kino.test',
			col3: '3 Monate',
			col4: 'Facebook-Pixel',
		}
	]
},
{
	title: 'Trailer',
	description: 'trailer',
	toggle: {
		value: 'trailer',
		enabled: false,
		readonly: false
	},
	cookie_table: [
		{
			col1: '_trailer',
			col2: 'kino.test',
			col3: '3 Monate',
			col4: 'Youtube',
		}
	]
}`

Btw. I had the same problems with the matomo cookies: they won't delete themselves.

Any hints?

**Comment by davidsprinz** [comment]
Well, in my case I just had to deliver the domain with the dot (.kino-test and not kino.test) in the cooke creation script. Now it get's deleted when a user rejects his consent for this category!

**Comment by supporthost-com** [comment]
I found the bug and made a pull request. Now it works with both versions of the domains, domain.it and .domain.it

I'll do some more tests with matomo later

**Comment by jacksoggetto** [comment]
I found the bug and made a pull request. Now it works with both versions of the domains, domain.com and .domain.com

I'll do some more tests with matomo later

**Comment by orestbida** [comment]
@davidsprinz
> Btw. I had the same problems with the matomo cookies: they won't delete themselves.

Services such as GA, Matomo and Facebook Pixel have their own API methods, which you must use in order to stop the tracking and prevent the re-creation of the cookie(s).

You can check this discussion related to Matomo: https://github.com/orestbida/cookieconsent/discussions/279

**Comment by jacksoggetto** [comment]
Kinda, the delete was not working, not it is. I even tried some random cookies, they were only deleted if the domain started with a .

The problem I was referring to wasn't about their API, but that bug that impeded to delete cookies without the dot

I'm happy you accepted my pull request, now it's working, I'm packaging it in a WordPress plugin

**Comment by orestbida** [comment]
@jacksoggetto ,

I was answering to davidsprinz regarding the Matomo issue. It is recommended to invoke their API to properly disable the tracking and cookies, otherwise the cookie is re-created right after being erased. It's a known issue.

The issue you raised was valid and I approved your pr. Thanks a lot for your contribution! Expect a minor revision soon.
