### ISSUE TITLE
force_consent doesn´t work on 3.0.0-rc.4

### ISSUE THREAD

**Issue by kerim80** [orestbida/cookieconsent#363]
Hi, at first great script 👍

The only thing that doesn´t work for me is the force_consent parameter like on your demo page https://orestbida.com/demo-projects/cookieconsent/

Does this have to do with version 3.0.0-rc.4 that I'm using?

**Comment by orestbida** [comment]
Fixed in the [v3.0.0-rc.5 release](https://github.com/orestbida/cookieconsent/releases/tag/v3.0.0-rc.5).
