### ISSUE TITLE
Adding already built Nuxt Module

### ISSUE THREAD

**Issue by raphaelbernhart** [orestbida/cookieconsent#365]
Hi @orestbida, 
I have created a nuxt module for cookieconsent :)
### https://github.com/raphaelbernhart/nuxtjs-cookieconsent

I would love to see the module in the README 😄

If it would help I would also make a PR to do this!
Just waiting on your reply to finish this.

PS: README and other changes for the developer experience (in the module repo) will be added soon.

**Comment by orestbida** [comment]
I don't mind it as long as you place it at the bottom of the Readme!
