### ISSUE TITLE
Use a darker colour for cc-main buttons in default light theme

### ISSUE THREAD

**Issue by mc7244** [orestbida/cookieconsent#366]
This request applies to version 3.0.0-rc4.

A more neutral colour in the default theme (such as black or even the dark blue used in 2.x version) would be much more "portable" than the light blue in my opinion, as it would fit most of the web sites.
The dark theme could benefit the same by using a white or so instead of the same blue.
I know you can CSS-style it, but I think a more neutral default would be better.
Thank you!

**Comment by orestbida** [comment]
Yes, a more neutral color is better!

**Comment by orestbida** [comment]
Implemented in the [v3.0.0-rc.5 release](https://github.com/orestbida/cookieconsent/releases/tag/v3.0.0-rc.5).
