### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by pastinepolenta** [orestbida/cookieconsent#367]
I am facing 2 issues using cookieconsent on IE11

1. The demo site https://orestbida.com/demo-projects/cookieconsent/ seems to have a syntax error (probably just the demo not the library itself)
2. Can you provide some guidance on how to style the component since IE11 does not support css variables?

Thanks

**Comment by orestbida** [comment]
Hi @pastinepolenta,

the simplest solution to IE11 and css variables is to use a polyfill such as [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill).

Alternatively you could use the `postcss-custom-properties` module to create a custom color scheme which would also apply to  IE11 without the need for a polyfill:

0. make sure you have nodejs (LTS) installed
1. clone the repo
2. `npm install`
3. `npm i -D postcss-custom-properties`
4. modify the css variables inside `srs/cookieconsent.css` 
5. `npm run build`

**Comment by pastinepolenta** [comment]
I get the workaround and polyfills but then I would argue that the Key feature `Cross-browser support (IE10+)` is misleading and should be amended or the workaround documented (if you consider styling as part of the support)

**Comment by orestbida** [comment]
I agree. This should be documented and the `Cross-browser support` list item should also have a `*`.
