### ISSUE TITLE
Incompatible cc_cookie between minor versions

### ISSUE THREAD

**Issue by stefanides** [orestbida/cookieconsent#372]
Hi, 

I am using the library to get cookie consents across multiple domains. One is Wordpress, where the version is set manually to v 2.8.0. Another one is managed by npm, which has got recently updated to v. 2.8.5. This introduces the new `cc_cookie` format (see [PR 257](https://github.com/orestbida/cookieconsent/pull/257)), which is not compatible with previous versions - user is then required to confirm cookies on each site separately even the request contains `cc_cookie` with already agreed values from the other site. 

Could this change be backward compatible within minor versions or at least marked as breaking in some release notes?

**Comment by orestbida** [comment]
Hi @stefanides,

this was marked as a breaking change in [v2.8.1](https://github.com/orestbida/cookieconsent/releases/tag/v2.8.1). If I had created a dedicated "Breaking Changes" section it would have probably been much more visible. Also check out https://github.com/orestbida/cookieconsent/issues/349#issuecomment-1195535562.
