### ISSUE TITLE
Setting the "z-index" value

### ISSUE THREAD

**Issue by osworx** [orestbida/cookieconsent#377]
First of all, great plugin.

What I had troubles to implement it into w webshop.
The problem: another (small) popup-window is loaded and is placed over the cookie consent window.
Which has currently an "z-index" of 1000000 (line 935 of 2.8.0 version, 959 of latest version)
`main_container.style.zIndex = "1000000";`

Could a variable be added to the config file to be able to configure this value when needed?

**Comment by orestbida** [comment]
Hi @osworx,

I'd like to to avoid adding new features, especially if we consider that this can be easily achieved via CSS.

A simpler solution would be to simply set the value of the `z-Index` prop. to `2147483647` — the highest accepted value — which should solve the issue.

**Comment by osworx** [comment]
> I'd like to to avoid adding new features, especially if we consider that this can be easily achieved via CSS.
> 
> A simpler solution would be to simply set the value of the `z-Index` prop. to `2147483647` — the highest accepted value — which should solve the issue.

This is how I achieved it with that current implementation.
And finally the simpliest solution.
