### ISSUE TITLE
CSS problem with RTL

### ISSUE THREAD

**Issue by pinkasey** [orestbida/cookieconsent#388]
This is what the plugin looks like with `direction: rtl;` in the body:
![image](https://user-images.githubusercontent.com/1780369/193817139-6b5c17d3-4986-4098-888a-773102b82b0e.png)

For reference, here it is with `direction: ltr;`
![image](https://user-images.githubusercontent.com/1780369/193817270-4d6d135e-ca2c-4ad2-a887-0ffe9e6afa93.png)

(I'm opening this issue after opening the exact same issue on https://github.com/68publishers/cookie-consent/issues/42)
(I might open a PR to fix this, but I'm not sure when)

**Comment by orestbida** [comment]
Hi @pinkasey,

v2 is now in maintenance mode and will receive bugfixes or minor tweaks*. If this can be achieved in few lines of css, sure go ahead. 

If I were you, I'd switch to [v3](https://github.com/orestbida/cookieconsent/tree/v3.0-beta). I've already planned on adding full support for RTL languages.

\*: I might consider features/options with a tiny implementation

**Comment by pinkasey** [comment]
Thanks for the reply.
I currently don't need RTL support, so I don't think I'd invest time in this, I came across this bug by chance.
Also,
I'm a user of [68publishers/cookie-consent](https://github.com/68publishers/cookie-consent), which follows v3, I believe.

I'll revisit this if I have a need for RTL.
Thanks again.

**Comment by orestbida** [comment]
I see. 

Currently they're based on cookieconsent v2. They might switch to v3 once it's officially released.

**Comment by orestbida** [comment]
[v3.0.0-rc.9](https://github.com/orestbida/cookieconsent/releases/tag/v3.0.0-rc.9) has full support for RTL. You can also see it in action in the [playground](https://playground.cookieconsent.orestbida.com/).
