### ISSUE TITLE
Reject All option?

### ISSUE THREAD

**Issue by neromaki** [orestbida/cookieconsent#39]
Hello,
I'm looking to implement this, but am legally required to have a "Dismiss All" button on the banner alongside "Accept All", though I can't see any config options for dismissing all at once - is there a way to do this?

**Comment by orestbida** [comment]
Hi @neromaki,

there's alredy `accept_necessary` role which acts as "reject all":

```javascript
...
secondary_btn: {
    text : 'Reject all',
    role : 'accept_necessary'   //'settings' or 'accept_necessary'
}
...
```

for it to be a "true reject all", you must have no categories marked as "necessary/requried", in other words, you need to make sure all toggles have the `readonly` property set to `false`

```javascript
...
toggle : {
    value : 'my_category',
    enabled : false,
    readonly: false
}
...
```

**Comment by neromaki** [comment]
Ah that works fantastically, thanks so much!
