### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'replaceChild')

### ISSUE THREAD

**Issue by thomsondevelopment** [orestbida/cookieconsent#390]
Hi, 
i am using this library in my NUXT 3 project and after build i get this error:

Uncaught TypeError: Cannot read properties of null (reading 'replaceChild')
    at o (VM16907 cookieconsent.js:7:13763)
    at a.readyState.a.onload (VM16907 cookieconsent.js:7:13739)

Can you help me please ?

**Comment by thomsondevelopment** [comment]
@orestbida  problem still continues

**Comment by orestbida** [comment]
Please provide a minimal demo with the issue, so that I can inspect the code. You could use StackBlitz, CodeSandbox or a Github repo.
