### ISSUE TITLE
Uncaught TypeError: CookieConsent.init is not a function

### ISSUE THREAD

**Issue by gyurmey2** [orestbida/cookieconsent#395]
Hi,
with using [this demo](https://github.com/orestbida/cookieconsent/tree/master/demo/demo_basic) and the latest Beta version (3.0.0-rc.7) I get an error as in the topic. Can it be fixed?

Regards!

**Comment by orestbida** [comment]
Hi @gyurmey2,

there are 2 major versions of cookieconsent — v2 and v3 — and they are substantially different. If you want to check out a demo configuration for v3, please refer to the [v3.0-beta](https://github.com/orestbida/cookieconsent/tree/v3.0-beta/demo) branch.

You could also check out the live (work in progress) [playground for v3](https://playground.cookieconsent.orestbida.com/).

**Comment by gyurmey2** [comment]
@orestbida thank you very much.
I made changes, but now I get `CookieConsent is not defined` error, but only when I try to [compile](https://jsbin.com/hadugoguha/edit?js). There is no problem with v2.8.8.

**Comment by orestbida** [comment]
Mhm, there's a warning saying that `import` is not available, probably related to jsbin. I'd recommend to use Stackblitz for a live demo.

There are a few live demos that you can inspec on [Stackblitz](https://stackblitz.com/@orestbida) and [CodeSandbox](https://codesandbox.io/u/orestbida)

**Comment by gyurmey2** [comment]
Yes, I know, It was just a sample code snippet for inspection. The problem, however, remains.

**Comment by orestbida** [comment]
I cannot tell what the issue is unless you provide a full demo with the problem (a react, laravel, vue, vite ... app); There is nothing wrong with the jsbin snippet itself.

**Comment by gyurmey2** [comment]
Thank you. Examples below:
[Without import.](https://stackblitz.com/edit/web-platform-nsklzz?file=index.html)
[With import.](https://stackblitz.com/edit/js-yagndr?file=index.html)

**Comment by orestbida** [comment]
Found the issue!

If you want to use `import` in a script, you must specify `type="module`:
```html
<script type="module" src="index.js"></script>
```

In the import statement, you can either import the whole plugin:
```javascript
import * as CookieConsent from 'vanilla-cookieconsent';
```

or some specific API methods only:
```javascript
import { run } from 'vanilla-cookieconsent';

run({...});
```

you must use the same name as the one you specified in the import, in this case it's `CookieConsent`:
```javascript
import * as CookieConsent from 'vanilla-cookieconsent';

CookieConsent.run({...});
```

**Comment by gyurmey2** [comment]
It works! Thanks a lot.

**Comment by dngraphisme** [comment]
> 

Hello @orestbida ,

I updated the library with v3 (especially for lenis) and the import is no longer correct.

The problem now is that I end up with a JS error: Uncaught (in promise) TypeError: can't convert undefined to object

Here is my old code:

`import * as CookieConsent from 'vanilla-cookieconsent';
export const cookie = {
    init: function () {
        //const CookieConsent = initCookieConsent();
        CookieConsent.run({
            current_lang: 'fr',
            autoclear_cookies: true,
            page_scripts: true,
            languages: {

            },
            gui_options: {
           
            },
            onModalReady: ({modalName, modal}) => {
                if(modalName === 'preferencesModal'){
                    console.log('hello')
                    $('#s-bl').attr('data-lenis-prevent', '')
                    //modal.querySelector('.s-bl').setAttribute('data-lenis-prevent', '');
                }
            }
        });

        return CookieConsent;

    },
}
export default cookie;`

I don't see where the problem is, can you help me ? Thanks in advance, nicolas

**Comment by orestbida** [comment]
@dngraphisme,

you need to provide a valid config. object with at least the following 2 properties: `language`, `categories`. This is mentioned in the [Getting Started](https://cookieconsent.orestbida.com/essential/getting-started.html#configuration) page.
