### ISSUE TITLE
css class `disable--interaction` remains on <html> tag after close (v3)

### ISSUE THREAD

**Issue by meixger** [orestbida/cookieconsent#396]
Shouldn't the class `disable--interaction` also be removed in the [hide() function](https://github.com/orestbida/cookieconsent/blob/9ca66bd152850f4062d58cc5659367017e761c50/src/core/api.js#L404)?

**Comment by orestbida** [comment]
Although it shouldn't cause issues, we can remove it for a cleaner state.

**Comment by orestbida** [comment]
included in [v3.0.0-rc.9](https://github.com/orestbida/cookieconsent/releases/tag/v3.0.0-rc.9)
