### ISSUE TITLE
How to properly add an event?

### ISSUE THREAD

**Issue by gyurmey2** [orestbida/cookieconsent#397]
Hi,
I am adding the code below but it generates errors.
```
// Allow Cookie Preferences scrolling
  onModalShow: function () { 
    document.querySelector(".pm__body").addEventListener("wheel", (e) => {
      e.stopPropagation();
    });
  },
 ```
Pen: https://codepen.io/gyurmey2/pen/NWMErqQ

What am I doing wrong?

**Comment by orestbida** [comment]
You are trying to add an `eventListener` every time one of the modals is visible. The `preferencesModal` does not exist, until it's just about to be visible.

You should use the [`onModalReady` callback](https://cookieconsent.orestbida.com/reference/configuration-reference.html#onmodalready) — which is fired only once, when a modal is generated and appended to the dom:
```javascript
CookieConsent.run({
  
    onModalReady: ({modalName, modal}) => {
        if(modalName === 'preferencesModal') {
            modal.querySelector('.pm__body').addEventListener('wheel', (e) => {
                e.stopPropagation();
            }, {passive: true});
        }
    }

});
```

**Comment by gyurmey2** [comment]
Thank you. This works fine when I click a red button ([Manage preferences](https://codepen.io/gyurmey2/pen/NWMErqQ)), but it doesn't work when I directly click a button in a modal window (Manage preferences). Is there any conflict?

**Comment by orestbida** [comment]
Oh, I see the issue. The best solution would be for the `leni` plugin to implement an “exclusions list” option, to avoid adding `scroll`, `wheel` and `mousewheel` event listeners everywhere.

In the meantime, here is a “hack” which should work:

```javascript
function stopPropagation(e){
    console.log("stop propagation")	
    e.stopPropagation();
}

function stopScroll(modalName, stop){
    if(modalName === 'preferencesModal'){
        
        const eventAction = stop === true 
            ? 'addEventListener'
            : 'removeEventListener';

        document.querySelector('.pm__body')[eventAction](
            'wheel', 
            stopPropagation, 
            { passive: true }
        );
    }
}

CookieConsent.run({
    onModalShow: ({modalName}) => {
        stopScroll(modalName, true);
    },
    
    onModalHide: ({modalName}) => {
        stopScroll(modalName, false);
    }
});

**Comment by gyurmey2** [comment]
You are amazing. Thanks again.

**Comment by orestbida** [comment]
@gyurmey2, with `lenis 0.2.17` this is now simplified to:

```javascript
CookieConsent.run({
    onModalReady: ({modalName, modal}) => {
        if(modalName === 'preferencesModal'){
            modal.querySelector('.cm__body').setAttribute('data-lenis-prevent', '');
        }
    }
});
```

Note: I'd recommend to use an explicit version of `lenis` rather than `latest`, to avoid potential breaking changes. Also, as of now, the `latest` published version on `jsdelivr` is not updated.

**Comment by gyurmey2** [comment]
@orestbida Thanks for the tips. The `lenis` has been updated but the [same problem](https://github.com/orestbida/cookieconsent/issues/397#issuecomment-1287085641) has returned.

**Comment by orestbida** [comment]
Pretty sure it's a cdn issue, rather than lenis'; it works on my end. Make sure to specify the `0.2.17` version on the cdn url, instead of `latest`.

**Comment by gyurmey2** [comment]
Yes, I'm sure: https://codepen.io/gyurmey2/pen/NWMErqQ

**Comment by orestbida** [comment]
Just did some more testing, and can confirm this is caused by an unhandled mouse hover event (v3)  which causes the preferences modal to be recreated every time (any custom attribute is removed).

**Comment by gyurmey2** [comment]
Fantastic! Now it is working.
