### ISSUE TITLE
Enhancement: move ccb_cookies_table th to language file 

### ISSUE THREAD

**Issue by adelmazza** [orestbida/cookieconsent#4]
All the table header field names of  ccb_cookies_table are currently hardcoded on cookieconsent.js
As an enhacement request, plese move the TH to the language file.

Name | Domain | Description | Expiration | Type

Thanks a lot!

**Comment by orestbida** [comment]
yea, sure, update should arrive ~ by saturday.

**Comment by orestbida** [comment]
update is up. You can now define custom table headers by using the `ccb_table_headers` prop as:

```javascript
ccb_table_headers : [
    {th1: "Name"}, 
    {th2: "Domain"}, 
    {th3: "Expiration"}
],
```
where `th1`, `th2`, ... are now used as keys for `ccb_cookies_table`(th1, th2 are not keywords, you can choose whatever you want, just make sure they match the keys used in ccb_cookies_table) :
```javascript
ccb_cookies_table: [
    {
        th1: 'darkmode',
        th2: 'orestbida.com',
        th3: 'One week after the cookie has been created',
    }
]
```

From now on the `ccb_table_headers` is **required**, should you create tables.
Check the full example config for a better idea [Example config](https://github.com/orestbida/cookieconsent#user-content-full_example)
