### ISSUE TITLE
data-service toggle error

### ISSUE THREAD

**Issue by flowereight** [orestbida/cookieconsent#401]
Hi to everybody, 
When I define a s JS scripts with "data-service" within a given "data-category" I have the following problem.

If I click on "accept all" from the main screen of the site, the JS of the category are put up but not those of the service.  If instead I click on "customize" and then on "accept all", in the modal that opens, then it works correctly.

**Comment by orestbida** [comment]
Hi @flowereight,
I cannot reproduce the issue. Can you provide a demo that I can inspect (on Stackblitz, CodeSandbox ...)?

**Comment by flowereight** [comment]
I found that the error is present with v3.0.0-rc.6. By installing v3.0.0-rc.8 everything works fine. Thank you.
