### ISSUE TITLE
How can you create a top right X to close?

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#407]
The demo page looks real nice, and I especially like the top right X to close and reject all, or to click outside the dialog to have the same effect. This is especially useful for foreign language users. Unfortunately I couldn't find the options to enable these. Did I miss it?

**Comment by orestbida** [comment]
There's a small note in the docs. under the `consentModal` configuration section.: [consentModal options](https://cookieconsent.orestbida.com/reference/configuration-reference.html#translation-consentmodalrequired)

You need to specify a valid `closeIconLabel` field for the button to be created.

**Comment by wzol** [comment]
It seems to work, thank you :)

**Comment by wzol** [comment]
As I saw in v3 the top right X for the consent dialog will be available for necessary only. 👍  Is it possible for now to use only necessary when clicking on the overlay in force_consent mode? It might work with an event bind, I'm just not sure how.

**Comment by orestbida** [comment]
In order to make this work, you need to add a `click` event listener to the `.cm-wrapper` element. Since the html markup is generated asynchronously, you'll have to rely on the `onModalReady` event/callback to detect when the modal is generated.

This should work:
```javascript
CookieConsent.run({
    // ...
    
    onModalReady: ({modalName, modal}) => {
        if(modalName === 'consentModal'){
            modal.parentElement.addEventListener('click', () => {
                CookieConsent.acceptCategory([]);
                CookieConsent.hide();
            });
        }
    }
});
```

**Comment by wzol** [comment]
Hm, I doesn't seem to do anything. When the modal appears I can't find `.cm-wrapper` or `consentModal` elements. Is it the div `id="cm"` ?

**Comment by orestbida** [comment]
Yeah, just tried that and it doesn't work properly. This should handle all cases:

```javascript
CookieConsent.run({
    onModalReady: ({ modalName, modal }) => {
        if (modalName === 'consentModal') {
            modal.parentElement.addEventListener('click', (event) => {
                if (
                    CookieConsent.getConfig('disablePageInteraction') &&
                    !modal.contains(event.target)
                ) {
                    CookieConsent.acceptCategory([]);
                    CookieConsent.hide();
                }
            });
        }
    }
});
```

[Demo on Stackblitz](https://stackblitz.com/edit/web-platform-hkzb2g?file=index.js%3AL30)

**Comment by orestbida** [comment]
Oh, in that case it should be way simpler. Something like this:

```javascript
cc.run({...});

const overlay = document.getElementById('cm-ov');

overlay && overlay.addEventListener('click', () => {
    cc.accept([]);
    cc.hide();
});
```

**Comment by wzol** [comment]
Oh, that works great! Thank you! 😃
