### ISSUE TITLE
Best way to handle v3 beta breaking changes?

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#408]
There are some awesome changes already in v3 beta, so I'd like to use it, but as I see it gets breaking changes. I understand it is a beta, but how can I use it, so new beaking changes won't give an error or result an unexpected behaviour.

**Comment by orestbida** [comment]
Although the branch is called "beta", v3 is stable as of now and pretty much done feature wise. With that being said, I can't guarantee that there won't be any new breaking changes until the official release.

If you decide to use a release candidate, then I'd highly recommend to read the changelog before updating to a newer version.

**Comment by wzol** [comment]
Will do, and you are doing an awesome job! 👍
