### ISSUE TITLE
after saving settings user cannot revoke them

### ISSUE THREAD

**Issue by javismiles** [orestbida/cookieconsent#41]
congrats for a wonderful repo, thank you,
question, when user clicks in settings, and changes some settings and clicks on "save settings", the popup disappears and never reappears again. So how is the user supposed to revoke or change again those settings? there should be a way to do that,
thank you :)

**Comment by orestbida** [comment]
Hi @javismiles,

you can achieve this by creating a `button` or `a` tag with the following attribute `data-cc="c-settings"`:

```html
<button type="button" data-cc="c-settings">Cookie Preferences</button>
```

Alternatively you can also show the modal via javascript using the `.showSettings()` method.

**Comment by javismiles** [comment]
great help, thank you very much :)
