### ISSUE TITLE
Demo iFrameManager Checkbox doesn't toggle

### ISSUE THREAD

**Issue by edgarhuber** [orestbida/cookieconsent#411]
In the iFrameManager Demo of Version 3 Beta the checkboxes for iFrame Services do not toggle, when I click the "Don't ask again" button.

I implemented YouTube and Google Maps as a data-category instead of a data-service in preferencesModal (en.json) and the index.html. But I think, this doesn't play a role on the checkbox' beahviour. When YouTube and Google Maps are integrated as services the checkboxes don't toggle, too.

Example: https://edgarunger.com/cc3beta/demo/demo_iframemanager2/index.html

![Screenshot 2022-11-02 171331](https://user-images.githubusercontent.com/116775302/199542899-2689b43b-9440-4bb0-b374-4749662841ce.png)

![Screenshot 2022-11-02 171416](https://user-images.githubusercontent.com/116775302/199542913-c3ab55a6-c735-44a9-9fcb-847e955decc6.png)

**Comment by edgarhuber** [comment]
Thank you, Orest. Do services actually have to be in a category? I'd like to show each of them on the same hierarchy level as for example Google Analytics and not include them in a category.

**Comment by orestbida** [comment]
If that's the desired and intentional result, then it's all good. It was simply unusual seeing services configured as categories.

**Comment by orestbida** [comment]
Closing this issue. You can check [iframemanager/#28](https://github.com/orestbida/iframemanager/issues/28) for updates.

**Comment by mr-manuel** [comment]
> Hi @edgarhuber,
> 
> IframeManager is still in its first release and there is no way to connect its buttons' actions to CookieConsent. For now you'll have to use custom code to do this, as shown in this [demo on CodeSandbox](https://codesandbox.io/s/cookieconsent-v3-iframemanager-22z79d?file=/index.js:1730-2413).
> 
> Note: I'd recommend to configure youtube and google maps embeds as [services](https://cookieconsent.orestbida.com/reference/configuration-reference.html#category-services) rather than categories.

Unfortunately this is not working anymore with 3.0.0-rc.11. Would it be possible that you update the code?
