### ISSUE TITLE
Is there a forced order for data-cookiecategory?

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#412]
What I'm thinking is:

`<script type="text/plain" data-cookiecategory="cat1">myVariable=1;</script>`
and
`<script type="text/plain" data-cookiecategory="cat2">myVariable=2;</script>`

And if both `cat1` and `cat2` accepted can I be sure that myVariable will have a 2 value?

**Comment by orestbida** [comment]
Scripts are enabled in sequence so this should work.

**Comment by wzol** [comment]
Great, thank you!

**Comment by orestbida** [comment]
Anytime!
