### ISSUE TITLE
Informative Text instead of Disabled Toogle

### ISSUE THREAD

**Issue by petekyetke** [orestbida/cookieconsent#415]
Our hotjar recordings shows that many users try to click read only (stricly necessary category) toogle button.

Is it possible instead of a disabled toogle button to add a text like "Allways on"? 

![example](https://user-images.githubusercontent.com/117347299/200755397-72e832aa-3549-4cbd-a78a-96080b1abbd1.jpg)

**Comment by osworx** [comment]
Well that would make sence - if they are necessary ..

**But, what are necessary cookies?**
From my point of development (after nearly 30 years) I do not know really any one!

**Comment by tillsanders** [comment]
> But, what are necessary cookies?

I think most websites use it for trivial things like language/region selection to not bother people unnecessarily. Or for auth mechanisms. Of course none of them are strictly necessary, but it makes sense to not have your users disable them accidentally because it will actually lead to them having a bad experience.

**Comment by osworx** [comment]
@tillsanders It was an **ironic** question ..
I know what many thinks, storing stupid cookies about language, currency, session, etc. as **required**.
And that in the moment each and every website visitor opens that website - does no matter if just for looking or later buying (e.g. webstores as I develop for such).

Normally all these stupid cookies should not be requried and not be set - as long as the visitor decides to stay longer and visit (or buy) other sites of the same domain.

From the point of the normal visitor it makes sense to show "alway On" - if really set!

**Comment by orestbida** [comment]
@petekyetke you cannot remove the toggle — unless custom css/js is used —  but you can add a "badge" via an html element with the `pm__badge` class, as showcased in the [playground](https://playground.cookieconsent.orestbida.com/) page.

```javascript
{
    title: `
        Strictly necessary cookies
        <span class="pm__badge">Always On</span>
    `,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscin ...',
    linkedCategory: 'necessary'
}
```

**Comment by tillsanders** [comment]
> It was an **ironic** question ..

I see, well. I found that irony and sarcasm are sometimes difficult in international communication, especially text-only. You might want to make it more clear using emojis.

**Comment by osworx** [comment]
> > It was an **ironic** question ..
> 
> I see, well. I found that irony and sarcasm are sometimes difficult in international communication, especially text-only. You might want to make it more clear using emojis.

I hate these icons, called emojis.
Better to write what I think and mean.

So, what I have written is both ..

**Comment by petekyetke** [comment]
Thanks @orestbida. This will do the job!

**Comment by osworx** [comment]
Just - because it effects also my work - another solution (via css):
![grafik](https://user-images.githubusercontent.com/1905204/201081325-f54a8a28-fe24-4b3f-a4ee-763c689f7b9b.png)

Doing so, will not show any toggle - users might get not confused this way?
What do you think - reasonable?

**Comment by petekyetke** [comment]
@osworx I think it looks great. Also when you remove add class="pm__badge" it shows text with same font with category title. 

May I ask what change did you make on CSS to achieve this?

**Comment by osworx** [comment]
> @osworx I think it looks great. Also when you remove add class="pm__badge" it shows text with same font with category title.
> 
> May I ask what change did you make on CSS to achieve this?

Well, I just played a bit around .. 
https://playground.cookieconsent.orestbida.com/

And made this:

At the first label 
```css
label class="section__toggle-wrapper"
```

I added 
```css 
display:none
```

and at the first span
```css
span class="pm__badge"
```

I added 
```css
margin-right: -55px;
```

I was only curious just to see if possible.
Of course, if there would be a setting for this, the script could do it automatically ..

**Comment by petekyetke** [comment]
@osworx thanks, I will try it out.

**Comment by osworx** [comment]
Here a short snippet to get the result you want.

```js
let textOn = 'Always active';
let userLang = navigator.language || navigator.browserLanguage || navigator.systemLanguage || navigator.userLanguage || null, userLanguage = lang ? lang.substr(0, 2) : null;
let elm2 = document.getElementsByClassName('b-tg');

// add here optional other language strings
if(userLang === 'de') {
    textOn = 'Immer aktiv';
}
if(typeof elm2 !== undefined && elm2 !== null) {
    elm2[0].style = 'width:120px';
    elm2[0].innerHTML = textOn;
}
```

I have placed it at the bottom of the init script.
Maybe someone can need it ..
