### ISSUE TITLE
Problem with saving cookies

### ISSUE THREAD

**Issue by JiriBandura** [orestbida/cookieconsent#416]
Hi,
some of our clients report a bug, that when they accept/decline a modal and make a refresh, the modal windows reappears.
The only solution is that they have to wipe their cookies hard and only then everything works correctly for them.

Do anybody knows, where can be a problem?

**Comment by orestbida** [comment]
Hi @JiriBandura,

* Which version are you currently using? 
* What was your previous version (if any)? 
* Can you point me to a demo that I can inspect?

**Comment by mrschick** [comment]
I just ran into an issue that might be related to the above.

With version 2.8.5 and 2.8.8, changing the consent `cookie_name:` from the standard `"cc_cookie"` to `"consent"` or `"ob_consent"` (I only tried these) causes any consent option other than `accept_all` to save a consent cookie with no value.
In other words, the consent cookie holds an empty string, causing the code to discard it and prompt the form again.

**Comment by mrschick** [comment]
@orestbida Steps to repro:
* open `demo/demo_basic/cookieconsent-init.js`;
* modify either of the `col1` attributes in `cookie_table` to have the same value as `cookie_name`, i.e: `cc_cookie_demo1`;
* when testing, `accept_necessary` will cause an empty `cc_cookie_demo1` cookie to be saved, leading to the cookie consent form being prompted again after reloading the page;

**Comment by orestbida** [comment]
@mrschick placing the plugin's cookie in the analytics category is wrong. The autoclear function erases all (listed) cookies under the rejected categories. You should list the plugin's cookie in the "necessary" category.

**Comment by mrschick** [comment]
Ah, understood.
Then I only ran into this "issue" because my website runs analytics by default (but bound by `data-cookiecategory="analytics"`) unless a specific opt-out cookie is set, so I initially thought of mentioning the cc-cookie as the one enabling analytics if it contains the "analytics" category. I later reverted to simply not mentioning any specific analytics cookie.

Thanks for clearing that behavior up, this project is awesome 👍

**Comment by YourItalianChef** [comment]
> Hi, some of our clients report a bug, that when they accept/decline a modal and make a refresh, the modal windows reappears. The only solution is that they have to wipe their cookies hard and only then everything works correctly for them.
> 
> Do anybody knows, where can be a problem?

i had the same problem, after the change of this attribute  from `cookie_domain: 'static descrp'` to `cookie_domain: window.location.host `, it starts to work correctly
