### ISSUE TITLE
Documentation for v.3 ?

### ISSUE THREAD

**Issue by osworx** [orestbida/cookieconsent#417]
@orestbida Unfortunetaly the current docs are describing only the settings for v.2.x
https://github.com/orestbida/cookieconsent#installation--usage

Will be there some for the new v.3 release?
I want to start a new project with the new version instead using the older ..

thx!

**Comment by orestbida** [comment]
The documentation for v3 is available [here](https://cookieconsent.orestbida.com/essential/introduction.html).

**Comment by osworx** [comment]
> The documentation for v3 is available [here](https://cookieconsent.orestbida.com/essential/introduction.html).

many thanks!
