### ISSUE TITLE
Custom/individual configuration possible?

### ISSUE THREAD

**Issue by osworx** [orestbida/cookieconsent#418]
Using the current solution (does no matter if v.2 or v.3) requieres a "hard coded" init file.
That seems to be fine for people knowing what to do.

But what, if I want to embed your solution into a CMS (or other framework).
The user should have the possibility to define simply the settings as he want/need via the backend of the website administration defining the developed options and texts (per language) over the existing GUI

Currently I do not see an way doing so - except developing a solution which will override the current used **cookieconsent-ini.js** on the fly.

Is there a plan to allow and start further your solution with any external script which will override the standard config settings?

Thx in advance in pointing me into the right direction ..

**Comment by orestbida** [comment]
v3 supports both inline and [external translation files](https://cookieconsent.orestbida.com/advanced/language-configuration.html#external-translations), unlike v2.

**Comment by osworx** [comment]
@orestbida Tat what I have already "dicovered" ;)
But if I (or in this case the client/customer) want(s) to define his own settings (for eaxmple v.2):
```
layout: 'box',
position: 'bottom right',
```

he must edit the js-file directly and must have knowledge of javascript.
A "no go" for the majority of users. So they should be able to use an internal solution (of course delevoped for this CMS/Webshop/etc.) simply by selecting and defining what he wants.

And your script should be able to get this "custom" configuration and override the default values "on the fly".

Have I described it correct and easy to understand?

**Comment by orestbida** [comment]
The points you raised are covered in the [introduction section](https://cookieconsent.orestbida.com/essential/introduction.html#is-cookieconsent-the-right-tool-for-you). 

The plugin was never meant to be a "quick-install" solution and does not provide a GUI based configuration tool, unlike most mainstream solutions. It is specifically designed for users who have at least a basic understanding of javascript, are willing to invest a bit of their time and would like to have full control over their scripts. It's just a generic, neutral, empty shell with no default configuration: no languages and no pre-configured services.

A GUI based configurator would be nice, but I don't see one being developed it in the near future.

This is the safest route for me (as a dev). Having no dependencies or default configurations means that there is — relatively — little maintenance.

**Comment by osworx** [comment]
Well, as a dev I understand you completely and agree fully.
The basics are here, they are very good - many thanks again for your work and passion.

Nevermind, I will develop a GUI for that framework I am mainly working - so that website owners can easely adopt the settings they need/want.
Including javascript and css variables - important is only, that the config settings for the main script are accessable public.

**Comment by orestbida** [comment]
Yeah, sorry!
