### ISSUE TITLE
CookieConsent in a VUE component

### ISSUE THREAD

**Issue by SumentsJavi** [orestbida/cookieconsent#42]
Hi,
Is there any documentation to get this plugin up and running on a VUE component?

**Comment by orestbida** [comment]
Hi @SumentsJavi,
unfortunately there is no public documentation for vue (or react). Heck there isn't even an npm package yet. 

I'm not a vue expert but you should be able to use this in your vue app by simply **initializing the plugin inside vue's own [mounted](https://v3.vuejs.org/api/options-lifecycle-hooks.html#mounted)** hook to make sure that the DOM exists before the plugin tries to append the modal to the body. 

Something like this:

```javascript
mounted() {
  const cc = window.initCookieConsent();

  cc.run({
        current_lang : 'en',
        theme_css : '<path-to-cookieconsent.css>',
        ...
  });
}
```

as for how to load the plugin, you could load it using plain javascript, before initialization:
```javascript
mounted() {
  const script = document.createElement('script');
  script.src = "<path-to-cookieconsent.js>";
  script.type = "application/javascript";
  document.head.appendChild(script);
 
  const cc = window.initCookieConsent();
  ...
}
```

Probably there's a better way to load external javascript in vue?

**Comment by tillsanders** [comment]
I published the library on the NPM Registry (`vanilla-cookieconsent`, more [here](https://github.com/orestbida/cookieconsent/issues/38#issuecomment-899382867)) and added it to my Nuxt 2 installation as a client-only plugin:

```typescript
// plugins/cookieconsent.client.ts
import { Plugin } from '@nuxt/types'
import 'vanilla-cookieconsent/dist/cookieconsent.css'
import 'vanilla-cookieconsent/src/cookieconsent.js'

const cookieConsentPlugin: Plugin = () => {
  // @ts-ignore
  const cookieConsent = window.initCookieConsent()
  cookieConsent.run({/* ... */})
}

export default cookieConsentPlugin
```

```javascript
// nuxt.config.js
export default {
  plugins: [
    { src: '~/plugins/cookieconsent.client.ts' },
  ],
}
```

Works like a charm so far!

**Comment by SumentsJavi** [comment]
Awesome! I'll follow up this.

**Comment by costafrancesco94** [comment]
Would be really nice if we could integrate some of the Vue layout features to add more styling to the banner/modal and eventually inject other buttons/texts and features using vue slots...

The same could be achieved for react/angular counterpart if there are

**Comment by Loosie94** [comment]
> I wrapped this as a Vue plugin and published to NPM: https://www.npmjs.com/package/vue-cookieconsent
> 
> Just do `npm i vue-cookieconsent` and set up as follows:
> 
> ```js
> // main.[js|ts]
> import CookieConsent from 'vue-cookieconsent'
> 
> const consentOptions = { /* your config */ }
> 
> const app = createApp(App)
>   .use(CookieConsent, consentOptions)
>   .use(router)
> ```
> 
> A Cookieconsent instance is now globally available via `this.$cc` in your Vue components, providing the full library API. To react on consent changes (and to hook into the lib's callback functions), there's an additional `on` method on `$cc`:
> 
> ```js
> export default defineComponent({
>     name: 'Foo',
>     beforeCreate () {
>         this.$cc.on('consent-changed', () => {
>             console.log('cookie consent changed, new user preferences:', 
>                 this.$cc.getUserPreferences())
>             // your business logic..
>         })
>     }
> })
> ```

I followed your steps, but the consent is not visible?
I get the console log with my config but not the consent itself. The data-cc button to show the modal also doesn't seem to work..

**Comment by Vitomir2** [comment]
> 

Are there any updates for vue2-cookieconsent @eyecatchup ?

**Comment by JavascriptMick** [comment]
Works as a Nuxt3 plugin with some rearrangement 
Note, no messing about with nuxt.config.ts required.
https://gist.github.com/JavascriptMick/3fc3af09dd66691c25dd3e815fa1b499

**Comment by YusufTezel** [comment]
I spent an hour looking for a good way to add cookie consent to my Nuxt 3 project and found a helpful example here: https://stackblitz.com/edit/nuxt-starter-l5k2ny?file=app.vue. Also, the solution from @JavascriptMick is pretty good too.
