### ISSUE TITLE
How use this library in Nuxt 2

### ISSUE THREAD

**Issue by YourItalianChef** [orestbida/cookieconsent#420]
Hey,
i want to describe how to use this library in nuxt 2.

Step 1:
npm i vanilla-cookieconsent

Step 2: 
create config file JS into folder of plugins => YourNameOfFile.js
```
YOUR CONFIG
const CookiesConsent = window.initCookieConsent()

CookiesConsent.run({})

```
Step 3:
config nuxt.config.js add text below

```
css: [
'./node_modules/vanilla-cookieconsent/dist/cookieconsent.css'
]

plugins: [
{ src: './node_modules/vanilla-cookieconsent/dist/cookieconsent.js', mode: 'client' },
{ src: './plugins/YourNameOfFile.js', mode: 'client' }
]
```

Step 4:
make a cup of coffee and enjoy

**Comment by orestbida** [comment]
There's also a guide for nuxt2 here: https://github.com/orestbida/cookieconsent/issues/42#issuecomment-899387614.
