### ISSUE TITLE
DNT - respect or not?

### ISSUE THREAD

**Issue by osworx** [orestbida/cookieconsent#421]
Read all comments here, and checked the code also.

**DNT = Do Not Track** (as all of you know a setting per user) is implemented by some (or many / all ?) browsers.
Not per default - unfortunetaly.

So my question is: can DNT be respected?
I know the Opt-In and Opt-Out discussions - nearly each Country or Continent has one of that.
But (!!) when I as user enables DNT, I really do not want to be tracked!
And more, I do NOT want to be asked for that to give my consent .. or when Opt-Out is allowed it should NOT be enabled (per default), that should be then a Opt-In option.

So, does CookieConsent take care of DNT?
Or are there any plans to add such to the configuration and could be defined therefore by the website owner?

**Comment by orestbida** [comment]
Sadly [DNT is already deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack).

I don't want to sound harsh, but if you really value the privacy of your users you might as well remove all tracking scripts. Alternatively you could switch to a GDPR compliant analytics solution such as:

* [Plausible](https://plausible.io/) 
* [Fathom Analytics](https://usefathom.com/)
* [Simple Analytics](https://www.simpleanalytics.com/)

Although these tools are neither free nor nearly as powerful as ga/gtm, they are built with privacy in mind and do not require a consent notice AFAIK.

**Comment by osworx** [comment]
Thanks for the extended answer.
And you do not sound "harsh", it is as it is - I like clear words and comments rather "this, that, ..."

Now we have clarified this, I personally respect all of the privacy and maybe one of those web developers who welcome the GDPR/DGSVO and other regulations.
It's time to stop the marketing industry and their endless hunger for data!

I am not dependent from them, displaying no ads or something else.
Do not collect any visitor data (expect those server id doing it automatically.
Never used GA or similiar tools, do like Google (Bing also not) - when searching I use other tools.

But I am developing plugins and extensions for clients.
They have websites build on CMS, having webshops selling products.
And they often use tools like GA.

When Matomo started as Piwik (many years ago), I tried it to see what it can do.
Because it's part of my job to know the possibilties the users might have.

Now we have to live with all that marketing excess, many website owners want to use tools to check how their websites are used. And many of them use GA  - while at least they have no glue what this tool is really is!

And here comes your script, which will be part of one of my modules.

Sadly that DNT is stopped, guess a result of the marketing industry.
And these days, every website owner has to display what his cookies are doing (if used, and they are used on nearly 99% of all websites).
That's one of the reasons to use tool s like yours, because if the regulation authorities do not change their current rules, we - the website owners - have to inform.

Next reason is, some websites (or more than some) are using then GA (and other).
Then they have to ask for consent - which is good!
Current tools are made to confuse visitors, are complicated and mostly of them are violating the GDPR!
Users tend then to accept every and all, because they want to visit the website.

So, that we have clarified the basics you may know now why I am asking.
I as developer can do nearly everything, but the users of my scripts should have an easy to understand and operating UI based tool where they can define their individual settings.

Your tool gives me the basics, all around has to be developed.
Which also means, your settings and definitions should be public available, should be able to override (if needed).

Explained enough?
