### ISSUE TITLE
[FEATURE Load external language files automatically

### ISSUE THREAD

**Issue by osworx** [orestbida/cookieconsent#422]
Referring to this page: https://cookieconsent.orestbida.com/advanced/language-configuration.html

As far as I can see that, languages have to be defined manual.
But, could it be made to load all defined language files automatically by the script - so nobody must "fiddle around" with the init script?

For example: the backend of the sued system generates x language files (in json format of course).
Assume we have en, it, de, fr
Now the script scan this subfolder and add them automatically.
If a new language is added, this new file is also (the translations) added.
Same goes for when a language file is deleted - that language is not valid anymore.

Guess that could be a nice feature.

**Comment by orestbida** [comment]
Unfortunately this is not possible since javascript does not have access to the file system (for security reasons).

The scan must be done server side, afterwards you can pass all the defined languages to the frontend.

**Comment by osworx** [comment]
Okay, many thx.
If I would be better in javascript, I should know this also - but you can learn every day 👍 

But what I have seen (after playing around now with v3), could the path for language files be one lower than the base and init scripts.

Say: 

- cookieconsent
- - cookieconsent.css
- - cookieconsent.umd.js
- - cookieconsent-ini.js
- - - language
- - - - en.json
- - - - de.json

Means then, the path is fixed, and the possible configuration errors (mispelling the path) can be avoided.

**Comment by Realme121** [comment]
Why are you asking me for help with my device info and making illegal changes to my personal identifiable information??

1

**Comment by orestbida** [comment]
Mhm, I'm not sure I understand what the issue is. 

You can specify any path for the translation files:
```
en: './en.json'
it: '../assets/translations/it.json'
```

**Comment by osworx** [comment]
Okay, I do it through the management console the user will have in his CMS.
