### ISSUE TITLE
Showing from scratch let button inactive

### ISSUE THREAD

**Issue by Javarome** [orestbida/cookieconsent#424]
Scenario:
1. `cc.run()` with doc sample config. "accept all"/"decline all" buttons work fine + "let me choose" works fine, probably because `cc.run()` called `_addDataButtonListeners()`
2. reload the page. The popup doesn't show up because cookies were accepted. 
   1. Calling `cc.show(0, false)`  doesn't show the popup
   2. Calling `cc.show(0, true)`  show the popup,  "accept all"/"decline all" buttons work fine but **"let me choose" does nothing**

Could this be because `_addDataButtonListeners()` is not called in the case of `show()` but only in case of `.run` or language change ?

**Comment by orestbida** [comment]
Hi @Javarome, it's definitely a bug!

`_addDataButtonListeners()` should be called inside `_createConsentModal()`.

**Comment by orestbida** [comment]
Should be fixed in [v2.8.9](https://github.com/orestbida/cookieconsent/releases/tag/v2.8.9).

**Comment by Javarome** [comment]
Fixed indeed 2.8.9, thanks!
