### ISSUE TITLE
Cannot read properties of undefined (reading 'setAttribute')

### ISSUE THREAD

**Issue by YourItalianChef** [orestbida/cookieconsent#425]
Hi,
i work with Nuxt 2, and use your library like plugins,
but when i call window.initCookieConsent().showSettings() / window.initCookieConsent().showSettings(0)
the settings is opened with error
Cannot read properties of undefined (reading 'setAttribute')

anybody know how fix it?

**Comment by orestbida** [comment]
Make sure you're calling `initCookieConsent()` only once in your app.

If you want to access the plugin from any component, you have to share the object returned from `initCookieConsent()` as shown in this [demo](https://codesandbox.io/s/cookieconsent-v2-nuxt-2-f1wnkr?file=/plugins/CookieConsentPlugin.client.js).

**Comment by YourItalianChef** [comment]
you are awesome, how i can pay your coffee?

**Comment by orestbida** [comment]
Puoi fare una donazione su [ko-fi](https://ko-fi.com/orestbida)!

**Comment by YourItalianChef** [comment]
fatto, grazie
