### ISSUE TITLE
Having a hard time understanding where some cookies are coming from and how script loading works

### ISSUE THREAD

**Issue by sunscreem** [orestbida/cookieconsent#428]
This is 2 noob questions. 

1. My client has around 40 cookies being set on their site. It's obvious some are from GTM and Facebook, but, for example, I think Cloudflare are setting one for bot detection when I'm loading fonts from fonts.com. I feel like I'm no understand how to find out what these cookies are being used for. Is it a case of visiting every companies docs and working it out? 

2. I'm struggling to understand why we need to block scripts. My understanding is that is just so on initial load we don't load certain scripts until the user has expressed a preference about, say, tracking cookies which might be set in those scripts. If they later change their mind about that, and change their preference, there's not really anything we can do at that point as the scripts were already loaded. Is my understanding correct?

**Comment by orestbida** [comment]
Hi @sunscreem,

1. You could use [Open-Cookie-Database](https://github.com/jkwakman/Open-Cookie-Database)/`open-cookie-database.csv` to figure out what each cookie does, assuming you can find it in the list.

2. If you configure the plugin properly, then you'll also be able to reject a specific category (e.g. analytics) in any moment. Cookies — relative to the category that was just disabled — will be cleared by the plugin. As for the already executed scripts, it's not always easy to stop them; It depends on whether the script (service) provides specific API to stop its own tracking (e.g. GTM) or not (e.g. microsoft clarity). These scripts however will no longer load on subsequent page loads, hence tracking will be disabled. If you want the tracking scripts to stop immediately, you can configure the plugin to reload the page after the cookies have been cleared.

**Comment by sunscreem** [comment]
@orestbida Not only an excellent plug-in but also fantastic and clear responses to my questions. Thank you so much! Super helpful.
