### ISSUE TITLE
A way to invalidate consent from the site

### ISSUE THREAD

**Issue by onesoftdk** [orestbida/cookieconsent#43]
Thanks for all the great work.

It would be nice to make sure that site users are prompted to renew their consent if the site settings change.

E.g. if I have set up my site with 
`{"level": ["necessary","preferences"]}`
and users have accepted that, and then I add "statistics".

Currently, I have to wait until the user's cookies time out (default six months) before I can start tracking "statistics" for users with old cc_cookies,

if the configuration is extended with an extra parameter:

Option | Type | Default | Description
-------- | ------ | --------| -------------
revision | string | null | The current revision of the cookie consent, if updated existing users will be prompt to renew their consense

The the cookie is extended with the accepted revision
`{"level": ["necessary","preferences"], "revision": "first"}`

and if the current revision doesn't fit with users cookie revision, they need to approve again

**Comment by orestbida** [comment]
Hi @onesoftdk,

a simpler approach to this would be to just **rename the cookie** (by default it's "cc_cookie") to something else. Users which had given consent, prior to your policy changes, would be asked once again to accept the cookie.

you can change the cookie name by simply specifying a valid **cookie_name** option inside the `.run()` method, example:

```javascript
cc.run({
  ...
  cookie_name : "new_cc_cookie",
  ...
});
```

**Comment by onesoftdk** [comment]
Hi @orestbida 

that was also my first thought, but then I was like: how will I get rid of the old cookie?

but I'll go with it, for now, thanks for your answer
