### ISSUE TITLE
[FEATURE] Translate service labels (v3)

### ISSUE THREAD

**Issue by mengelmann** [orestbida/cookieconsent#433]
Hi,

Thank you for great work, @orestbida!

I'm testing **version 3** and would like to be able to translate service labels located in 

```
{
    [service: string]: {
        label?: string,
        onAccept?: () => void,
        onReject?: () => void
    }
}
```

https://cookieconsent.orestbida.com/reference/configuration-reference.html#category-services

It looks like these labels are split from the rest of the translation part and put into the more "technical" part of the script (with callbacks, cookie names). It makes it difficult to translate them.

My ideas:
- (cleaner solution) Move service labels to `language.translations` https://cookieconsent.orestbida.com/reference/configuration-reference.html#language-translations-required as a sibling to `consentModa`l and `preferencesModal`.
- Allow adding translations in `[category].[services].label`

I think it's still a good time to change config structure, as v3 is still in beta.

**Comment by orestbida** [comment]
Hi @mengelmann,

I agree that it would be a nice addition, but it's very likely not going to be worked on. I see service names as unique, proper nouns which shouldn't be adapted/translated.

I'm quite strict on potential feature/enhancements and have said no to many other proposals, for the sake of a more lightweight plugin.
