### ISSUE TITLE
Can't use CookieConsent.acceptService() when cookie settings have not been defined

### ISSUE THREAD

**Issue by Striffly** [orestbida/cookieconsent#434]
#### What's wrong?

When using `CookieConsent.acceptService('all', 'category_name')` after a div click, when the cookie settings have not been defined (first loading of the site, no click on the popup), I got this error : 
```text
Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at eval (cookieconsent.esm.js:29:14231)
    at ae (cookieconsent.esm.js:29:14280)
    at Module.ce (cookieconsent.esm.js:29:16409)
    at App.onClick (App.js:89:58)
```

#### Possible solutions

- Set cookie datas when using this function when they don't already exists => hide consent modal on page reload
- Show preferences modal with option focused ( and seleted ?) => this requires additional functionality, such as a callback to know if the service has been activated or not and continue the code execution
- Handle error
- Other solution ?

#### Temporary workarounds

```javascript
if (!CookieConsent.validConsent()) {
  CookieConsent.showPreferences();
  return;
}
CookieConsent.acceptService('all', 'category_name');
```

```javascript
// On page reload, consent modal will be hidden even if cookie settings have not been defined
CookieConsent.showPreferences();
CookieConsent.hidePreferences();
CookieConsent.acceptService('all', 'category_name');
```

**Comment by orestbida** [comment]
Thanks for reporting this,  it will be fixed in the next release!

**Comment by mr-manuel** [comment]
I have the same issue with `CookieConsent.acceptCategory()` and `CookieConsent.acceptService()` when the cookie is not already set (`CookieConsent.validConsent() == false`) and the functions are called.

It would be great, if both accept functions create a valid consent, if there is none.

**Comment by orestbida** [comment]
Should be fixed in rc.12!
