### ISSUE TITLE
[Suggestion] autoReload when service / category is disabled

### ISSUE THREAD

**Issue by Striffly** [orestbida/cookieconsent#438]
Hello

First of all thanks for this plugin, your work and this upcoming v3 😁

#### What's wrong?

Disabling a service in many cases implies the need to disable a running script. An efficient solution for this is to reload the page: this is possible through `[category].autoClear.reloadPage` property, or `[service].onReject()` method.<br>
However, it is necessary in this case to include this reload on each new service and/or category, which is not always easy to do (case of dynamically created configurations), and leads to a lot of duplicated code.

#### Feature suggestion

Add a global `reloadOnDisable` property, which reloads the page if a consent is withdrawn after being initially accepted.

#### Temporary workarounds
- Add `[category].autoClear.reloadPage` to all categories, or a window reload in every `[service].onReject()` method.
- Detect removes services / categories in `onChange()` hook.
- 
 ```javascript
  onConsent({cookie}) {
    window.cookies_consent = CookieConsent.getUserPreferences();
  },

  onChange: ({cookie, changedCategories, changedPreferences}) => {
    const userPreferences = CookieConsent.getUserPreferences();

    userPreferences.rejectedCategories.forEach((category) => {
      if (!window.cookies_consent.rejectedCategories.includes(category)) window.location.reload();
    });

    for (const [key, services] of Object.entries(userPreferences.rejectedServices)) {
      services.forEach((service) => {
        if (!window.cookies_consent.rejectedServices[key].includes(service)) window.location.reload();
      });
    }

    window.cookies_consent = userPreferences;
  },
```

**Comment by orestbida** [comment]
Hi @Striffly,

I'd rather implement such option inside each service, for a more granular/flexible control.

I highly discourage calling `location.reload()` inside a service, since it may prevent other code from running, due to the page being reloaded too soon. The safest option is to do this inside the `onChange` callback, since it is last in the "execution chain".

Here is a (slightly) simpler way to achieve the same behavior (not tested):
```javascript
onChange({changedCategories, changedServices, cookie}) {
    const { categories, services } = cookie;

    for(const category in changedServices){

        if(changedCategories.includes(category))
            !categories.includes(category) && location.reload();

        for(const service of changedServices[category])
            !services[category].includes(service) && location.reload();
    }
}
```

**Comment by Striffly** [comment]
This solution works very well, thanks !<br>
I was looking here for finding `onChange` parameters, but `changedServices` was missing (hence the solution I proposed) : https://cookieconsent.orestbida.com/reference/configuration-reference.html#onchange
But I should have looked here instead : https://cookieconsent.orestbida.com/advanced/callbacks-events.html#onchange
