### ISSUE TITLE
[Bug / Suggestion] Better auto-detection of document language

### ISSUE THREAD

**Issue by Striffly** [orestbida/cookieconsent#439]
Hi,

Currently, the langage value retrieved from the body lang attribute is not truncated if no other is available.
Example : if there is "fr" translated fields in CookieConsent configuration, and the body lang attribute is "fr-FR", default language will be used.

Is it possible to truncate the value of body lang attribute if no related translation is available in CookieConsent configuration ? Then check if a configuration exists for this truncated value.

**Comment by orestbida** [comment]
Mhm, the value is always truncated though.

https://github.com/orestbida/cookieconsent/blob/d33d2c1cd6668ec8c67f22c699183202af12c8f8/src/cookieconsent.js#L1291
https://github.com/orestbida/cookieconsent/blob/2db756f11fdddb19b0b75847a4f084564055362a/src/utils/language.js#L43

**Comment by fbatschi** [comment]
its truncating the language attribute when `autodetect: 'browser',` is used,  but not for detection of the documents language via `autodetect: 'document',` at least not in v3.

https://github.com/orestbida/cookieconsent/blob/4d0e62cf3d590737c35c53955966136501ade213/src/utils/language.js#L53
