### ISSUE TITLE
Matomo

### ISSUE THREAD

**Issue by sakis-tech** [orestbida/cookieconsent#442]
Hello, I use Matomo and don't know how to link it to the cookieconsent. Can someone help me with an example or something else?

**Comment by orestbida** [comment]
Hi @sakis-tech,

you need to use [matomo's api](https://developer.matomo.org/guides/tracking-consent). You can find an example in https://github.com/orestbida/cookieconsent/discussions/279.

**Comment by tailwindtom** [comment]
Hello @sakis-tech - in most cases you dont need consent for matomo, as you can host it locally. I added it as a necessary cookie, working in germany.

**Comment by sakis-tech** [comment]
> Hi @sakis-tech,
> 
> you need to use [matomo's api](https://developer.matomo.org/guides/tracking-consent). You can find an example in #279.

Thank you @orestbida  for the tip. That helped me.

I have still one question. Is there a way to combine the Matomo cookies "`_pk_id.*`" , "`_pk_ses.*`" and "`mtm_consent_removed`" in a custom cookie such as "`matomo_cookies`"?

**Comment by orestbida** [comment]
@sakis-tech unless there is a config. option offered by Matomo to do so, I don't think it's possible.

There is however an option to [disable all matomo's cookies](https://matomo.org/faq/general/faq_157/#:~:text=Log%20in%20to%20your%20WordPress,and%20press%20%E2%80%9CSave%20changes%E2%80%9D.), but it impacts the analytics' data accuracy.

**Comment by sakis-tech** [comment]
I understand, all right. then the issue is closed for me. Thank you for the great support.

**Comment by sakis-tech** [comment]
I have now switched to V3 and unfortunately do not know how to integrate Matomo there. Can you help me with that?

Many Thanks.

**Comment by orestbida** [comment]
The easiest way is via [script tags](https://cookieconsent.orestbida.com/advanced/manage-scripts.html):
```html
<script type="text/plain" data-category="analytics">
 _paq.push(['setConsentGiven']);
</script>

<script type="text/plain" data-category="!analytics">
 _paq.push(['forgetConsentGiven']);
</script>
```
or you could configure it the same way as in v2.
```javascript
cc.run({
    onConsent: () => {
        if(cc.acceptedCategory('analytics')) {
            _paq.push(['setConsentGiven']);
        }
    },
    
    onChange: () => {
        if(!cc.acceptedCategory('analytics')) {
            _paq.push(['forgetConsentGiven']);
        }
    },
});
```
Note: `cc` is a shorthand for `CookieConsent`.

**Comment by tailwindtom** [comment]
Hello @sakis-tech - did you add the cookie consent as a plugin? I would recommend to add all scripts (cookieconsent, google tag and so on) as a plugin. 

My configuration with Nuxt 3: 

Install via npm vanilla-cookieconsent

/plugins/cookieconsent.js
```
import 'vanilla-cookieconsent';

const config = {
    current_lang: document.documentElement.getAttribute('lang'),
    autoclear_cookies: true, // default: false
    page_scripts: true, // default: false
....
...

export default ({ app, store }, inject) => {
    inject('cookieconsent', () => {
        // obtain plugin
        var cc = initCookieConsent()

        // run plugin with your configuration
        cc.run(config);
    })
  }

```

in the nuxt config you can add it like this: 
` plugins: [
      '~/plugins/cookieconsent.js'
    ]`

finally, you can add it to your mounted functions in app.vue: 

`mounted() {
            window.addEventListener("scroll", this.handleScroll);
            document.documentElement.classList.add('dark')
            this.$cookieconsent()
            
        },`

**Comment by sakis-tech** [comment]
thanks everyone, i made it with the script tag and it works.
