### ISSUE TITLE
I cannot get the consent dialog to pop up on my website when browsing on iPhone

### ISSUE THREAD

**Issue by Devacor** [orestbida/cookieconsent#443]
Website with the consent dialog in place: https://snapjaw.net/testing

It shows up properly on desktop, but not at all on iPhone in Chrome or on Safari.

**Comment by Devacor** [comment]
Perhaps it’s hidden behind the nav bar at the bottom. I’ll play with the css!
![DE236742-8A76-444D-B67B-4DBD85172B46](https://user-images.githubusercontent.com/923621/206811877-fef9fbc6-8a54-4942-8de7-e2b708e524e2.jpeg)

**Comment by orestbida** [comment]
There are 2 version of your website:

1. https://snapjaw.net/
2. https://snapjaw.net/testing/

The plugin is installed only in the `/testing/` path, that's (probably) why you don't see it at all.

**Comment by Devacor** [comment]
The title bar in the screenshot is confusing, but I was on the correct
site, that’s just how chrome on iPhone simplifies the view. I triple
checked. :)

**Comment by Devacor** [comment]
It does work on Android

**Comment by orestbida** [comment]
Perhaps your iphone has a cached version of the website. Did you try incognito mode? You could also try to clear the browser's data.

**Comment by Devacor** [comment]
Yes, I just verified in incognito mode with out luck.

**Comment by Devacor** [comment]
Take a look at this, likely the same issue: https://snapjaw.net/testing/testlayout.php

View that on a browser, and then on iPhone it's completely hidden.

https://stackoverflow.com/questions/57510797/ios-ui-hides-the-bottom-of-the-page-how-do-i-make-the-whole-page-responsive-and

**Comment by orestbida** [comment]
Can you view the "settings modal" correctly?

> View that on a browser, and then on iPhone it's completely hidden.

Yea, that is very likely the case.

**Comment by Devacor** [comment]
If you click the second link in this page it should pop that consent settings modal up (and does so on desktop) but actually this is also not working on iOS. Perhaps I have a hidden javascript issue causing errors. I need to figure out how to open up a dev console on iPhone similar to PC to see what's going on. Other javascript elements on this site work, however, like the "account" button.

https://dragonstorage/snapjaw/cookies.php

**Comment by Devacor** [comment]
Indeed it seems to be a javascript error within cookieconsent.js

![image](https://user-images.githubusercontent.com/923621/206820931-8163b81c-05a7-4f6e-9e6a-5d600728d5a7.png)

Then, additionally, in my own init.js script it seems like initCookieConsent() is not valid at the time it gets evaluated.

![image](https://user-images.githubusercontent.com/923621/206820968-898d46b3-9a3b-4316-a920-dd661f0f247f.png)

This may be because on iPhone the defer is not happening sequentially, but on a completely separate thread and it isn't sequencing the two behaviors. So perhaps I need to manually load the two in a more intentional order. This is probably worth noting in your examples though.

![image](https://user-images.githubusercontent.com/923621/206821028-eaf530f0-81ae-41ae-abb2-0c806e07d0fe.png)

Note: This is debugging with Safari on iOS, not Chrome which also exhibits a similar problem, possibly fixing Safari will fix both.

**Comment by Devacor** [comment]
This same issue affects Safari on my MacBook running Mojave (possibly and likely other versions of OSX as well)

**Comment by orestbida** [comment]
I highly doubt defer is the issue. If it was, then millions of other websites would be broken on ios ... 

Removing (or fixing) the `clear_all_cookies` function should fix everything, unless there is something else broken.

**Comment by Devacor** [comment]
Yeah actually, I added that myself Q_Q sorry about that. Let me fix that. I threw that in there out of convenience and it wasn't causing any issues on my other devices so I forgot I had.

**Comment by orestbida** [comment]
Glad you found the culprit! I also learned something new, win-win.
