### ISSUE TITLE
Modal not being shown using  versions above 2.8.0

### ISSUE THREAD

**Issue by filak** [orestbida/cookieconsent#447]
After upgrading from 2.7.2 to 2.8.9 no modal has been showing. I have gradually downgraded and the last working version seems to be 2.8.0.

The log for 2.8.1+ looks OK:

```
CookieConsent [CONFIG]: received_config_settings ...
auto_language: "browser"
autoclear_cookies: true
cookie_expiration: 182
cookie_name: "xx_cc_cookie"
cookie_necessary_only_expiration: 7
current_lang: "cs"
hide_from_bots: true
languages: {cs: {…}, en: {…}}
mode: "opt-out"
onAccept: ƒ (cookie)
onChange: ƒ (cookie, changed_categories)
onFirstAction: ƒ (user_preferences, cookie)
page_scripts: true
revision: 105
theme_css: "/assets/cookies/cookieconsent.css?ver=2.8.1"
...
cookieconsent.js?ver=2.8.9:1244 CookieConsent [LANG]: auto_language strategy is 'browser'  
cookieconsent.js?ver=2.8.9:1244 CookieConsent [LANG]: detected_browser_lang = 'cs'  
cookieconsent.js?ver=2.8.9:1244 CookieConsent [CONFIG] mode='opt-out', default enabled categories: 
(2) ['necessary', 'analytics']
cookieconsent.js?ver=2.8.9:1244 CookieConsent [NOTICE]: ask for consent!  
cookieconsent.js?ver=2.8.9:1244 CookieConsent [MODAL]: show consent_modal 
```

But no modal is being shown.

Thank you for awsome plugin !

**Comment by filak** [comment]
Sorry, I have closed this unintentionally.

**Comment by orestbida** [comment]
Hi @filak,

there are 2 breaking changes in [v2.8.1](https://github.com/orestbida/cookieconsent/releases/tag/v2.8.1).

* the `theme_css` option was removed so you'll need to load the `.css` file the usual via: `<link rel...>`
* the cookie's field `level` was renamed (by accident, this change was meant only for cookieconsent v3) to `categories`

If you are upgrading to cookieconsent v2.8.1+, I'd highly recommend to reset consent for all your users to avoid potential issues. You can do this by either chaning the cookie name or by increasing the `revision` number.

**Comment by filak** [comment]
Thank you!
