### ISSUE TITLE
[Feat]: Hiding the cookie banner on the privacy page.

### ISSUE THREAD

**Issue by RobertFess** [orestbida/cookieconsent#458]
### Description

Before deciding, the user may want to go to the privacy page and read through everything. For this, the banner on this page must be disabled without activating a cookie that is not required. If the user switches back to another page, the banner becomes active again and the user must choose.

### Proposed solution

You could identify the privacy page by the URL (URL slug must be predefined or can be specified individually in the settings). Alternatively, identification via a page ID would be possible. For this, the privacy page must receive an ID in the body or in the root, via which the banner recognizes the page.

**Comment by orestbida** [comment]
Hi @RobertFess,

unfortunately this won't be worked on, sorry! 

The plugin is already much heavier than I ever imagined it to become and I'm quite strict about new features. I don't see myself using this feature as I'd like to have analytics data enabled on all pages, including the privacy/cookie policy page.

**Comment by RobertFess** [comment]
@orestbida , I understand. Thanks for your answer and explanation. You have created a great plugin from my point of view.
