### ISSUE TITLE
Suggestion: add a callback for Rejected cookies

### ISSUE THREAD

**Issue by PINHOf** [orestbida/cookieconsent#46]
I couldn't find any callback to handle people who press "Reject cookies". Solved it temporarily by attaching the click event to the rejected button created in the DOM.

```
$(document).on('click', '#c-s-bn', function()
{
	document.cookie = "cc_cookie=;expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=[put-your-domain-here]";
	window.location.href = 'https://google.com';		
});
```

**Comment by orestbida** [comment]
Hi @PINHOf,

**both reject and accept buttons** will trigger the same `onAccept` method. The reject action is treated as a special case of the accept action (though, with no categories accepted).

You can check if the user has rejected the cookieconsent inside the `onAccept` method by accessing the parameter (which in this example I called it `preferences`) passed to the onAccept function like so:

```javascript
...
onAccept: function(preferences){

    console.log("User accepted the following cookie categories:", preferences.level);
    
    // Check if user rejected ALL services
    if(preferences.level.length === 0){
	console.log("User rejected all categories");
    }
},
...
```

Or this way, in case you have some categories marked as necessary/always enabled (those are the categories with `readonly: true`):

```javascript
...
onAccept: function(preferences){

    console.log("User accepted the following cookie categories:", preferences.level);
    
    // Method 2
    const necessary_categories = ['necessary'];
    
    // Check if user rejected all categories except those marked as necessary ( categories with readonly: true)
    if(preferences.level.every( elem => necessary_categories.includes(elem))){
        console.log("User rejected all categories except those marked as necessary");
    }
},
...
```

Also note that in your example you are manually overwriting the content of the default cookie `cc_cookie`, with your own content which can cause issues.

**Comment by PINHOf** [comment]
> Also note that in your example you are manually overwriting the content of the default cookie `cc_cookie`, with your own content which can cause issues.
I'm not overwritting, I'm deleting the cookie.

Your sample seems the correct approach, thanks.
