### ISSUE TITLE
[Feat]: Three buttons (since "Settings, Accept All" is technically not legal)

### ISSUE THREAD

**Issue by uuf6429** [orestbida/cookieconsent#460]
### Description

This plugin is not exactly legal (by default) because of two reasons:
1. "decline" and "accept" buttons should both be displayed/considered as primary buttons:
    https://noyb.eu/en/more-cookie-banners-go-second-wave-complaints-underway
3. it's not allowed to only have "settings" and "accept", and since right now decline is the same as settings, this can't be done:
    https://noyb.eu/en/226-complaints-lodged-against-deceptive-cookie-banners

### Proposed solution

For maximum flexibility, I'd refactor buttons into an array of `{label /*text*/, role /* the click action */, style /* primary, secondary, link..*/  }`objects (then "swap_buttons" could also be removed).

**Comment by orestbida** [comment]
Hi @uuf6429, 

there are no default settings, what you are seeing are example configurations. You can still create a "3 button layout" by placing one of the buttons (the "settings" button) in the description field.

The above described layout (accept + reject button with the same weight/color + settings button below them) can be easily achieved in [v3](https://github.com/orestbida/cookieconsent/tree/v3.0-beta) which you can see in the [playground](https://playground.cookieconsent.orestbida.com/).

**Comment by uuf6429** [comment]
Hey, so I switched to the new version and followed the documentation - it looks very good so far and seems to work very well! 🎉 

Only one really minor thing: the playground implies that some the library comes with some builtin translations, but when I looked into it (read the docs and checked the code), it seems this is only implemented in the playground as a demo? Not a problem for me, but maybe it might make sense to explain this better in the playground?

**Comment by orestbida** [comment]
Currently the playground is a work-in-progress, I might add something similar to the [Introduction section](https://cookieconsent.orestbida.com/essential/introduction.html) in the next update.

> ie. rewording it into "Demo Languages" or similar.

Yes!
