### ISSUE TITLE
Consent Logging - script load issues for ga.push event

### ISSUE THREAD

**Issue by ssdoe** [orestbida/cookieconsent#461]
Hello,

Trying to log all consent (accepted, reject and necessary) to google analytics for the marketing dept to measure a campaign they are implementing, using the consent logging approach you've outline in you guide.

The issue coming up with is, when rejecting consent, the event trigger is not firing because there is no to analytics scripts loaded at that point, below is the event to GA. 

```
ga.push(
  [
    "event",
    "Consent: " + preferences.accept_type,
    "Accepted: " + preferences.accepted_categories +
    " Rejected: " + preferences.rejected_categories
  ]
);
```

So, question is. how can the push event above be done, tried to follow the suggestions made here https://github.com/orestbida/cookieconsent/issues/290#issuecomment-1097007054 but none worked as hoped.

Thanks & Regards
ssdoe

**Comment by orestbida** [comment]
Hi @ssdoe,

I don't think this can be done without tracking the user. Generally speaking, consent records are stored in a database.

**Comment by ssdoe** [comment]
Hi @orestbida 

Thanks for getting back. Yes, figured that would case, was hoping to by pass and database fetch post stuff.

Regards
ssdoe
