### ISSUE TITLE
[Bug]: Switching a category doesn't seem to affect services when they are all enabled

### ISSUE THREAD

**Issue by uuf6429** [orestbida/cookieconsent#463]
### Expected Behavior

When a category is manually switched off, it is expected that all (in the category) services are also switched off.

### Current Behavior

It looks like it works (the services switches are turned off), but after saving, nothing changes except the state of the category switch changes.

### Steps to reproduce

1. Open the demo here: https://stackblitz.com/edit/web-platform-ahqgz3?file=index.js
2. Dismiss the cookie consent modal
3. Open the preferences modal and enable "Analytics Cookies" and all of its services, and Save
4. Open the modal again and switch off "Analytics Cookies" without changing anything else - note how the service switches are also disabled - save again
5. Open the modal again and notice how the service switches are now enabled again, but the category one is not (and the iframes have not be declined)

### Proposed fix or additional info.

I feel like this is a bug and not intentional. If it is actually intentional, then I suggest not to automatically disable all the services switches if by saving it won't actually do anything.

### Version

3.0.0-rc.12

### What browsers are you seeing the problem on?

Chrome

**Comment by orestbida** [comment]
Yup. Can confirm its a bug, and it has already been fixed in the v3 branch!

**Comment by uuf6429** [comment]
Hey, I don't want to cause any pressure, but we'd like to use this plugin with that bug fixed, so it would be great to have the fix released soon, or at least maybe a release date estimate (just so I can plan ahead). 🙏 

Also, thanks again for the very fast fix and support!

**Comment by orestbida** [comment]
The release will be published either this evening or tomorrow!
