### ISSUE TITLE
[Bug v3.0.0-rc.13]: autoClear.cookies not deleting cookies

### ISSUE THREAD

**Issue by ArnoMoqo** [orestbida/cookieconsent#465]
### Expected Behavior

When opting out of the 'analytics' group some cookies should be cleared according to the documentations. Using the following code should delete de **_gid** & cookies staging with **_ga**. Tis is not happening.

`
        categories: {
            necessary: {
                readOnly: true,
                enabled: true
            },
            analytics: {
                autoClear: {
                    cookies: [
                        {
                            name: /^(_ga)/
                        },
                        {
                            name: '_gid'
                        }
                    ]
                }
            }
        },
`

### Current Behavior

When opting out, no cookies are deleted.

### Steps to reproduce

Use the steps in de documentation. opt-out of some group, and see the problem.

### Version

v3.0.0-rc.13

### On which browser do you see the issue?

Chrome

**Comment by orestbida** [comment]
Hi @ArnoMoqo,

services such as [Google Analytics will re-set the cookie](https://cookieconsent.orestbida.com/additional/troubleshooting.html#some-cookies-are-not-deleted), #249.

You can find a [demo with GTM here](https://github.com/orestbida/cookieconsent/tree/v3.0-beta/demo/demo_gtm).
