### ISSUE TITLE
[Bug]: Allow not setting the domain at all

### ISSUE THREAD

**Issue by timiwahalahti** [orestbida/cookieconsent#468]
### Expected Behavior

Setting of the cookie should be allowed without the domain at all. Leading dot appended to domain can cause issues with external systems, if the site is on `domain.tld`, if the external system reads all cookies because the cookie does get set for `.domain.tld`

### Current Behavior

If `cookie_domain` setting is `domain.tld` and site is on `domain.tld` without any subdomains, the cookie is set as `.domain.tld` because clients do always append the dot to domains. https://stackoverflow.com/a/20884869

### Steps to reproduce

1. host site on `domain.tld` without any subdomain
2. set `cookie_domain` to `domain.tld`
3. cookie gets set with `.domain.tld`
4. spin up another site/system on some subdomain
5. cc cookie is available

### Proposed fix or additional info.

Made a quick hotfix

```
// assures cookie works with localhost (=> don't specify domain if on localhost)
if(window.location.hostname.indexOf(".") > -1 && window.location.hostname !== _config.cookie_domain ){
```

Currently using version 2.8.5 but by the looks of the code, same is happening with newer versions.

### Version

2.8.5

### On which browser do you see the issue?

Firefox

**Comment by orestbida** [comment]
Looks life a safe change to me, a PR is welcome!
