### ISSUE TITLE
[Docs]: Extension of the live demo with allowedCategory()

### ISSUE THREAD

**Issue by jirsbek** [orestbida/cookieconsent#473]
### What is the improvement/update you wish to see?

Would be possible to extend the live demo on stackblitz with allowedCategory() and other methods? I can't figure out, how to use this method in onFirstAction callback in React app.

### Link the related docs page, if it exists.

https://stackblitz.com/edit/nextjs-euxk9k
https://github.com/orestbida/cookieconsent#faq

**Comment by orestbida** [comment]
Hi @jirsbek,

in those 2 examples you can use `window.CookieConsentApi.<method_name>`;

Updated the [stackblitz demo](https://stackblitz.com/edit/nextjs-euxk9k?file=components%2FCookieConsentConfig.js);

**Comment by jirsbek** [comment]
Love it, @orestbida, thank you!
