### ISSUE TITLE
[Bug]: (v3) Duplicate id in <th> if multiple sections have cookieTable with same columns

### ISSUE THREAD

**Issue by EreMaijala** [orestbida/cookieconsent#483]
### Expected Behavior

Table headers should have unique id attributes (or no id unless necessary)

### Current Behavior

All th elements in the cookieTable get the id attribute from the header value (which could also make it invalid as an id) (see https://github.com/orestbida/cookieconsent/blob/v3.0-beta/src/core/modals/preferencesModal.js#L343). When there are more than one section with a table that has same header values, the id's get duplicated.

### Steps to reproduce

1. Use the included playground
2. Duplicate Analytics Cookies section with a new title
3. Open the Preferences window
4. Observe duplicate id attributes in the cookie tables

### Version

3.0.0-rc13

### On which browser do you see the issue?

Firefox, Chrome

**Comment by orestbida** [comment]
fixed by c2623fb
