### ISSUE TITLE
Automatic blocking of cookies

### ISSUE THREAD

**Issue by Enigma995** [orestbida/cookieconsent#495]
### What is the improvement/update you wish to see?

Hello.

Thanks for a great plugin! Really amazing work.

I want to ask if it is possible to automate the process of blocking cookies?

I mean it so that I wouldn't have to manually add **data-cookiecategory="analytics**" and **defer** to the script.

Thank you for your help!

Best regards

**Comment by orestbida** [comment]
Hi @Enigma995, as far as I know, this is just not possible. 

You'd need a special tool that can scan the entire website and detect which scripts must be blocked using some sort of AI powered algorithm.
