### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of undefined (reading 'en')

### ISSUE THREAD

**Issue by Kareszrk** [orestbida/cookieconsent#496]
### Expected Behavior

Popup should be displayed as far as I understood the documentation correctly.

### Current Behavior

Uncaught TypeError: Cannot read properties of undefined (reading 'en')
    at cn (cookieconsent.js:7:3238)
    at cookieconsent.js:7:10946
    at U.run (cookieconsent.js:7:10992)
    at impress:150:15

### Steps to reproduce

I have commented my own code, which returns me the mentioned error.

### Version

2.8.9

### On which browser do you see the issue?

Chrome

**Comment by Kareszrk** [comment]
https://gist.github.com/Kareszrk/470a0581863105d97a187c39fdef00c4

**Comment by orestbida** [comment]
The plugin doesn't come with default languages/translation; you need to create at least one language where you configure both modals, as shown in the third step of the [installation and usage](https://github.com/orestbida/cookieconsent#installation--usage) section.

**Comment by Kareszrk** [comment]
Thank you!
