### ISSUE TITLE
[Feat]: Make it possible to customize cc-main z-index

### ISSUE THREAD

**Issue by EreMaijala** [orestbida/cookieconsent#501]
### Description

Our use case requires the cookie consent panel to stay below some other elements to allow the user e.g. to change language before accepting cookies. While it's possible to override the hard-coded 2147483647, it would be nicer if it was a css variable or something that could be customized without having to resort to `!important`.

### Proposed solution

Move the hard-coded style attribute to css so that it can be overridden.

**Comment by orestbida** [comment]
Sure, is this for v2 or v3?

**Comment by EreMaijala** [comment]
@orestbida Sorry, missed one of the most important bits. This is about v3.

**Comment by orestbida** [comment]
fixed in 91e1877
