### ISSUE TITLE
[Feat]: Buttons 3 in a row and look the same.

### ISSUE THREAD

**Issue by schickermineral** [orestbida/cookieconsent#503]
### Description

Hello, I am using your script in a project of mine.

I would like it if you could use 3 buttons instead of 2.

It would also be good if you could specify the color in the config.

The problem in Germany is that you have to make all buttons the same size and they must not differ in color either.

If you could then get the 3 in a row I would be perfectly happy. currently I've customized it using my own CSS.

### Additional details

![grafik](https://user-images.githubusercontent.com/41774780/232740926-421f70eb-0956-41a0-b423-e592aa940cdb.png)

**Comment by orestbida** [comment]
Hi @schickermineral,

a 3 button layout  (https://github.com/orestbida/cookieconsent/issues/79) has been implemented in [v3](https://github.com/orestbida/cookieconsent/tree/v3.0-beta). You can check it out in the [playground](https://playground.cookieconsent.orestbida.com/). 

Unfortunately there is no plan to bring this to v2.

**Comment by Dekker500** [comment]
Love the look of the v3 beta - can't wait until it gets released!

Love that "playground" link. Any possibility of having it spit out the "current" configuration that has been selected? That would allow a sort of WYSIWYG visual configuration!

**Comment by orestbida** [comment]
@Dekker500,

> Any possibility of having it spit out the "current" configuration that has been selected

Yes, that's the objective!
