### ISSUE TITLE
[Bug]: detect common config errors

### ISSUE THREAD

**Issue by procodix** [orestbida/cookieconsent#506]
### Expected Behavior

I think it is a catchable mistake, if script categories are not configured. They could be simply ignored, logged, or shown under an auto-configured category. 

### Current Behavior

the JavaScript console shows cryptic (compressed JS) messages about null types ("s.xe").

### Steps to reproduce

include a script with a data-category="something", and configure a category with a name of "different". 

### Version

3.0

### On which browser do you see the issue?

Firefox, Safari

**Comment by orestbida** [comment]
Yes, they should be ignored as in v2.
