### ISSUE TITLE
npm package needs more explanation on how to use

### ISSUE THREAD

**Issue by jamesz** [orestbida/cookieconsent#518]
README should include instruction on how to use the NPM package say in a React/Angular app.

e.g.
import 'vanilla-cookieconsent/dist/cookieconsent.css';
import 'vanilla-cookieconsent/dist/cookieconsent.js';

**Comment by orestbida** [comment]
This is mentioned in the FAQ section!

You _shouldn't_ need to use an explicit path when importing `cookieconsent.js`;
```javascript
import 'vanilla-cookieconsent/dist/cookieconsent.css';
import 'vanilla-cookieconsent';
```

**Comment by gojsse** [comment]
I came across these Nuxt instructions for something similar with the vanilla npm package which could be helpful in the FAQ as well [NPM vanilla-cookieconsent in Vue/Nuxt]:(https://github.com/orestbida/cookieconsent/issues/42#issuecomment-899387614). The instructions in the link are for Nuxt 2 only I believe. Plenty of legacy projects out there that still use v2.

**Comment by orestbida** [comment]
A note about React/VUE was added to the Readme, in the second step of the [Installation & usage](https://github.com/orestbida/cookieconsent/tree/v2.9#installation--usage) section.

**Comment by Coinhexa** [comment]
> A note about React/VUE was added to the Readme, in the second step of the [Installation & usage](https://github.com/orestbida/cookieconsent/tree/v2.9#installation--usage) section.

Super appreciate if you can also add a note in the installation about Nuxt 2 / 3
