### ISSUE TITLE
[Feat]: config in script tag

### ISSUE THREAD

**Issue by procodix** [orestbida/cookieconsent#519]
### Description

I feel that separating the script tags from the configuration is asking for trouble: misspelled categories, and other woes.

Why now put everything around a script into the configuration. For most users, external cookies are the problem, so they are spit out by external javascripts which are include inside some script tag.

However even inline scripts can be better tagged by attributes than by some error-prone json config.

```
<script url="..."
data-cc-category="whatever" 
data-cc-cookies="cookie1|description|cookie2|description"
data-cc-readonly="no"
data-cc-enabled="yes"
></script>
```

This way, whenever you change/switch/update a script, you are forced to look at the attributes as well. The configuration can then be autogenerated.

**Comment by orestbida** [comment]
Sorry, I don't like the idea of having to rely on script tags to define configuration fields. It surely wouldn't be _pretty_ to inject script tags in a React app just to define a category.

The user should be able to configure everything with no script tags at all.

**Comment by procodix** [comment]
With the configuration and script inclusion apart you run into inconsistencies with the factual scripts and the definition. Had some headaches around this, especially since CookieConsent does not do any sanity/plausibility checks. If a configuration category has no scripts, the thing crashes silently...

**Comment by procodix** [comment]
And: this tool should be framework agnostic. I assumed it was not written to be married to React. Any usual app would inject their script into the page.

**Comment by orestbida** [comment]
The plugin is written in vanilla javascript, so it is framework agnostic. You can use it in angular, react, vue ... or plain .html files.

There's a `.d.ts` file which should help you create a valid configuration.

Even if the config. was moved to the script tag, you'd still have to specify the categories inside the configuration object (javascript side) in order to create the toggles inside the settings modal.
