### ISSUE TITLE
[Feat v3]: Hide empty consent categories

### ISSUE THREAD

**Issue by alxndr-w** [orestbida/cookieconsent#521]
### Description

I'd be happy if Cookie Consent could solve this on it's own rather than everybody would have to solve this by themself. 

So if Cookie Consent got an empty "Marketing" group , the group should not show up in the settings modal as there's nothing to consent.

### Proposed solution

Check if the group is empty.

### Additional details

![image](https://github.com/orestbida/cookieconsent/assets/3855487/0f28b4a7-2631-4a0d-8c8a-41a3d8a95aef)

**Comment by orestbida** [comment]
Sorry, but this looks like a matter of personal preference, and it's not something that I would use. Given the plugin's current size (pretty big, IMO), I have a strict approach towards adding new features to ensure the file size remains as small as possible.
