### ISSUE TITLE
[Bug v3]: Cookie Consent js cannot be loaded with Safari on iOS < 13.4

### ISSUE THREAD

**Issue by EreMaijala** [orestbida/cookieconsent#524]
### Expected Behavior

We just found out that Cookie Consent v3 does not work with Safari on iOS versions older than 13.4 due to the older versions [not supporting optional chaining](https://caniuse.com/mdn-javascript_operators_optional_chaining). That means that v3 does not work on a browser released in the beginning of 2020, but we sort of expected that to be modern enough.

### Current Behavior

`SyntaxError: Unexpected token: '.'`

### Steps to reproduce

Try to access playground with an iOS device running iOS 13.3 or older.

### Proposed fix or additional info.

If a browser from 2020 is considered modern enough, would it be possible to avoid the optional chaining operator `?.`? If not, I'd request that this be documented as a requirement for a modern browser. We could of course try to transpile the js locally, but I'd really like to avoid that.

### Version

3.0.0-rc13

### On which browser do you see the issue?

Safari

**Comment by orestbida** [comment]
Yes, In fact, I recently added support for older versions of safari in the latest release of [iframemanager](https://github.com/orestbida/iframemanager/releases/tag/v1.2.4). 

Safari 11-13 should now be supported (currently there's a bug causing the toggles' icons to not render properly): 605ae6f0e5020c4088299b7fdcf72c8e39451e04 8c0112688bde234fe6b169dee84596a678d99571.

The playground page itself does not yet fully support safari 11-13 (work in progress).

**Comment by orestbida** [comment]
There's now official support for Safari 11.3+ in [rc.14](https://github.com/orestbida/cookieconsent/releases/tag/v3.0.0-rc.14)!
