### ISSUE TITLE
[Feat]: Measurement of rejection rate

### ISSUE THREAD

**Issue by csaeum** [orestbida/cookieconsent#526]
### Description

A cool feature would be if the rejection would be counted in a file.
Or can someone tell me how you count or monitor it?

### Additional details

So what did people click:
accept everything
Configure cookies
reject everything

**Comment by orestbida** [comment]
As a client-side only solution this is not possible without a dedicated API (backend): https://github.com/orestbida/cookieconsent/discussions/208

Here are 2 examples/guidelines which should help you out:
* [Example using v2](https://stackblitz.com/edit/web-platform-9f7bqs?file=cookieconsent-init.js)
* [Example using v3](https://cookieconsent.orestbida.com/advanced/consent-logging.html)

You grab the data (user's preferences) from the plugin and then you send it (using a POST request) to a specific API Endpoint. It will be the task of the API to handle how/where the data should be stored.
