### ISSUE TITLE
[Feat]: Language Selector

### ISSUE THREAD

**Issue by paulwer** [orestbida/cookieconsent#532]
### Description

When multiple languages are defined, a language selector should be displayed for the user to select his language.
Maybe optional by adding a property.

Kindly thank you.
Paul

**Comment by orestbida** [comment]
The plugin allows you to set the language dynamically based on the user's browser, which IMHO makes this feature *very* optional. 

Unfortunately this won't be worked on for the sake of keeping the plugin as light as possible.

**Comment by paulwer** [comment]
In our case the website could be accessed from users with different languages and the cookie banner is the first thing they see and have to interact with, therefore i suggest reconsiddering this.

For now we are using the browser language. Thanks for the plugin anyways, nice work :)
