### ISSUE TITLE
[Bug]: Service counter is not displaying

### ISSUE THREAD

**Issue by MoritzLost** [orestbida/cookieconsent#533]
### Expected Behavior

I'm trying to use `serviceCounterLabel` to display the tiny counter indicating how many services are in a category. The categories are defined like this (simplified example):

```js
categories: {
    necessary: {
        enabled: true,
        readOnly: true,
    },
    media: {
        services: {
            youtube: {
                label: 'YouTube',
            },
            vimeo: {
                label: 'Vimeo',
            },
        },
    },
}
```

The translation defines a `serviceCounterLabel` (under `translations.de.preferencesModal`):

```js
serviceCounterLabel: 'Dienst|Dienste',
```

I also tried a simple string without the separator (`Dienst(e)`), but it's not working. The counter just doesn't show up. Is there something else I need to configure to get the counter to show up?

### Current Behavior

The counter icon never shows up, even if included in the config.

### Steps to reproduce

Include the `serviceCounterLabel` in the config as described above.

### Version

3.0.0-rc.15

### On which browser do you see the issue?

Firefox

**Comment by orestbida** [comment]
This works fine on my end: [demo](https://stackblitz.com/edit/web-platform-3asqh5?file=en.json%3AL18-L18)

Perhaps its just hidden; the label is hidden on mobile view and when the selected layout is `'bar'`, as the modal becomes quite narrow.

**Comment by MoritzLost** [comment]
@orestbida You're right, thanks! I was using bar layout. I think this caveat should be mentioned in the docs, I have opened a PR for this: #535
