### ISSUE TITLE
[Feat]: Allow a custom button order

### ISSUE THREAD

**Issue by MoritzLost** [orestbida/cookieconsent#534]
### Description

If all buttons are enabled in the consent and preferences modal, they are ordered like this:

- Reject all
- Accept all
- Manage preferences (consent modal) / Save preferences (preferences modal)

I can use `flipButtons` to invert the order of those buttons. But what is _not_ possible, as far as I can tell, is ordering the buttons like this: 

- Accept all
- Reject all
- Manage preferences (consent modal) / Save preferences (preferences modal)

Is this possible? If not, this would be great. In the default order, having reject all first isn't optimal, because the suggested action (from the website owner's perspective) should be accept all (while displaying both options with equal weight – `equalWeightButtons` is great!). But when the order is inverted, the secondary action is displayed _first_, which isn't ideal.

I know there are multiple layouts to chose from, but all of those could benefit from allowing for a custom button order.

### Proposed solution

Some ideas:

- Extend `flipButtons` to support an object or array that defines the button order (in addition to the existing behaviour).
- Create a separate config under `guiOptions` for the order and allow `flipButtons` to invert it.

**Comment by orestbida** [comment]
While I get your point, I also think that this is a *very* optional feature. I'd rather change the current default order to keep the size of the plugin as small as possible.

**Comment by MoritzLost** [comment]
@orestbida Thanks for the reply – you're right about keeping the size (and also number of options small).
As a workaround, I can reorder the buttons using `grid-colum-start` (side-note: any reason you're using `margin-top` instead of `row-gap` to space those buttons?). That isn't ideal for accessibility, though, since the tab order will be different than the visual order.

I'm in favour of changing the default order. This will allow developers to put the `Accept all` button either at the top or the bottom using the `flipButtons` config, depending on the surrounding layout system. I don't think it ever makes sense to have the primary/suggested button in the middle.

**Comment by mrleblanc101** [comment]
Instead of `flipButtons: true`, maybe something like this `buttonOrder: ['accept', 'reject',  'preferences']` so we can customize the order easily

**Comment by mrleblanc101** [comment]
In v3, I notice we can do these 2 layouts
![Screenshot 2023-10-23 at 11 24 14 AM](https://github.com/orestbida/cookieconsent/assets/17392251/a319d1a0-a125-42b7-a103-eb2893045f67)
![Screenshot 2023-10-23 at 11 24 11 AM](https://github.com/orestbida/cookieconsent/assets/17392251/de6093a7-20a9-4462-86e1-74215e21df61)

But not this 3rd option which seems the most logical to me:
![Screenshot 2023-10-23 at 11 25 58 AM](https://github.com/orestbida/cookieconsent/assets/17392251/2ccab598-83c7-4b58-82e9-2fc072fed647)

**Comment by mrleblanc101** [comment]
I'll open a new issue, it will be easier to track
