### ISSUE TITLE
[Feat]: Allow individual services to be enabled by default

### ISSUE THREAD

**Issue by MoritzLost** [orestbida/cookieconsent#537]
### Description

Currently, it's only possible to enable/disable entire categories by default. But sometimes, you need individual services to be enabled by default. For example, let's say you use Matomo and Google Analytics, both are listed in a category `Analytics`. Matomo is configured to not use cookies and to anonymize IPs, so it can run without consent. GA can only run after consent has been given. In this case, I want Matomo to be enabled by default, but Google Analytics to be disabled by default.

### Proposed solution

Add a new configuration option to services, e.g. `categories.[category].services.[service].enabled` to set the default state for individual services, similar to the `enabled` option for categories that sets the default state for that category.

**Comment by orestbida** [comment]
Sorry, this won't be worked on, mainly for the same reasons explained in https://github.com/orestbida/cookieconsent/issues/536#issuecomment-1603394090.

**Comment by MoritzLost** [comment]
Fair enough, thanks for the reply.
