### ISSUE TITLE
[Bug]: The preference modal bar layout is broken if button order is flipped

### ISSUE THREAD

**Issue by MoritzLost** [orestbida/cookieconsent#539]
### Expected Behavior

With the preferences modal set to `layout: bar` and `flipButtons: true`, the button layout is broken:

![Screen Shot 2023-06-22 at 12 34 43](https://github.com/orestbida/cookieconsent/assets/10146880/6be8f6cf-b504-44e1-9567-e411174e70d2)

The `necessary` button has additional margin to the top and right, but this only works in the default button order.

### Current Behavior

Buttons lack spacing and are not of equal width.

### Steps to reproduce

Use `layout: bar` and `flipButtons: true` under `guiOptions.preferencesModal`.

### Proposed fix or additional info.

This could be fixed by using `gap` instead of `margin` to add some spacing between the buttons. This works regardless of `flex-direction` or `grid-column` settings.

### Version

3.0.0-rc.15

### On which browser do you see the issue?

Firefox

**Comment by orestbida** [comment]
Can confirm this is a bug!

Unfortunately the [`gap` property is not supported in Safari < 14.1](https://caniuse.com/flexbox-gap) when the flexbox layout is used: https://github.com/orestbida/cookieconsent/commit/8c0112688bde234fe6b169dee84596a678d99571.

**Comment by MoritzLost** [comment]
> Unfortunately the [gap property is not supported in Safari < 14.1](https://caniuse.com/flexbox-gap) when the flexbox layout is used: https://github.com/orestbida/cookieconsent/commit/8c0112688bde234fe6b169dee84596a678d99571.

Ah, right – we dropped iOS < 15 a while ago, so we've been able to use `gap` in flex layouts.
Is there an official list of supported browsers? All I found is the note in the comparison between v2 and v3:

> Supports modern browsers only

**Comment by orestbida** [comment]
Unfortunately a consent management tool needs to have a reasonably wide browser support, so we're stuck with `margin`.

I don't know about specific browser ranges, *probably* all the browsers that support flexbox/grid and es6+. The oldest supported Safari version is 11.3.

**Comment by MoritzLost** [comment]
@orestbida Got it, thanks! Might be a good idea to explicitly define browser support using [browserslist](https://github.com/browserslist/browserslist).

**Comment by squareclouds** [comment]
> @orestbida Got it, thanks! Might be a good idea to explicitly define browser support using [browserslist](https://github.com/browserslist/browserslist).

yes!!! saying that v3 "Supports modern browsers only" is not helpful at all. a list with actual values would be good
