### ISSUE TITLE
[Bug]: Cookie Table header doesn't span full width

### ISSUE THREAD

**Issue by MoritzLost** [orestbida/cookieconsent#543]
### Expected Behavior

The header displayed when using the `caption` option for the `cookieTable` should span the whole width of the container in `bar` or `bar wide` layouts. In `box` layout, the header looks correct:

![Screenshot 2023-06-28 at 11 03 38](https://github.com/orestbida/cookieconsent/assets/10146880/70bbb3cf-00ee-4b4b-bb63-1a548cfa1379)

### Current Behavior

In `bar` or `bar wide` layout, the header is crammed to the left side, and the border doesn't span the whole width:

![Screenshot 2023-06-28 at 11 04 54](https://github.com/orestbida/cookieconsent/assets/10146880/f41a7e26-feee-4ec0-b112-5537b33707b5)

### Steps to reproduce

Use `bar` layout for the `preferencesModal` and add a `cookieTable` with a `caption`.

### Version

3.0.0-rc.15

### On which browser do you see the issue?

Firefox

**Comment by orestbida** [comment]
Nice catch!
