### ISSUE TITLE
[Bug]: 'cookie_expiration' and 'cookie_necessary_only_expiration' have no effect

### ISSUE THREAD

**Issue by lucasdalpra** [orestbida/cookieconsent#546]
### Expected Behavior

In the cookieconsent-init.js file, the options 'cookie_expiration' and 'cookie_necessary_only_expiration' offer the possibility to define custom expiry times of saved cookies. Default time in case of not setting custom time is 182 days.

### Current Behavior

The 'cookie_expiration' and 'cookie_necessary_only_expiration' options have no effect and the default expiration time is 7 days, instead of 182 days.

### Steps to reproduce

In the cookieconsent-init.js file, enable the 'cookie_expiration' and 'cookie_necessary_only_expiration' options and set the desired expiration times (in days). Clear the cache and save cookies in the consent window, then check the saved cookies for the actual expiration date recorded. In my case, it doesn't matter if I leave the mentioned options commented or if I put any amount of days, the saved cookies always have 7 days of validity.

<img width="574" alt="file1" src="https://github.com/orestbida/cookieconsent/assets/61293132/91b998cd-c902-4e21-a7b8-1d93b14f4cff">

<img width="723" alt="file2" src="https://github.com/orestbida/cookieconsent/assets/61293132/5a5f581c-ca52-432e-a6cf-a02af9adce15">

### Version

2.8.9

### On which browser do you see the issue?

Brave

**Comment by orestbida** [comment]
Hi @lucasdalpra, I can't reproduce this issue in v2.9.1, both fields work as intended on my end.

Can you provide a live demo that I can inspect (codepen, jsfiddle, stackblitz ...), or at the very least share the full configuration.

**Comment by orestbida** [comment]
Ah, it makes sense if you're using Brave, as it modifies the duration of cookies by default: https://www.cookiestatus.com/.
