### ISSUE TITLE
Google Analytics ^__utm

### ISSUE THREAD

**Issue by tdrzewosz** [orestbida/cookieconsent#55]
Hello, at first load I have got man ^__utm Cookies 

- __utmb
- __utmt
- __utma
- __utmz
- __utmc

How I can block?

`  {
                                col1: '^__utm',
                                col2: '.shop.demo.de',
                                col3: 'Google Analytics',
                                is_regex: true 
                            },`

Not working. Thanks! 

EDIT: I See I have got 2 different cookie domains. (Main & Subdomain). Is this a problem?

**Comment by orestbida** [comment]
you need to check in which domain are these cookies being set. The cookieconsent will try to delete cookies on the current domain (or subdomain) only. If you're on a subdomain but the cookies are being set on the main domain, you need to explicitly tell the cookieconsent the domain where they're being set.

for example if you are on `test.mydomain.com` and the google analytics' cookies are set on `mydomain.com`, you can specify on the cookie table, a `domain` parameter like so:

```javascript
{ 
  col1: '^__utm', 
  col2: '.shop.demo.de', 
  col3: 'Google Analytics',
  is_regex: true,
  domain: "mydomain.com"
}

**Comment by tdrzewosz** [comment]
works! thanks
