### ISSUE TITLE
[Feat]: disable trap focus

### ISSUE THREAD

**Issue by straatrakker** [orestbida/cookieconsent#551]
### Description

Maybe it would be useful to be able to disable the focus trap. This could be useful for when you have a page with details about the cookies on your website. Now it's not possible to tab through this information without first accepting or declining the cookies. This is not accessible

**Comment by dombyte** [comment]
Do you mean disablePageInteraction?

**Comment by straatrakker** [comment]
@dombyte No I don't think that's what i am looking for. In the source code there is a function called `_handleFocusTrap()`.

So when the cookie consent modal is shown, i cannot tab anywhere besides the cookie consent modal.

I would like to be able to disable `handleFocusTrap()`. Because I want the users of my website to still be able to tab through the webpage while the cookie consent modal is shown

**Comment by dombyte** [comment]
But that's possible when you set disablePageInteraction = true 
Then the Modal is shown and you're still able to navigate the Page.

**Comment by straatrakker** [comment]
@dombyte To the best of my knowledge `disablePageInteraction` adds a dark overlay and blocks the interaction with the page. By default `disablePageInteraction` is set to false. 

I have set `disablePageInteraction` to false. I can indeed interact with the page. I can scroll on the page, and i can navigate the page with my cursor. But what I can not do is interact with the page using the tab button. The tab focus is trapped inside the modal and cannot leave.

**Comment by dombyte** [comment]
Ah my mistake, I understood you wrong. Yeah that's indeed them something else.

**Comment by straatrakker** [comment]
> Ah my mistake, I understood you wrong. Yeah that's indeed them something else.

No worries, I appreciate your time :)

**Comment by orestbida** [comment]
> Now it's not possible to tab through this information without first accepting or declining the cookies. This is not accessible

Hi @straatrakker, the current behavior follows a11y best practices https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/.

To me this looks more like a personal preference; sorry this won't be worked on!

**Comment by rocky2b** [comment]
Wanted to share this in case anybody searches as well --

Current a11y best practices is for dialog (modals) to be focus trapped. But when it's not a modal, it should not focus-trap.

For our use-case, we want the consent modal to be something a end-user can navigate to without disrupting flow, nor locking them. 

Use-case:
1. User lands on the page and can only navigate with only their keyboard
2. User should be able to tab through the site normally. They can hit nav menus, the body links, footer.
3. User should be able to tab to the Consent modal after the footer.

We discovered when Consent Modal -> Layout -> bar inline (and maybe some other layouts), does not focusTrap, and works for that use-case!

And if necessary, you can also restyle with CSS the Consent Modal to 'simulate' a modal look, while still making it a11y.
