### ISSUE TITLE
[Bug v3]: Version number mismatch in packaged 3.0.0-rc.16

### ISSUE THREAD

**Issue by EreMaijala** [orestbida/cookieconsent#555]
### Expected Behavior

Looks like the dist files in the 3.0.0-rc.16 release indicate their version number as 3.0.0-rc.15. They are not the same as the files in release version 3.0.0-rc.15, so maybe just a missing version number update?

### Current Behavior

Release 3.0.0-rc.16 contains files marked as 3.0.0-rc.15.

### Steps to reproduce

Download the release and check the header of e.g. dist/cookieconsent.umd.js

### Version

3.0.0-rc.16

**Comment by orestbida** [comment]
Yes, just the header version is wrong, as I forgot to update it before publishing the package.
