### ISSUE TITLE
[Bug v2]: Can't update dynamic scripts in opt-out mode when no consent is made.

### ISSUE THREAD

**Issue by HannaHabr** [orestbida/cookieconsent#556]
### Description

Hi! Is it possible to pass `default_enabled_categories` to `_manageExistingScripts` in `updateScripts` call? I use opt-out mode. I need this behavior to update dynamic scripts when no consent is made. In this case `updateScripts` just do nothing, because cookie is not set and default_enabled_categories are not provided, but they exist in config.

![image](https://github.com/orestbida/cookieconsent/assets/31014790/5a6c4332-e78f-4b26-b3ff-b4980ff3ec43)

### Proposed solution

There are two ways to do this:
1.
```
_cookieconsent.updateScripts = function(must_enable_categories?: string[]){
            _manageExistingScripts(must_enable_categories);
 }
```
2.
```
_cookieconsent.updateScripts = function(){
            _manageExistingScripts(default_enabled_categories); //pick from config if opt-out mode
 }
```

### Additional details

Can this be made based on 2.9.1 version? I use it right now.

**Comment by orestbida** [comment]
This is a bug actually, will be fixed in the upcoming release!

**Comment by HannaHabr** [comment]
@orestbida thanks! Do you have a date of the release?

**Comment by orestbida** [comment]
Most likely by the end of the week.

**Comment by orestbida** [comment]
@HannaHabr v2.9.2 is out!
