### ISSUE TITLE
[Feat]: Language Autodetect

### ISSUE THREAD

**Issue by Diewy** [orestbida/cookieconsent#560]
### Description

Hi,

Currently, the language autodetect feature in the browser works with only the language component, while the document mode uses the complete lang value. This results in differing outcomes for each detection method.

For instance, consider the case of "en-GB":

- Browser mode: "en"
- Document mode: "en-GB"

This inconsistency in the autodetection process can lead to confusion and discrepancies in the language identification.

### Proposed solution

In an ideal scenario, the language autodetection process should prioritize finding translations for the complete lang code. If translations for the complete code are unavailable, the detection mechanism should then resort to searching for the language-only version.

### Additional details

Any feedback on the proposed solution?
Before I look into creating a pull request, would you be open to considering this change in the v3 version?

Thanks!

**Comment by orestbida** [comment]
Hi @Diewy, yes I fully agree with you! No ambiguity and it handles a wider range of use cases without introducing breaking changes. A PR is welcome!
