### ISSUE TITLE
Is it possible to add new section top of modal.

### ISSUE THREAD

**Issue by mmustafau** [orestbida/cookieconsent#57]
Hi, thanks for this job. It is very useful.

I want to ask that can we add new section next to the Coooki Setting at the top of the modal.

I want to add Cookie policy text in a new page. Is this possible or not.

Thanks for your great work.

**Comment by orestbida** [comment]
Hi @mmustafau,

If I understand correctly, you want to add some kind of "[tabs](https://inspirationalpixels.com/wp-content/uploads/2014/01/1.png)" support?

Unfortunately this is not possible with this cookie consent plugin. The only way to achieve this would be to manually inject html into the cookieconsent and manage the tabs via custom javascript which would hide/show the interested sections.

**Comment by mmustafau** [comment]
thank you for all support.

**Comment by costafrancesco94** [comment]
I think he intended to add a block between title and blocks...

I wanted a place to put another "description" after the title before the blocks section.

I also noticed there is nothing (except putting a link in the description of `consent_modal`) to link the privacy policy page.

A simple link is enough to be fully compliant with GDPR, not talking about modals or something like that.

would a description on the settings_modal be something easy to implement?
