### ISSUE TITLE
[Feat]: Privacy Policy link and force_consent

### ISSUE THREAD

**Issue by Massi-X** [orestbida/cookieconsent#572]
### Description

Hi, currently when cookieconsent is created with `force_consent=true` no action is permitted before the user choose what to do with the cookies. This is all fine but there is a small problem connected to the privacy link. In fact the privacy link when clicked takes you to another page, where the popup i still enabled with `force_consent=true` and doesn't let you see through. Although this can be prevented by setting this specific page with no force I think it's not the best idea (the popup is still blinding some area of the page especially on mobile devices).

### Proposed solution

A popup containing the privacy policy.

### Additional details

Currently I'm showing the popup with SweetAlert2, giving a z-index the same as cookieconsent (2147483647 which is already the max possible). Because it is attached below in the DOM it goes above yours, but still a hacky solution 😁

**Comment by peter-neumann-dev** [comment]
I have solved the same issue like this:

- `autorun: false` in the config
- the code below will prevent the initial modal on the privacy policy page
- on the privacy page we have a fixed button to open the settings panel again (this is always there, also after consent)

```javascript
const cookieConsetConfig = { 
  autorun: false
}

cc.run(cookieConsetConfig)

// Show the cookie consent modal if not on privacy policy page
if ((window.location.pathname !== privacyPolicyUrl)) {
  cookieConset.show()
}
```

**Comment by Massi-X** [comment]
That's not a bad idea! Bit is this gdpr compliant? Not a big issue for me but nice to know

**Comment by peter-neumann-dev** [comment]
We had no problems with that since today because it will pop up on all other pages until the user decides for it. The reason it is accepted (I think) is that at least the data privacy should work without any consent. Even if you have to link from other pages or printed products (like forms) to it. 🙂

But as always, the Data Protection Officer from the company has to check this. (No reliable legal advice)

**Comment by Massi-X** [comment]
Thank you all! Closing this
