### ISSUE TITLE
[Bug]: Cant open Modal with button

### ISSUE THREAD

**Issue by AlkoKod** [orestbida/cookieconsent#574]
### Expected Behavior

Modal should be opened with: 

<button type="button" data-cc="show-preferencesModal">Správa cookies</button>

I am not sure, why it doesnt work for me. Can I check it somehow?

### Current Behavior

Button does nothing. Take a look https://www.bouranidami.cz/

### Steps to reproduce

Downloaded script, added to my site. Consent works, button doesnt.

### Version

3.0.0

### On which browser do you see the issue?

Microsoft Edge

**Comment by orestbida** [comment]
You must load the plugin with the `defer` keyword, otherwise it won't scan the entire page:

```html
<script defer src="/wp-content/themes/bricks-child/scripts/cookieconsent/cookieconsent.js"></script>
<script defer src="/wp-content/themes/bricks-child/scripts/cookieconsent/cookieconsent-init.js"></script>
```

**Comment by AlkoKod** [comment]
> You must load the plugin with the `defer` keyword, otherwise it won't scan the entire page:
> 
> ```
> <script defer src="/wp-content/themes/bricks-child/scripts/cookieconsent/cookieconsent.js"></script>
> <script defer src="/wp-content/themes/bricks-child/scripts/cookieconsent/cookieconsent-init.js"></script>
> ```

Thank you very much. I was getting lost. Sorry for your time!
