### ISSUE TITLE
Cookie consent in German

### ISSUE THREAD

**Issue by Mamunson** [orestbida/cookieconsent#585]
### Discussed in https://github.com/orestbida/cookieconsent/discussions/584

<div type='discussions-op-text'>

<sup>Originally posted by **Mamunson** October 20, 2023</sup>
Hi,

I asked a question here [https://github.com/orgs/community/discussions/70679](url)
Grateful for your guidance. </div>

Hi there,

I'm trying to configure this cookie consent to show in German (It is still showing in English) https://github.com/orestbida/cookieconsent#layout-options--customization

`
<title></title> <script src="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@v2.9.2/dist/cookieconsent.js"></script> <script defer src="assets/js/cookieconsent-init.js"></script> `
and this is inside the cookieconsent-init.js file:

`// obtain plugin
var cc = initCookieConsent();

// run plugin with your configuration
cc.run({
current_lang: 'de',
autoclear_cookies: true, // default: false
page_scripts: true,
auto_language: 'document',

`// obtain plugin
var cc = initCookieConsent();

// run plugin with your configuration
cc.run({
    current_lang: 'de',
    autoclear_cookies: true,                   // default: false
    page_scripts: true,  
    auto_language: 'document',

    // mode: 'opt-in'                          // default: 'opt-in'; value: 'opt-in' or 'opt-out'
    // delay: 0,                               // default: 0
    // auto_language: null                     // default: null; could also be 'browser' or 'document'
    // autorun: true,                          // default: true
    // force_consent: false,                   // default: false
    // hide_from_bots: true,                   // default: true
    // remove_cookie_tables: false             // default: false
    // cookie_name: 'cc_cookie',               // default: 'cc_cookie'
    // cookie_expiration: 182,                 // default: 182 (days)
    // cookie_necessary_only_expiration: 182   // default: disabled
    // cookie_domain: location.hostname,       // default: current domain
    // cookie_path: '/',                       // default: root
    // cookie_same_site: 'Lax',                // default: 'Lax'
    // use_rfc_cookie: false,                  // default: false
    // revision: 0,                            // default: 0

    onFirstAction: function(user_preferences, cookie){
        // callback triggered only once
    },

    onAccept: function (cookie) {
        // ...
    },

    onChange: function (cookie, changed_preferences) {
        // ...
    },

    languages: {
        'de': {
            consent_modal: {
                title: 'We use cookies!',
                description: 'Hi, this website uses essential cookies to ensure its proper operation and tracking cookies to understand how you interact with it. The latter will be set only after consent. <button type="button" data-cc="c-settings" class="cc-link">Let me choose</button>',
                primary_btn: {
                    text: 'Accept all',
                    role: 'accept_all'              // 'accept_selected' or 'accept_all'
                },
                secondary_btn: {
                    text: 'Reject all',
                    role: 'accept_necessary'        // 'settings' or 'accept_necessary'
                }
            },
            settings_modal: {
                title: 'Cookie preferences',
                save_settings_btn: 'Save settings',
                accept_all_btn: 'Accept all',
                reject_all_btn: 'Reject all',
                close_btn_label: 'Close',
                cookie_table_headers: [
                    {col1: 'Name'},
                    {col2: 'Domain'},
                    {col3: 'Expiration'},
                    {col4: 'Description'}
                ],
                blocks: [
                    {
                        title: 'Cookie usage 📢',
                        description: 'I use cookies to ensure the basic functionalities of the website and to enhance your online experience. You can choose for each category to opt-in/out whenever you want. For more details relative to cookies and other sensitive data, please read the full <a href="#" class="cc-link">privacy policy</a>.'
                    }, {
                        title: 'Strictly necessary cookies',
                        description: 'These cookies are essential for the proper functioning of my website. Without these cookies, the website would not work properly',
                        toggle: {
                            value: 'necessary',
                            enabled: true,
                            readonly: true          // cookie categories with readonly=true are all treated as "necessary cookies"
                        }
                    }, {
                        title: 'Performance and Analytics cookies',
                        description: 'These cookies allow the website to remember the choices you have made in the past',
                        toggle: {
                            value: 'analytics',     // your cookie category
                            enabled: false,
                            readonly: false
                        },
                        cookie_table: [             // list of all expected cookies
                            {
                                col1: '^_ga',       // match all cookies starting with "_ga"
                                col2: 'google.com',
                                col3: '2 years',
                                col4: 'description ...',
                                is_regex: true
                            },
                            {
                                col1: '_gid',
                                col2: 'google.com',
                                col3: '1 day',
                                col4: 'description ...',
                            }
                        ]
                    }, {
                        title: 'Advertisement and Targeting cookies',
                        description: 'These cookies collect information about how you use the website, which pages you visited and which links you clicked on. All of the data is anonymized and cannot be used to identify you',
                        toggle: {
                            value: 'targeting',
                            enabled: false,
                            readonly: false
                        }
                    }, {
                        title: 'More information',
                        description: 'For any queries in relation to our policy on cookies and your choices, please <a class="cc-link" href="#yourcontactpage">contact us</a>.',
                    }
                ]
            }
        }
    }
});`

Grateful for your guidance.

**Comment by orestbida** [comment]
Hi @Mamunson, you need to manually translate the content to german, since there are no built in translations. 

You can try the [v3 playground](https://playground.cookieconsent.orestbida.com/) which allows you to edit the translations through a GUI.

**Comment by danielehrhardt** [comment]
```
 de: {
          consent_modal: {
            title: 'Wir verwenden Cookies!',
            description:
              'Hallo, diese Webseite verwendet notwendige Cookies, um ihre ordnungsgemäße Funktion sicherzustellen, und Tracking-Cookies, um zu verstehen, wie Sie mit ihr interagieren. Letztere werden erst nach Zustimmung gesetzt. <button type="button" data-cc="c-settings" class="cc-link">Lassen Sie mich auswählen</button>',
            primary_btn: {
              text: 'Alle akzeptieren',
              role: 'accept_all',
            },
            secondary_btn: {
              text: 'Alle ablehnen',
              role: 'accept_necessary',
            },
          },
          settings_modal: {
            title: 'Cookie-Einstellungen',
            save_settings_btn: 'Einstellungen speichern',
            accept_all_btn: 'Alle akzeptieren',
            reject_all_btn: 'Alle ablehnen',
            close_btn_label: 'Schließen',
            cookie_table_headers: [
              { col1: 'Name' },
              { col2: 'Domain' },
              { col3: 'Ablaufdatum' },
              { col4: 'Beschreibung' },
            ],
            blocks: [
              {
                title: 'Verwendung von Cookies 📢',
                description:
                  'Wir verwenden Cookies, um die grundlegenden Funktionen der Website sicherzustellen und Ihr Online-Erlebnis zu verbessern. Sie können für jede Kategorie entscheiden, ob Sie sie aktivieren/deaktivieren möchten. Weitere Informationen zu Cookies und anderen sensiblen Daten finden Sie in der vollständigen <a href="#" class="cc-link">Datenschutzerklärung</a>.',
              },
              {
                title: 'Unbedingt erforderliche Cookies',
                description:
                  'Diese Cookies sind für das ordnungsgemäße Funktionieren meiner Webseite unerlässlich. Ohne diese Cookies würde die Webseite nicht ordnungsgemäß funktionieren.',
                toggle: {
                  value: 'necessary',
                  enabled: true,
                  readonly: true,
                },
              },
              {
                title: 'Leistungs- und Analyse-Cookies',
                description:
                  'Diese Cookies ermöglichen es der Webseite, sich an die von Ihnen in der Vergangenheit getroffenen Entscheidungen zu erinnern.',
                toggle: {
                  value: 'analytics',
                  enabled: false,
                  readonly: false,
                },
                cookie_table: [
                  {
                    col1: '^_ga',
                    col2: 'google.com',
                    col3: '2 Jahre',
                    col4: 'Beschreibung ...',
                    is_regex: true,
                  },
                  {
                    col1: '_gid',
                    col2: 'google.com',
                    col3: '1 Tag',
                    col4: 'Beschreibung ...',
                  },
                ],
              },
              {
                title: 'Werbe- und Ziel-Cookies',
                description:
                  'Diese Cookies sammeln Informationen darüber, wie Sie die Webseite nutzen, welche Seiten Sie besucht haben und auf welche Links Sie geklickt haben. Alle Daten sind anonymisiert und können nicht zur Identifikation verwendet werden.',
                toggle: {
                  value: 'targeting',
                  enabled: false,
                  readonly: false,
                },
              },
              {
                title: 'Weitere Informationen',
                description:
                  'Bei Fragen zu unserer Cookie-Richtlinie und Ihren Wahlmöglichkeiten, <a class="cc-link" href="#yourcontactpage">kontaktieren Sie uns</a> bitte.',
              },
            ],
          },
        },
```

**Comment by Mamunson** [comment]
Many thanks indeed to both of you :+1: Much appreciate it.
