### ISSUE TITLE
[Bug]: Border disappers causing consent window to jump 

### ISSUE THREAD

**Issue by seigieu** [orestbida/cookieconsent#586]
### Expected Behavior

Cookie window not jumping because border disappears

### Current Behavior

If hovered on cookie consent popup, border disappears and makes consent "jumpy" if there is `.box` class in same file
This happens on Prestashop 1.6 when enabled fuinction to compile all CSS into one file.

### Steps to reproduce

It's hard to reproduce. Probably impossible as this is visible only on cerain systems (Prestashop) when Compile all CSS into one file is enabled

### Proposed fix or additional info.

There is this code
```
.cc_div *,
.cc_div *:hover,
.cc_div :before,
.cc_div :after{
```
Change it to 
```
#cc_div.cc_div *,
#cc_div.cc_div *:hover,
#cc_div.cc_div :before,
#cc_div.cc_div :after{
```

This will increase CSS importance of rules and will make it less prone to being affected by other classes

### Version

2.8.9

### On which browser do you see the issue?

Firefox

**Comment by orestbida** [comment]
Hi @seigieu, changing the specificity of the selectors will very likely reset/alter the custom css used by other users, something I'd like to avoid.

**Comment by seigieu** [comment]
@seigieu I tested it and yes. It's far too complex for fix to be that easy it seems. For now I made myself additional fix:
```css
#cm { /* Fix border problem */
    border: none !important;
}
```
Leaving it, if anyone ever needs.
