### ISSUE TITLE
[Feat]: Accept all on the top-right when using `bar inline` layout

### ISSUE THREAD

**Issue by mrleblanc101** [orestbida/cookieconsent#587]
### Description

In v3, I notice we can do these 2 layouts:

Accept all on the botton right
![Screenshot 2023-10-23 at 11 24 14 AM](https://github.com/orestbida/cookieconsent/assets/17392251/a319d1a0-a125-42b7-a103-eb2893045f67)

Accept all on the top left
![Screenshot 2023-10-23 at 11 24 11 AM](https://github.com/orestbida/cookieconsent/assets/17392251/de6093a7-20a9-4462-86e1-74215e21df61)

But not this 3rd option which seems the most logical to me:
Accept all on the top right
![Screenshot 2023-10-23 at 11 25 58 AM](https://github.com/orestbida/cookieconsent/assets/17392251/2ccab598-83c7-4b58-82e9-2fc072fed647)

### Proposed solution

Instead of `swap_button: true` in v2 or `flipButtons: true` in v3, maybe something like this `buttonOrder: ['accept', 'reject',  'preferences']` so we can customize the order easily ?

**Comment by orestbida** [comment]
Sorry, this won't be worked on since it would require either a breaking change or a new option which could conflict with the already existing ones.
