### ISSUE TITLE
[Feat]: Parse again function for dynamic Html component

### ISSUE THREAD

**Issue by gitVasile** [orestbida/cookieconsent#590]
### Description

If I add the piece of code below in my DOM dynamically, the cookieconsent will never be able to parse this new code because it was added after the loaded.

```
<script type="text/plain" data-cookiecategory="optional" lang="js">alert('ok')</script>
```

### Proposed solution

We should maybe add a way to parse the code again using a mehtod from you api.

### Additional details

Thank you

**Comment by orestbida** [comment]
@gitVasile, you can use the `.updateScripts()` method to let the plugin know of newly added script tags.

**Comment by gitVasile** [comment]
Hey @orestbida ok, but why about iframe newly added for example? Is updateScripts() parsing all the elements?

Thank you

**Comment by orestbida** [comment]
Unfortunately no, the plugin only handles scripts.

**Comment by gitVasile** [comment]
Ok, no problem. Thank you for your time and project 👍 .

**Comment by orestbida** [comment]
@gitVasile  I forgot to mention as I was in a hurry, but there's a dedicated plugin to handle iframes, called [iframemanager](https://orestbida.com/demo-projects/iframemanager/demo1/), although it too does not handle dynamically injected iframes.

**Comment by gitVasile** [comment]
Hey @orestbida Thank you for your help. Should be fine.

Have a nice day
