### ISSUE TITLE
Feature Request: Allow all cookies button

### ISSUE THREAD

**Issue by TomPeirs** [orestbida/cookieconsent#6]
Hey!

I love your pure JS CSS solution to show a cookie consent banner.
However to bring this to it's full advantage I was wondering how I could add more buttons to the modal that is shown.

I would like to treat the "I understand" button as an Allow all cookies button, however I would also like to add other buttons which allow for selection such as "allow necessary cookies only"

**Comment by orestbida** [comment]
As of now the only way to add additional buttons is to **modify the source code**. 

The only issue is that the modal is small, and adding another button:

- I understand (accepts only the inital/default checked preferences)
- (**new**) Accept necessary only / Decline all
- Learn more / preferences

would "ruin" what little design there is. If this new button were to be added inside the **prefences modal** instead, it would be much better, (strictly speaking from the ui/design perspective), something like this (buttons on the bottom would stay fixed and always visible during the scroll inside the big modal):
![image](https://drive.google.com/uc?export=view&id=1OUWyZ8_ER1YRyz4m4P4ZyWCUs8g-oX9v)

**Comment by TomPeirs** [comment]
Alright, Thank you for reaching out, I still have to get a better understanding of the cookie handling itself, but I might Fork this repo and create a PR or simply share my changes if I manage something cool

**Comment by orestbida** [comment]
partially solved with the new v2 version, which allows for `accept all` and `accept necessary only` buttons. (A link/button to cookie settings can be added inside the description of the consent modal)
