### ISSUE TITLE
[Feat]: Description for Category-Services

### ISSUE THREAD

**Issue by paulwer** [orestbida/cookieconsent#612]
### Description

We would like to add descriptions with translations for each services of a category, which is according to the documentation currently not possible.

**Comment by orestbida** [comment]
Sorry, this won't be worked on. I'd like to avoid making the modal more complex.

**Comment by blackangelxl** [comment]
Try this:
`label: '<details><summary>Youtube</summary><small>Description....</small></details>',`

;-)
