### ISSUE TITLE
[Docs]: Migrating from version 2 to version 3

### ISSUE THREAD

**Issue by ioweb-gr** [orestbida/cookieconsent#615]
### What is the improvement/update you wish to see?

I was searching the documentation topics to find a guide or reference to breaking changes and I couldn't find them consolidated. 

Would it be possible to add a mini guide on how to migrate from version 2 to version 3?

**Comment by orestbida** [comment]
The reason why there's no guide is because v3 is completely different from v2; the configuration and the API have all been reworked.

It would be simpler to just go through the docs. and set up the plugin from scratch rather than following a migration guide.
