### ISSUE TITLE
Disable cookieconsent on reactive variable

### ISSUE THREAD

**Issue by Reconnact** [orestbida/cookieconsent#630]
What would be the best way to disable the popping up of the cookie consent when a variable that can be accessed from everywhere (authed) is set to true? I want to keep the whole default functionality (if no cookies are chosen show the cookie consent) but make an exception for when the user is logged in. Thanks for the help!

_Originally posted by @Reconnact in https://github.com/orestbida/cookieconsent/discussions/629_

**Comment by orestbida** [comment]
If the variable can be accessed on the client side, then you can achieve this via the [`autoShow`](https://cookieconsent.orestbida.com/reference/configuration-reference.html#autoshow) property.

For example, assuming the variable is called "isLoggedIn" and that it's a boolean, you would have to do something like this:
```js
CookieConsent.run({
    autoShow: isLoggedIn !== true
    ...
})

**Comment by Reconnact** [comment]
Thanks! I combined this logic with a watch to show/hide when user is logging out/in so it feels seemless:

```
  watch(isLoggedIn, () => {
    const preferences = cc.getUserPreferences();
    if (isLoggedIn) {
      cc.hide();
    } else if (preferences['accepted_categories'].length == 0) {
      cc.show();
    }
  });
  ```

**Comment by orestbida** [comment]
I would suggest using the `validConsent()` method to determine if the plugin should be shown or not, rather than manually checking the array of categories.
