### ISSUE TITLE
[Bug]: Callbacks are not triggered in individually togglable services.

### ISSUE THREAD

**Issue by handplant** [orestbida/cookieconsent#640]
### Expected Behavior

The onAccept callbacks should be triggered for all services, including Personio, when the user accepts the corresponding category/service.

### Current Behavior

The onAccept callbacks are triggered for YouTube and Vimeo services, but not for the Personio service.

### Steps to reproduce

Set up a web application with my categories/services functionality.

Here are my categories/services. 

```
  categories: {
    necessary: {
      readOnly: true,
      enabled: true,
    },
    videos: {
      services: {
        youtube: {
          label: 'Youtube Embed',
          onAccept: () => {
            console.log('accept youtube');
          }
        },
        vimeo: {
          label: 'Vimeo Embed',
          onAccept: () => {
            console.log('accept vimeo');
          }
        },
      },
    },
    personio: {
      label: 'Personio',
      onAccept: () => {
        console.log('accept personio');
      }
    }
  },
```

### Version

3.0.0

### On which browser do you see the issue?

Chrome

**Comment by orestbida** [comment]
You have declared personio outside services, as a category: `[necessary, videos, personio]`

**Comment by handplant** [comment]
I would like it to be visually and functionally like this!

![Bildschirmfoto 2024-02-13 um 08 54 14](https://github.com/orestbida/cookieconsent/assets/2598962/d5b55a32-ee81-459e-931d-9a6d392c34b7)

If I only have one service, then the following doesn't make sense, right? Or am I misunderstanding something?

![Bildschirmfoto 2024-02-13 um 08 57 06](https://github.com/orestbida/cookieconsent/assets/2598962/b4101b81-95f7-4b6a-976f-50ecc53ae7f4)

Am I correct in understanding that categories themselves don't have callbacks?
Thank you!

**Comment by handplant** [comment]
Okay, I'm now solving it through the CookieConsent onChange callback! 

```
  onChange: ({ cookie, changedCategories, changedServices }) => {
    if (cookie.categories.includes('personio')) {
      im.acceptService('personio');
    } else {
      im.rejectService('personio')
    }
  },
```

Thank you very much for this first-class consent management tool!
