### ISSUE TITLE
[Bug]: esm version has no cookieConsent variable

### ISSUE THREAD

**Issue by ourmaninindia** [orestbida/cookieconsent#656]
### Expected Behavior

after importing the esm version I get an error message that cookieConsent is not defined which is true. As a result I was forced to use the umd version.  

I much prefer using the esm as I use ES6 vanilla javascript 

### Current Behavior

cookieConsent missing when using https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.0/dist/cookieconsent.esm.js

### Steps to reproduce

just open the file

### Proposed fix or additional info.

export the cookieConsent variable as u=in the umd version

### Version

3.0.0

### On which browser do you see the issue?

Firefox

**Comment by orestbida** [comment]
I'm not sure I understand the issue. 

The UMD version is attached to the window object and is globally accessible. The ESM version is imported in the current context only, which is the expected behavior of ESM, afaik.

**Comment by dreinon** [comment]
Same issue here after importing 
```js
import CookieConsent from 'vanilla-cookieconsent';
```
 I get this error:
![image](https://github.com/orestbida/cookieconsent/assets/67071425/ab3df561-db73-4092-9b60-2204e70e2078)

**Comment by orestbida** [comment]
@ourmaninindia there is no default export so that won't work.

You should use the `import *` syntax, as shown in the docs:
```js
import * as CookieConsent from 'vanilla-cookieconsent';
```

**Comment by dreinon** [comment]
Right, it might be a good idea to also export it as default, since linters recommend you import as default instead of with "*"

**Comment by dreinon** [comment]
![image](https://github.com/orestbida/cookieconsent/assets/67071425/b151e6ae-a89f-4611-b632-317ea1c63254)

**Comment by orestbida** [comment]
It mostly boils down to personal preference. 
I like the explicitness of named exports. They are more flexible and clearer to me.

This clearly conveys that you are willingfully loading everything:
```js
import * as CookieConsent from 'vanilla-cookieconsent';
```

I would have used a default export if there was only one function exported.
