### ISSUE TITLE
[DEMO]: NextJS 12 demo doesn't seem to work

### ISSUE THREAD

**Issue by nik32** [orestbida/cookieconsent#659]
### What is the improvement/update you wish to see?

Wanted to know if the package works with NextJS 12 (The demo given [here](https://stackblitz.com/edit/nextjs-epd84e?file=package.json) wasn't working)? If it does work with NextJS 12 then would wish to see it working

### Link the related docs page, if it exists.

https://stackblitz.com/edit/nextjs-epd84e?file=package.json

**Comment by orestbida** [comment]
It's working fine on my end, did you try with a different browser?

**Comment by nik32** [comment]
@orestbida thanks for the quick reply! I tried on safari... it did not compile only. Then I tried with edge... it compiled but nothing is shown in the output tab... its blank white

**Comment by orestbida** [comment]
Stackblitz is not perfect. After the successfull compilation try reloading the right pane (preview iframe).

Alternatively you can download the entire demo as a zip file, extract it in a folder, run npm install and then start the app.

**Comment by nik32** [comment]
You are right... there might be an issue with stackblitz... coz it ran on my local with NextJS 12. Thanks a lot for the replying and Kudos for this library! It's awesome 🙌!
