### ISSUE TITLE
[Bug]: Translations

### ISSUE THREAD

**Issue by DmytroIvantsov** [orestbida/cookieconsent#670]
### Expected Behavior

I think translations must be updated dynamically when the page language changed

### Current Behavior

Nuxt 3, i18n, translations are not updated dynamically when the page language is changed, even if the page's lang attribute has been changed.

### Steps to reproduce

1. Open page
2. Change language without page reloading
3. There are no translations in the cookie settings window

### Version

3.0.1

**Comment by orestbida** [comment]
The plugin is vanilla js, you need to manually call [`.setLanguage()`](https://cookieconsent.orestbida.com/reference/api-reference.html#setlanguage) as it's not aware of the changes outside, unless you reload the page.

**Comment by DmytroIvantsov** [comment]
Thank you, @orestbida
