### ISSUE TITLE
Clarify cookieconsent's initialization methods

### ISSUE THREAD

**Issue by lamtonylam** [orestbida/cookieconsent#68]
After navigating on the site, cookie settings won't open anymore.

See on my website at the bottom of the site: [opkh.fi](https://opkh.fi)

Here's the code
`<button type="button" class="btn btn-outline-primary" aria-label="View cookie settings" data-cc="c-settings">Muokkaa evästeasetuksia</button>
`

**Comment by orestbida** [comment]
Hi @lamtonylam,

from the looks of it, you are running the script **before** the rest of `body` has been loaded. To fix this, you should simply put the script at the bottom, just before the `</body>` tag.

Or alternatively you can:
1. add the `defer` attribute to cookieconsent.js
2. put your cookieconsent init code inside this function

    ```javascript
    window.addEventListener('load', function(){
        var cookieconsent = initCookieConsent();
                 
        cookieconsent.run(...);
    });

By doing so, the cookieconsent won't run until the body section has been loaded (and it can now bind that button to open the settings modal)

I should make this clearer in the docs.

**Comment by lamtonylam** [comment]
Thank you! All fixed now!
