### ISSUE TITLE
[Bug]: CookieConsent v3 with Next.js

### ISSUE THREAD

**Issue by combi-35** [orestbida/cookieconsent#681]
### Expected Behavior

How can we use v3 with Next.js?
In the documentation I only read about React, when trying to use it the same way with next.js I got:
`TypeError: can't convert undefined to object`

I was using v2 for the last 2 years with this setup mentioned here: #303 
But I dont see `initCookieConsent` anymore, so I guess the setup has to be different for v3 with next.js.

### Version

3.0.1

### On which browser do you see the issue?

Firefox, Chrome

**Comment by judict** [comment]
You don't need the old methods anymore. You can just use .run().

**Comment by orestbida** [comment]
@combi-35, v3 contains many breaking changes that makes it non compatible with v2.

You can find many demos [here](https://stackblitz.com/@orestbida/collections/cookieconsent-v3).  [Demo with Next.js 13](https://stackblitz.com/edit/stackblitz-starters-gobdmp?file=components%2FCookieConsent.tsx,components%2FCookieConsentConfig.ts,app%2Flayout.tsx)
