### ISSUE TITLE
Add options to set accessible names

### ISSUE THREAD

**Issue by basterrika** [orestbida/cookieconsent#689]
### Description

When using the library, PageSpeed Insights returns the error 'Elements with role=“dialog” or role=“alertdialog” do not have accessible names.'.

<img width="956" alt="error" src="https://github.com/orestbida/cookieconsent/assets/15806324/76ba71a5-0fad-4910-a609-04786f64b7b1">

It would be nice if consentModal had a parameter to set this value to fix the error.

**Comment by orestbida** [comment]
Fair enough.

By the way, this occurs only when you omit the title.

**Comment by basterrika** [comment]
Does this mean that the parameter will be added or that I have to settle for the title? 😅

**Comment by orestbida** [comment]
Yes, there will be a new field to handle cases like yours.

**Comment by orestbida** [comment]
NVM, I had forgotten that there's already a [`consentModal.label`](https://cookieconsent.orestbida.com/reference/configuration-reference.html#translation-consentmodal) option.

```javascript
translations: {
    'en': {
        consentModal: {
            label: 'Cookie Consent Modal',
            ...
        }
    }
}
