### ISSUE TITLE
Custom cookie data / visitor identification

### ISSUE THREAD

**Issue by timiwahalahti** [orestbida/cookieconsent#69]
_I absolutely love this little JS library and don't want to ask anything that could bloat its code unnecessarily._

Given that (at least) the Finnish authorities require that you can point the time when the visitor has accepted the cookies, we've implemented custom consent recording which saves these details to our database. Just to be on the safe side, as there is no precedent what this actually means.

Currently, the way how we've done this is a bit hacky, as it used separate cookie for giving each visitor their own UUID which is then used to "identify" visitors if needed. It works, though having everything in one cookie would be most ideal.

I do wish there would be a way to add custom data into the cookie OR having a native feature for generating visitor identifications. I will leave it up to you which way would be better, if any.

BTW we are packaging CookieConsent and IframeManager into WordPress plugin which will be published Open Source soon(ish) :)

**Comment by orestbida** [comment]
Yea, I'm going to leave the “generate visitor id” thing up to you!

As I see it, adding 2 methods like `.setCookieData(<object>)` and `.getCookieData()` would probably be the simplest route to achieve this. It would work as follows:

```javascript
// add/update only the specified fields
cookieconsent.setCookieData('update', {
    uuid: '5ed91576-aa9a-4389-b696-f2470ca6e253',
    country: 'Italy',
    date: + new Date()
});

// overwrite existing data with the following (empty) object
cookieconsent.setCookieData('overwrite', {});

// retrieve stored data
cookieconsent.getCookieData();
```

Cool! Can't wait to see them on WP!

**Comment by timiwahalahti** [comment]
Sounds promising! Thanks for considering this :)

**Comment by lamtonylam** [comment]
@timiwahalahti 
Hello, a fellow Finnish here! I am also interested in this. I didn't know that Finnish authorities required this! 
Can you tell me more?
