### ISSUE TITLE
[Bug]: INP Problem

### ISSUE THREAD

**Issue by agracia-foticos** [orestbida/cookieconsent#691]
### Expected Behavior

In Google Web Core Vitals 

![image](https://github.com/orestbida/cookieconsent/assets/77386602/37f8ce82-dd55-48d9-863b-8210c8695787)

Problem with INP when closes cookie consent

### Current Behavior

In Google Web Core Vitals 

![image](https://github.com/orestbida/cookieconsent/assets/77386602/37f8ce82-dd55-48d9-863b-8210c8695787)

Problem with INP when closes cookie consent

### Steps to reproduce

In Google Web Core Vitals 

![image](https://github.com/orestbida/cookieconsent/assets/77386602/37f8ce82-dd55-48d9-863b-8210c8695787)

Problem with INP when closes cookie consent

### Version

3.0.1

**Comment by orestbida** [comment]
Unless you provide a demo I won't be able to help you.

**Comment by bennetsadyba** [comment]
@agracia-foticos did you manage to solve this problem?
Google Search Console reports this issue as you described.

**Comment by agracia-foticos** [comment]
@bennetsadyba actually we dont use this module, we prefer a custom implementation of consent
