### ISSUE TITLE
[Bug]: In translated / i18n projects, the config dialog does not work in the second language

### ISSUE THREAD

**Issue by ascheucher-shopify-partner** [orestbida/cookieconsent#693]
### Expected Behavior

In Astro projects with i18n support, the configuration dialog should work in all languages.

<img width="561" alt="Config dialog working" src="https://github.com/orestbida/cookieconsent/assets/140156444/21ff330c-4ea0-4151-b415-0ff132db3b17">

### Current Behavior

Switching to the non default language, there are no buttons and no heading styling for the sections in the config dialog.

<img width="560" alt="Config dialog broken" src="https://github.com/orestbida/cookieconsent/assets/140156444/af1c2899-6f11-4301-b5f2-05f593261616">

### Steps to reproduce

I have created a [minimal Astro project with DE & EN support on StackBlitz](https://stackblitz.com/edit/withastro-astro-htqoen?file=src%2Fpages%2F%5Blang%5D%2Findex.astro)

* open the minimal project
* wait for it to build and let it load the working EN version of the page
* open the preferences to see it working
* close the preferences
* click the **switch to DE** link below the **welcome to Astro** heading
* click the **Einstellungen** button to see the broken dialog

### Proposed fix or additional info.

Sorry, I don't have any suggestion on how to solve the issue.

Thanks for having a look.

### Version

3.0.1

### On which browser do you see the issue?

Chrome

**Comment by ascheucher-shopify-partner** [comment]
Ah, want to add:

Comparing the DOM in the EN and DE version of the open settings dialog, there are some nodes missing in the DE version.

**Comment by orestbida** [comment]
The configuration for the de translation is not correct. You should not translate the "linkedCategory" value, as that is used to reference a specific category. 

By translating it, it's no longer able to find a valid category, and just renders a normal section block.
