### ISSUE TITLE
[Feat]: Allow apply custom css to buttons

### ISSUE THREAD

**Issue by agracia-foticos** [orestbida/cookieconsent#694]
### Description

Allow apply custom different css to accept, dissmiss and config 

### Proposed solution

Allow apply custom different css to accept, dissmiss and config 

### Additional details

Allow apply custom different css to accept, dissmiss and config

**Comment by orestbida** [comment]
You can change the colors via css variabiles or you can use your own custom css to override the default styles.

**Comment by agracia-foticos** [comment]
But we want to apply directly diferent classes to specific buttons.

One case is we want customize the order of buttons, and apply this styles https://tailwindcss.com/docs/order
