### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cankoman** [orestbida/cookieconsent#696]
### Expected Behavior

I have 3 categories in the preferences modal (necessary, analytics and marketing). Under necessary there are two, under analytics one service and under marketing 3 services.
When I click on "accept all", all categories and services are saved correctly and set in the json.
When the page is reloaded and the preferences modal is opened again via a button, all categories and services are correctly set to "On". If "Save preferences" is now clicked, all categories and services have to be saved as before and should be under "acceptedCategories" AND "acceptedServices".``

### Current Behavior

I have 3 categories in the preferences modal (necessary, analytics and marketing). Under necessary there are two, under analytics one service and under marketing 3 services.
When I click on "accept all", all categories and services are saved correctly and set in the json (screenshot 1).
When the page is reloaded and the preferences modal is opened again via a button, all categories and services are correctly set to "On". If "Save preferences" is now clicked (screenshot 2), all categories are correctly saved to "On", but the services are set to "Off". 
all services, except for those under "necessary", will end up under "rejectedServices"!

![Screenshot1](https://github.com/orestbida/cookieconsent/assets/173061955/2805df7a-7dad-4d0a-ace3-18bfda1d2cf3)
![Screenshot2](https://github.com/orestbida/cookieconsent/assets/173061955/3c1a0a86-9e5c-4dba-91bc-d772013165bf)

### Steps to reproduce

1. open Preferences Modal -> click on "accept all"
2. reload the page
3. open Preferences Modal again -> click on "Save preferences"
4. open Preferences Modal and check the services (were set incorrectly)

### Version

3.0.1

### On which browser do you see the issue?

Firefox, Chrome

**Comment by peaemaye** [comment]
This sounds like the same bug I reported as #700. I've submitted a PR with a fix here: https://github.com/orestbida/cookieconsent/pull/701

**Comment by cankoman** [comment]
Thank you @peaemaye!

**Comment by orestbida** [comment]
Should be fixed by #701
