### ISSUE TITLE
On modal visible action

### ISSUE THREAD

**Issue by dimmuboy** [orestbida/cookieconsent#70]
How can I do some action when user open modal with preferences?
I'm using fullPage.js so when I scroll in modal it scrolls my page on background instead modal. I would like to disable fullPage.js scrolling when modal is opened and enable it back when modal disappear.

**Comment by orestbida** [comment]
Hi @dimmuboy,

unfortunately, there is no built-in option to do such a thing. You can however use a `MutationObserver` — supported by all major browsers — to detect the open/closed state of the modal:

```javascript
(function(){
    let html = document.documentElement, 
        isVisible = false, 
        shouldShow = false;

    const observer = new MutationObserver(function() {
        shouldShow = html.className.indexOf('show--settings') > -1;

        if(!isVisible && shouldShow){
            isVisible = true;
            console.log("modal is visible")
        }else if(isVisible && !shouldShow){
            isVisible = false;
            console.log("modal is hidden")
        }
    });

    observer.observe(html, { 
        attributes: true, 
        attributeFilter: ['class']
    });
})();
```

**Comment by dimmuboy** [comment]
Great @orestbida, it works! I'm able to to disable and enable fullpage.js back now.
But I still have problem scroll content inside preferences window. When I try to scroll it do nothing :/

https://dnmetalchrom.sk/

**Comment by orestbida** [comment]
based on [fullPage.js](https://github.com/alvarotrigo/fullPage.js#options), there's an option called `normalScrollElements` which sholud allow normal scrolling on specific elements. Try using it like this:

```javascript
normalScrollElements: "#s-bl"
```

**Comment by dimmuboy** [comment]
Awesome! It works, thanks
