### ISSUE TITLE
[Bug]: Brave Browser block consent modal (import script.js)

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [orestbida/cookieconsent#709]
### Expected Behavior

Hello, Brave block the vendor/cookieconsent.js :( in module import. 
https://community.brave.com/t/cookie-consent-is-blocked-by-brave-shield/559044

Thanks for help

### Current Behavior

The librairie JS is not loaded and blocked.

### Steps to reproduce

Use Brave Browser with Shield is activated, the script are blocked
![Capture d'écran 2024-07-21 113908](https://github.com/user-attachments/assets/212405fe-fd67-49b9-b9a9-5b0ed2996d2c)

### Version

3.0.1

### On which browser do you see the issue?

Other

**Comment by alxndr-w** [comment]
Works as expected: 

https://brave.com/shields/

**Comment by orestbida** [comment]
Unfortunately there's not much that I can do, unless they decide to whitelist the plugin.
