### ISSUE TITLE
[Feat]: Add Cookie's config option to set secure flag manually

### ISSUE THREAD

**Issue by LuksAO** [orestbida/cookieconsent#714]
### Description

When the Cookie is set in a parent domain, if the cookie is set in a domain with https, since it uses secure tag, it can not be accessed from http domains.

Then in http domains the cookie is shown again and again cause it can not be accessed nor set.

This behavior makes sense since you can't set a secure cookie in http but you should have an alternative for these cases.

### Proposed solution

Add a 'secure' boolean property in 'Cookie' interface.

Default can be 'true' maintaining current behavior (secure flag on if https and false if http).

If 'secure' is false then secure flag is never set.

Alternatively default value and current behavior can be undefined and when secure is true it may try to force secure flag.

**Comment by orestbida** [comment]
Seems like a good addition to me.
