### ISSUE TITLE
[Bug]: The selection is empty if prototype framework is used

### ISSUE THREAD

**Issue by claudiuj** [orestbida/cookieconsent#727]
### Expected Behavior

I know that Prototype is an old framework but it is still used by Magento 1.9.

### Current Behavior

When I use cookieconsent with Prototype (the latest version), the selection saved in the cookie is empty (the categories array is empty)

### Steps to reproduce

1. Create a config file using GUI interface
2. Create a simple HTML file that includes Prototype framework (I've attached a screenshot of the source
<img width="822" alt="Screenshot 2024-09-01 at 22 15 42" src="https://github.com/user-attachments/assets/35e39994-e466-4a2a-aaa8-7772b7fd363b">
)

3. Run HTML file in browser
4. Set cookie preference
5. Check the cookie value (categories array)

### Version

3.0.1

**Comment by orestbida** [comment]
@claudiuj, this is due to prototype modifying the standard `Array.from` function, see https://github.com/prototypejs/prototype/issues/338.

You can restore the default `Array.from` as suggested in https://github.com/prototypejs/prototype/issues/362:
```html
<script>
  const iframe = document.body.appendChild(
    document.createElement('iframe')
  );
  const iframeArray = iframe.contentWindow.Array;
  document.body.removeChild(iframe);
  Array.from = iframeArray.from;
</script>

<script type="module" src="cookieconsent-config.js"></script>
```

This might break other things in your page though.

**Comment by claudiuj** [comment]
it is working;

Thank you.
