### ISSUE TITLE
Cookies do not delete if remove_cookie_tables enabled

### ISSUE THREAD

**Issue by PWaddict** [orestbida/cookieconsent#73]
Hi, 

I've set autoclear_cookies and remove_cookie_tables to true but the cookies are not getting deleted when I'm pressing the "Reject All" button. If I set the remove_cookie_tables to false, press the "Reject All" button and then reload the page the cookies are getting deleted.

Can you please fix it?

**Comment by orestbida** [comment]
Hi @PWaddict,

expect a minor update soon!

**Comment by matin73** [comment]
I have same problem also if remove_cookie_tables is false. I can see in console log 
CookieConsent [AUTOCLEAR]: deleting cookie: '_ga' path: '/' domain: 
Array [ "www.xxx.at", ".www.xxx.at" ]

but cookie is not deleted. Analytics script is embeded via <script type="text/plain" data-cookiecategory="analytics">

**Comment by orestbida** [comment]
Hi @matin73,

please open a new issue as it is different from the one discussed here! You could also check out #55 and #65!
