### ISSUE TITLE
[Docs]: Most of the examples are not working

### ISSUE THREAD

**Issue by nycynik** [orestbida/cookieconsent#740]
### What is the improvement/update you wish to see?

most of these examples, do not work, I noticed the ally one does, but it does not show the v3 UI. 

https://stackblitz.com/@orestbida/collections/cookieconsent-v3

I'm new to cookieconsent, but I'm going to try to implement it today, and if I can figure out how to get it to work in my project, I might also figure out why they are all showing errors and I'll comment here if I can point towards fixes. 

### Link the related docs page, if it exists.

https://stackblitz.com/@orestbida/collections/cookieconsent-v3

**Comment by orestbida** [comment]
I tried the first 5 demos and they work fine on my end. 

Which demos exactly and on which browser?

**Comment by nycynik** [comment]
They are all working! I just clicked them all. I was in Chrome, and I was seeing a build error, but not today! Thanks for the quick response!

**Comment by nycynik** [comment]
Closing, working as expected.
