### ISSUE TITLE
Feature request: Expose a method to set the accepted revision

### ISSUE THREAD

**Issue by karptonite** [orestbida/cookieconsent#75]
It would be useful to have a method to set the revision in the cookie, in the same way the `.accept()` method lets us set accepted levels.

The use case is as follows: I want to persist the consent choices (and revision) of the user on the server, so that if the user logs in from a different browser, their consent choices are remembered. I do this by retrieving their choices from the server and calling `.accept()` on their choices client side, if the cookie is not found.

But this means that if their choices remain the same, but I push out a new revision, if they log in from a new browser, I'll automatically "accept" them at the same level, under the new revision. If I could also set the revision, then the plugin will be able to detect that the revisions don't match, and show the consent modal with the revision dialog.

**Comment by orestbida** [comment]
Shouldn't this already be possible? Example:

```javascript
(async function(){

    //fetch value from server
    const cc_config = await (await fetch('your_api_url')).json();

    const cc = initCookieConsent();
    
    cc.run({
        ...
        revision: cc_config.revision
        ...
    }

})();
```

Is a `.setRevision()` really needed? Do you plan on setting the revision number **after** the plugin has already been initialized?

**Comment by karptonite** [comment]
Yea, I plan to initialize the plug-in first, to the **current** revision, then to call **setRevison()** with whatever revision the user had previously agreed to (possibly an earlier revision). Would the purpose be more clear if the new function were called `acceptRevison()`? Or maybe there is a better way to handle this? The goal is to deal with the situation where a new revision is available, the user has agreed to an older revision, AND that user agreement is currently stored server side, not in the cookie.

**Comment by karptonite** [comment]
Thinking more, maybe adding a third "revision" parameter to `accept()` might be cleaner than a new method.

**Comment by orestbida** [comment]
I don't get why the current way doesn't fit your needs. Correct me if this is not what you want.
I assume you store a configuration parameter to manage the revision number on the server side, let's call it `server revision`:

1. fetch `server revision` value from the server
2. initialize the plugin with the fetched `server revision` value
3. the plugin will check if it has already been accepted (with the specified `server revision` value) or not: 
    1. cookieconsent is already accepted:
        1. `current cookie revision` === `server revision` :  great, don't show modal
        2. `current cookie revision` !== `server revision` : same as __*"cookieconsent has not yet been accepted"*__ case below
    2. cookieconsent has not yet been accepted: 
    show consent modal, and when consent is given, set cc_cookie with `revision = server revision`

Perhaps I'm missing your point.

**Comment by karptonite** [comment]
Thanks for the reply! Here is the issue I'm having a hard time explaining: if a logged in user grants us consent to use cookies, I send a request back to the server to persist that _on the server_. Then, if the same user logs in from another browser (or their cookies are cleared), I don't want them to have to consent again (they already have). As part of retrieving the account information from the server, I also retrieve the consent data.

So the part that the current system doesn't quite handle: I can call `accept` client side to set the current cookie to whatever the server says they have already agreed to. but I can't set the revision in the cookie to what they have already agreed to. Perhaps I am abusing the intended purpose of the `accept` method here?

The main goal here is to achieve the following. User X logs in on our site, and grants consent. Then User X logs in on a different device; they shouldn't have to grant consent again (they already have), UNLESS the revision has changed.

This is really only sort of a theoretical problem for now, but it will become real if I ever go to a new revision.

**Comment by karptonite** [comment]
To be even clearer, the current way requires the user's consent info to already be in a cookie. I'm sometimes getting it via a request, and setting it client side.

**Comment by orestbida** [comment]
I think I got it now. 

Whenever you call the `.accept()` method, cc_cookie is re-set*, which means that as long as you're initializing the plugin with the latest valid revision parameter (in your case, retrieved from the server), cc_cookie will be set correctly. 

The following code is executed after each `.accept()` call (** note at the bottom):
https://github.com/orestbida/cookieconsent/blob/9170f9067b288dcd51d9606f3c71094b3d7c0a8e/src/cookieconsent.js#L835-L843

So you shouldn't need a method to manually tell the plugin what the new revision should be.


Perhaps something like this works:

```javascript
// suppose this is the data fetched from the server
const server_preferences = {
    latest_revision: 3, 
    user_accepted_revision: 2,
    user_accepted_categories: ['necessary', 'analytics']
};

/*
 *  found server preferences for this user ?
 *    - no: should_ask_consent = true;
 *    - yes:
 *        1. saved user revision === latest valid revision: should_ask_consent = false;
 *        2. saved user revision !== latest valid revision: should_ask_consent = true;
 */
const should_ask_consent = server_preferences.latest_revision !== server_preferences['user_accepted_revision'];  

const cc = initCookieConsent();

cc.run({
    autorun: should_ask_consent,
    revision: server_preferences.latest_revision,
    ...
});

if (!should_ask_consent) {
    // consent already given
    // set/re-set cc_cookie (regardless of whether it already exists or not)
    cc.accept(server_preferences.user_accepted_categories);
}
```

Note: with the upcoming v2.6, calling multiple times `cc.accept()` will not necessarily re-set cc_cookie multiple times. It will be set only if at least one of the following states/changes occur:
- cc_cookie has not yet been set
- categories have changed
- revision has changed

**Comment by karptonite** [comment]
Hmm... Correct me if I'm wrong, but it seems to me that the proposed solution doesn't account for showing the `revision_message` when there is no cookie set (because the user is on a new browser) but we know (from the server data) that the user has accepted an outdated revision. One of the main appeals of the revision system is being able to ask for consent again while acknowledging that consent was previously granted (but is now outdated).

**Comment by orestbida** [comment]
Yes, it doesn't manage the `revision_message`. Although It can be adapted to do so, it is not an ideal solution.

**Comment by orestbida** [comment]
Hahaha, I like criticisms (especially constructive ones)!

The main issue is that as soon as `.run()` is executed, the modals are also generated! Since there is no initial parameter which can tell the plugin “there was a previous accepted revision by this user”, it will create the default modal without the `revision message` (if cookie is not found).

Re-working the `.accept()` method — at this point — would be a big breaking change! 

The easiest and most intuitive way to handle all of these cases — from my point of view — would be to simply add an option like `old_revision`. This way the plugin knows everything before generating the html!

- [yes] valid `revision` (number > -1) ?
  - [yes] valid `old_revision` (number > -1) ?
      - [yes] `revision` === `old_revision` ?
        - [yes] `.accept(<user_categories>)`
        - [ no] generate `consent_modal` with `revision_message`  and show
      - [ no] `cc_cookie` exists ?
        - [yes] `cc_cookie[revision]` === `revision` ?
          - [yes] don't do anything
          - [ no] generate `consent_modal` with `revision_message`  and show
        - [ no] generate `consent_modal` and show 
  - [ no] `cc_cookie` exists ?
    - [yes] don't do anything
    - [ no] generate `consent_modal` and show

Other cases? My question is: do you really need a method to set revision ?

**Comment by karptonite** [comment]
Yes, an `old_revision` option might work. But, to make it even more consistent, what about an option like `accepted_consent` that would have the same format as the cookie? essentially an `old_everything`. `{level:[], revision: 1}`.  

If `accepted_consent` is set and is different from what is already in the cookie (or if the cookie is missing), then, in `run()`, you could stick the `accepted_consent` into the cookie at the beginning, and then proceed as normal with no other special logic--it could proceed exactly as if it found the `accepted_consent` in the cookie.

Then you could just do:
`cookieconsent.run()` with the revision set to the current revision, and the `accepted_consent` set to the user's preferences. If the revisions have a mismatch, the system already handles that. Wouldn't need to separately run `accept()`, and, possibly could even use `autorun` to show, depending on the use case.

**Comment by orestbida** [comment]
Yes, as long as the cookie set from the server can be decoded using `decodeUriComponent`!
