### ISSUE TITLE
Option to show the cookie settings button. css style. (z-index).

### ISSUE THREAD

**Issue by samuelmarkno** [orestbida/cookieconsent#8]
Hi, I found your plugin a few days ago and it's great. In a future version, could you add this fixed button CSS style for cookie settings to c_m_primary__btn, c_s_acceptall_btn, c_s_s_s_save__btn events. Default to be shown when accepting any of those ID's that the button changes display:none --> display: block

example my button: https://codepen.io/pacmancode/pen/rNWzRod

Again, this is a great plugin.

Greetings.

**Comment by orestbida** [comment]
Nice, but still I think I'll stick to the orginal idea, and that is to keep it as simple as possible. If you feel like this deserves its own version you're welcome to clone the repo and apply the changes you proposed!

**Comment by samuelmarkno** [comment]
Thank you for taking the time to respond to my request, I will do so. Without further ado, I will close this issue.
