### ISSUE TITLE
Issue with implementation of use_rfc_cookie

### ISSUE THREAD

**Issue by karptonite** [orestbida/cookieconsent#87]
Thanks so much for adding the `use_rfc_cookie` functionality!

I don't want to sound ungrateful, since this is a real improvement, but since this just rolled out, maybe it is not too late to reconsider the implementation of this. Here is the issue: a base64 encoded cookie is hard to read, which obviously makes debugging more difficult. 

I believe you could achieve the same level of RFC compliance, with simpler code, by using `encodeURIComponent` and `decodeURIComponent`.  This would be easier to read not only because fewer character would be encoded, but also chrome, at least, expects this sort of behavior in the debugger, and has a checkbox to let you show the decoded value:

<img width="672" alt="Screen Shot 2021-10-08 at 9 49 06 AM" src="https://user-images.githubusercontent.com/132278/136568689-65f7cc1f-20a4-4f28-9327-bd2f61d577c2.png">

**Comment by orestbida** [comment]
Yes, it's easier now so I might remove the `.set('revision')` method whenever v3 is released!
