### ISSUE TITLE
Conflict with YouTube comment hider extensions

### ISSUE THREAD

**Issue by wzol** [orestbida/cookieconsent#94]
Just found out that the cookie dialog doesn't show up if some comment blocker extension is enabled - example https://chrome.google.com/webstore/detail/shut-up-comment-blocker/oklfoejikkmejobodofaimigojomlfim/ using https://github.com/panicsteve/shutup-css/blob/master/shutup.css

It seems it auto hides `#cm` here:

```
/* YouTube */
#watch-comment-panel,
#watch-comments-core,
#watch-discussion,
#comments-test-iframe,
#cm,
ytm-comment-section-renderer,
```

This is especially problematic when you use `force_consent` - in that case there is just a black overlay without any way to continue.

Any idea how to fix / workaround this problem?

**Comment by orestbida** [comment]
Hi @wzol,

until v2.7 comes out, you should be able to fix the issue with a little css:

```css
#cc_div #cm {
    display: block!important;
}
```

**Comment by wzol** [comment]
Awesome, thank you!
