### ISSUE TITLE
enable logs with config

### ISSUE THREAD

**Issue by combi-35** [orestbida/cookieconsent#97]
Hi,
for now logs are enabled by default and the only way to change this is to directly modify the libraries code.
It would be great if this could be a parameter in configs.

Thanks for the amazing library :)

**Comment by orestbida** [comment]
Hi @combi-35,

logs are enabled only on the "source" version (meant for those who want to modify the plugin) and such an option would be useless when used on the "dist" version (dead code). I would have agreed with you if logs were also present on the dist version!
